-- Percentual de IR
SELECT * FROM SED010 WHERE ED_MSBLQL <> '1' AND ED_PERCIRF > 0;

-- Notas com valor de IR a 1%
SELECT F1_SERIE, F1_DOC, F1_FORNECE, F1_LOJA, F1_EMISSAO, F1_IRRF, F1_VALBRUT, F1_VALBRUT * 0.015 AS F1_IRRF_OK
  FROM SF1010 
 WHERE F1_IRRF > 0 AND F1_IRRF = F1_VALBRUT * 0.010 AND D_E_L_E_T_ = ' '
 ORDER BY R_E_C_N_O_;