Select SE5.*
  FROM SE5010 SE5
  LEFT JOIN SA6010 SA6 ON E5_BANCO = A6_COD AND E5_AGENCIA	= A6_AGENCIA AND E5_CONTA = A6_NUMCON
 WHERE E5_FILIAL = '01' AND E5_DTDISPO = '20120119' and A6_FILIAL = '  '
   AND E5_BANCO = '237' AND E5_AGENCIA = '2818' AND E5_CONTA = '7985-5' 
   AND E5_TIPODOC NOT IN ('DC','JR','MT','CM','D2','J2','M2','C2','V2','CP','TL','BA') 
   AND NOT (E5_MOEDA IN ('C1','C2','C3','C4','C5','CH') AND E5_NUMCHEQ = '               ' AND (E5_TIPODOC NOT IN('TR','TE'))) 
   AND NOT (E5_TIPODOC IN ('TR','TE') AND ((E5_NUMCHEQ BETWEEN '*              ' AND '*ZZZZZZZZZZZZZZ') OR (E5_DOCUMEN BETWEEN '*                ' AND '*ZZZZZZZZZZZZZZZZ' ))) 
   AND NOT (E5_TIPODOC IN ('TR','TE') AND E5_NUMERO = '      ' AND E5_MOEDA NOT IN ('CC', 'CD', 'CH', 'CO', 'DOC', 'FI', 'R$', 'TB', 'TC', 'VL') )
   AND E5_SITUACA <> 'C' AND E5_VALOR   <> 0 
   AND NOT (E5_NUMCHEQ BETWEEN '*              ' AND '*ZZZZZZZZZZZZZZ') 
   AND (E5_VENCTO <= '20120119' OR E5_VENCTO <= E5_DATA) 
   AND SE5.D_E_L_E_T_ = ' ' AND SA6.D_E_L_E_T_ = ' '
 ORDER BY SE5.R_E_C_N_O_; 