SELECT F3_FILIAL, F3_CFO, SUM(F3_VALCONT) AS F3_VALCONT,  SUM(F3_BASEICM) AS F3_BASEICM, SUM(F3_VALICM) AS F3_VALICM, SUM(F3_ISENICM) AS F3_ISENICM, SUM(F3_OUTRICM) AS F3_OUTRICM
  FROM SF3700 SF3
 WHERE D_E_L_E_T_ = ' ' AND F3_ENTRADA BETWEEN '20180301' AND '20180331'
   AND F3_TIPO <> 'S'
 GROUP BY F3_FILIAL, F3_CFO
 ORDER BY F3_FILIAL, F3_CFO

-- Conferência das notas de entrada - ICMS e IPI
SELECT F3_CFO, F3_NFISCAL, F3_SERIE, F3_CLIEFOR, F3_LOJA, F3_IDENTFT, F3_VALCONT, 
       CASE WHEN ROUND(F3_BASEICM + F3_ISENICM + F3_OUTRICM + CASE WHEN F3_BASEICM = F3_VALCONT THEN 0 ELSE F3_VALIPI END, 2) <> F3_VALCONT THEN 1 Else 0 End AS DIFFICM,
       ROUND(F3_BASEICM + F3_ISENICM + F3_OUTRICM + CASE WHEN F3_BASEICM = F3_VALCONT THEN 0 ELSE F3_VALIPI END, 2) AS F3_VALCONT_ICM, 
       F3_BASEICM, F3_ALIQICM, F3_VALICM, F3_ISENICM, F3_OUTRICM, 
       CASE WHEN ROUND(SF3.F3_BASEIPI + SF3.F3_ISENIPI + SF3.F3_OUTRIPI + SF3.F3_VALIPI, 2) <> F3_VALCONT THEN 1 Else 0 End AS DIFFIPI,
       ROUND(SF3.F3_BASEIPI + SF3.F3_ISENIPI + SF3.F3_OUTRIPI + SF3.F3_VALIPI, 2) AS F3_VALCONT_IPI,
       F3_BASEIPI, F3_VALIPI, F3_ISENIPI, F3_OUTRIPI, F3_DTCANC
  FROM SF3010 SF3
 WHERE D_E_L_E_T_ = ' ' AND F3_ENTRADA BETWEEN '20130701' AND '20130731'
   AND F3_TIPO <> 'S'
   AND (ROUND(F3_VALCONT, 2) <> ROUND(F3_BASEICM + F3_ISENICM + F3_OUTRICM + 
        CASE WHEN F3_BASEICM = F3_VALCONT THEN 0 ELSE F3_VALIPI END, 2)
     OR ROUND(SF3.F3_VALCONT, 2) <> ROUND(SF3.F3_BASEIPI + SF3.F3_ISENIPI + SF3.F3_OUTRIPI + SF3.F3_VALIPI, 2))
 ORDER BY F3_CFO, F3_NFISCAL, F3_SERIE, F3_CLIEFOR, F3_LOJA, F3_IDENTFT;
 
-- Conferência dos itens notas de entrada - ICMS e IPI
SELECT FT_CFOP, FT_NFISCAL, FT_SERIE, FT_ITEM, FT_CLIEFOR, FT_LOJA, FT_IDENTF3,  FT_VALCONT, 
       CASE WHEN ROUND(FT_BASEICM + FT_ISENICM + FT_OUTRICM + CASE WHEN FT_BASEICM = FT_VALCONT THEN 0 ELSE FT_VALIPI END, 2) <> FT_VALCONT THEN 1 Else 0 End AS DIFFICM,
       ROUND(FT_BASEICM + FT_ISENICM + FT_OUTRICM + FT_VALIPI, 2) AS FT_VALCONT_ICM, 
       FT_BASEICM, FT_ALIQICM, FT_VALICM, FT_ISENICM, FT_OUTRICM, 
       CASE WHEN ROUND(FT_BASEIPI + FT_ISENIPI + FT_OUTRIPI + FT_VALIPI, 2) <> FT_VALCONT THEN 1 Else 0 End AS DIFFIPI,
       ROUND(FT_BASEIPI + FT_ISENIPI + FT_OUTRIPI + FT_VALIPI, 2) AS FT_VALCONT_IPI, 
       FT_BASEIPI, FT_ALIQIPI, FT_VALIPI, FT_ISENIPI, FT_OUTRIPI, FT_DTCANC
  FROM SFT010 WHERE D_E_L_E_T_ = ' ' AND FT_ENTRADA BETWEEN '20130601' AND '20130631'
   AND FT_TIPO <> 'S'
   AND (ROUND(FT_VALCONT, 2) <> ROUND(FT_BASEICM + FT_ISENICM + FT_OUTRICM + 
                            CASE WHEN FT_BASEICM = FT_VALCONT THEN 0 ELSE FT_VALIPI END, 2) OR
        ROUND(FT_VALCONT, 2) <> ROUND(FT_BASEIPI + FT_ISENIPI + FT_OUTRIPI + FT_VALIPI, 2))
 ORDER BY FT_CFOP, FT_NFISCAL, FT_ITEM;
 
-- Entradas
SELECT SUM(F3_VALICM)
  FROM SF3010 
 WHERE D_E_L_E_T_ = ' ' AND F3_ENTRADA BETWEEN '20130601' AND '20130630' AND F3_CFO < '5000' AND F3_DTCANC = ''
   AND F3_TIPO <> 'S';
 
-- Saidas
 SELECT SUM(F3_VALICM)
  FROM SF3010 
 WHERE D_E_L_E_T_ = ' ' AND F3_ENTRADA BETWEEN '20130601' AND '20130630' AND F3_CFO > '5000' AND F3_DTCANC = ''
   AND F3_TIPO <> 'S';
 