-- Itens das Notas
SELECT TOP 1 FT_CODBCC, FT_CSTPIS, FT_CSTCOF, * FROM SFT010

SELECT FT_CODBCC, FT_CSTPIS, FT_CSTCOF, * FROM SFT010 WHERE FT_CSTPIS <> '';

UPDATE SFT010 SET FT_CODBCC = '01';

-- Situação da TES
SELECT TOP 1 F4_CODBCC, F4_CSTPIS, F4_CSTCOF, * FROM SF4010 WHERE F4_CSTPIS <> '';

UPDATE SF4010 SET F4_CODBCC = '01';



