SELECT FT_NFISCAL, FT_ITEM, * 
  FROM SFT010 WHERE D_E_L_E_T_ = ' ' AND FT_NFISCAL IN ('000000284', '000000285') 
   AND FT_CLIEFOR = '001631'
 ORDER BY FT_NFISCAL, FT_ITEM
 
INSERT INTO SFT010 (R_E_C_N_O_, D_E_L_E_T_, FT_FILIAL, FT_NFISCAL, FT_SERIE, FT_ITEM, FT_ENTRADA, 
                    FT_EMISSAO, FT_CLIEFOR, FT_LOJA, FT_ESTADO, FT_CFOP, FT_VALCONT, FT_ESPECIE, 
                    FT_CONTA, FT_PRODUTO, FT_TIPOMOV, FT_CLASFIS, FT_CTIPI, FT_BASEIRR, 
                    FT_ALIQIRR, FT_VALIRR, FT_BASEINS, FT_ALIQINS, FT_VALINS, FT_POSIPI, FT_IDENTF3, 
                    FT_ESTOQUE, FT_DESPIPI, FT_QUANT, FT_PRCUNIT, FT_TOTAL, FT_BASEPIS, FT_ALIQPIS, 
                    FT_VALPIS, FT_BASECOF, FT_ALIQCOF, FT_VALCOF, FT_RECISS, FT_ALIQSOL, FT_ALQFECP, 
                    FT_CSTPIS, FT_CSTCOF, FT_CODBCC, FT_BRETPIS, FT_BRETCOF, FT_BRETCSL, FT_VRETPIS, 
                    FT_VRETCOF, FT_VRETCSL, FT_ARETPIS, FT_ARETCOF, FT_ARETCSL, FT_TNATREC, FT_CNATREC)
SELECT (SELECT MAX(R_E_C_N_O_) FROM SFT010) + ROW_NUMBER() OVER(ORDER BY D1_DOC, D1_ITEM) AS R_E_C_N_O_, 
       ' ' AS D_E_L_E_T_, D1_FILIAL AS FT_FILIAL, D1_DOC AS FT_SERIE, D1_SERIE AS FT_SERIE, 
       D1_ITEM AS FT_ITEM, D1_DTDIGIT AS FT_ENTRADA, D1_EMISSAO AS FT_EMISSAO, D1_FORNECE AS FT_CLIEFOR, 
       D1_LOJA AS FT_LOJA,'SP' AS FT_ESTADO, D1_CF AS FT_CFOP, D1_TOTAL AS FT_VALCONT, 'NFS' AS FT_ESPECIE, 
       D1_CONTA AS FT_CONTA, D1_COD AS FT_PRODUTO, 'E' AS FT_TIPOMOV, 
       '041' AS FT_CLAFIS, '99' AS FT_CTIPI, D1_BASEIRR AS FT_BASEIRR, D1_ALIQIRR AS FT_ALIQIRR,
       D1_VALIRR AS FT_VALIRR, D1_BASEINS AS FT_BASEINS, D1_ALIQINS AS FT_ALIQINS, D1_VALINS AS FT_VALINS,
       '99999999' AS FT_POSIPI, '000001' AS FT_IDENTF3, 'N' AS FT_ESTOQUE, 'S' AS FT_DESPIPI, 
       D1_QUANT AS FT_QUANT, D1_VUNIT AS FT_PRCUNIT, D1_TOTAL AS FT_TOTAL, D1_TOTAL AS FT_BASEPIS,
       1.65 AS FT_ALIQPIS, D1_TOTAL * (1.65 / 100) AS FT_VALPIS, 
       D1_TOTAL AS FT_BASECOF, 7.6 AS FT_ALIQCOF, D1_TOTAL * (7.6 / 100) AS FT_VALCOF, '2' AS FT_RECISS,
       18 AS FT_ALIQSOL, 1 AS FT_ALQFECP, '50' AS FT_CSTPIS, '50' AS FT_CSTCOF, '03' AS FT_CODBCC,
       D1_TOTAL AS FT_BRETPIS, D1_TOTAL AS FT_BRETCOF, D1_TOTAL AS FT_BRETCSL,
       D1_TOTAL * 0.65 / 100 AS FT_VRETPIS, D1_TOTAL * 3 / 100 AS FT_VRETCOF, 
       D1_TOTAL * 1 / 100 AS FT_VRETCSL, 0.65 AS FT_ARETPIS, 3 AS F_ARETCOF, 1 AS F_ARETCSL,
       '4313' AS FT_TNATREC, '999' AS FT_CNATREC
  FROM SD1010 WHERE D_E_L_E_T_ = ' ' AND D1_FORNECE = '001631'
   AND D1_DOC = '000000300'
   AND D1_TES = '001'
 ORDER BY D1_DOC, D1_ITEM;