-- 1) SB8 - Saldo de Lotes
DELETE FROM SB8010;
INSERT INTO SB8010(B8_FILIAL, B8_PRODUTO, B8_LOCAL, B8_QTDORI, B8_SALDO, B8_DATA, B8_DTVALID, B8_ORIGLAN,
                   B8_LOTECTL, D_E_L_E_T_, R_E_C_N_O_)
SELECT SB2.B2_FILIAL, SB2.B2_COD, SB2.B2_LOCAL, SB2.B2_QATU + COALESCE(KDX.QUANT * -1, 0) AS B8_QTDORI, 
       SB2.B2_QATU AS B8_SALDO, '20120430' AS B8_DATA, '20301231' AS B8_DTVALID, 'NF' AS B8_ORIGLAN, 
       'INICIAL' AS B8_LOTECTL, ' ' AS D_E_L_E_T_, ROW_NUMBER() OVER(ORDER BY SB2.R_E_C_N_O_) AS R_E_C_N_O_
  FROM SB2010 SB2
  LEFT JOIN (select B1_COD, SUM(QUANT) AS QUANT
               from KARDEX
              where DATA between '20120501' and '20120531' and B1_LOCAL = '01'
              group by B1_COD
             having SUM(QUANT) <> 0) KDX ON KDX.B1_COD = SB2.B2_COD
  LEFT JOIN SB9010 SB9 ON SB9.D_E_L_E_T_ = ' ' AND SB9.B9_FILIAL = '01' AND SB9.B9_LOCAL = '01' 
   AND SB9.B9_DATA = '20120430' AND SB9.B9_COD = SB2.B2_COD
 WHERE SB2.D_E_L_E_T_ = ' ' AND SB2.B2_FILIAL = '01' AND SB2.B2_LOCAL = '01'
   AND SB2.B2_QATU  + COALESCE(SB9.B9_QINI, 0) > 0;
 
-- 2) SBJ - Saldo Inicial por Lote
DELETE FROM SBJ010;
INSERT INTO SBJ010(BJ_FILIAL, BJ_COD, BJ_LOCAL, BJ_DATA, BJ_DTVALID, BJ_QINI, BJ_LOTECTL, 
                   D_E_L_E_T_, R_E_C_N_O_)
            SELECT SB8.B8_FILIAL, SB8.B8_PRODUTO, SB8.B8_LOCAL, '20120430', '20301231', 
                   SB8.B8_QTDORI AS BJ_QINI, 'INICIAL', ' ', 
                   ROW_NUMBER() OVER(ORDER BY R_E_C_N_O_) AS R_E_C_N_O_
              FROM SB8010 SB8
             WHERE SB8.D_E_L_E_T_ = ' ' AND SB8.B8_QTDORI > 0;

-- 3) SD5 - Apontamento do lote
DELETE FROM SD5010;
INSERT INTO SD5010(D5_FILIAL, D5_PRODUTO, D5_LOCAL, D5_DOC, D5_SERIE, D5_OP, D5_DATA, D5_ORIGLAN,
                   D5_NUMSEQ, D5_QUANT, D5_LOTECTL, D5_DTVALID, D_E_L_E_T_, R_E_C_N_O_)
            SELECT B8_FILIAL, B8_PRODUTO, B8_LOCAL, 'INICIAL' AS D5_DOC, '' AS D5_SERIE, '' AS D5_OP, 
                   '20120430' AS D5_DATA, '499' AS D5_ORIGLAN, 'INICIO' AS D5_NUMSEQ, B8_QTDORI AS D5_QUANT, 
                   'INICIAL' AS D5_LOTECTL, '20301231' AS D5_DTVALID, ' ' AS D_E_L_E_T_,
                   ROW_NUMBER() OVER(ORDER BY R_E_C_N_O_) AS R_E_C_N_O_
              FROM SB8010
             WHERE D_E_L_E_T_ = ' ' AND B8_QTDORI > 0;

-- Entradas por Lote
INSERT INTO SD5010(D5_FILIAL, D5_PRODUTO, D5_LOCAL, D5_DOC, D5_SERIE, D5_OP, D5_DATA, D5_ORIGLAN,
                   D5_NUMSEQ, D5_QUANT, D5_LOTECTL, D5_DTVALID, D_E_L_E_T_, R_E_C_N_O_)
            SELECT B8_FILIAL, B8_PRODUTO, B8_LOCAL, 'INICIAL' AS D5_DOC, '' AS D5_SERIE, '' AS D5_OP, 
                   '20120501' AS D5_DATA, '499' AS D5_ORIGLAN, 'INICIO' AS D5_NUMSEQ, B8_SALDO - B8_QTDORI AS D5_QUANT, 
                   'INICIAL' AS D5_LOTECTL, '20301231' AS D5_DTVALID, ' ' AS D_E_L_E_T_,
                   (SELECT MAX(R_E_C_N_O_) FROM SD5010) + ROW_NUMBER() OVER(ORDER BY R_E_C_N_O_) AS R_E_C_N_O_
              FROM SB8010
             WHERE D_E_L_E_T_ = ' ' AND B8_SALDO > B8_QTDORI;

-- Saidas por Lote
INSERT INTO SD5010(D5_FILIAL, D5_PRODUTO, D5_LOCAL, D5_DOC, D5_SERIE, D5_OP, D5_DATA, D5_ORIGLAN,
                   D5_NUMSEQ, D5_QUANT, D5_LOTECTL, D5_DTVALID, D_E_L_E_T_, R_E_C_N_O_)
            SELECT B8_FILIAL, B8_PRODUTO, B8_LOCAL, 'INICIAL' AS D5_DOC, '' AS D5_SERIE, '' AS D5_OP, 
                   '20120501' AS D5_DATA, '999' AS D5_ORIGLAN, 'INICIO' AS D5_NUMSEQ, 
                   B8_QTDORI - B8_SALDO AS D5_QUANT, 
                   'INICIAL' AS D5_LOTECTL, '20301231' AS D5_DTVALID, ' ' AS D_E_L_E_T_,
                   (SELECT MAX(R_E_C_N_O_) FROM SD5010) + ROW_NUMBER() OVER(ORDER BY R_E_C_N_O_) AS R_E_C_N_O_
              FROM SB8010
             WHERE D_E_L_E_T_ = ' ' AND B8_SALDO < B8_QTDORI;

-- Igual o saldo do lote
UPDATE SB8010 SET B8_QTDORI = B8_SALDO;
             
-- 4) Marcação do Cadastro de Produtos
update SB1010
   set B1_RASTRO = 'L'
 where D_E_L_E_T_ = ' ' and B1_TIPO in ('ME', 'PA', 'MP', 'MC');

-- Faz Copia das Tabelas
SELECT * INTO SB8010_INI FROM SB8010;
SELECT * INTO SBJ010_INI FROM SBJ010;
SELECT * INTO SD5010_INI FROM SD5010;
 
-- 6) Conferencia do Resultado
SELECT SLD_LOCAL.*, SLD_LOTE.*
  FROM 
(  
SELECT SUM(SB2.B2_QATU) AS SALDO_ATUAL, MIN(KDX.QUANT) AS SALDO_MOVIMENTO, 
       SUM(SB2.B2_QATU) - MIN(KDX.QUANT) AS CONFERE_FECHAMENTO,
       MIN(SB9.B9_QINI) AS SALDO_FECHAMENTO, SUM(SB2.B2_QEMP) AS EMPENHO
  FROM SB2010 SB2
  JOIN (select SUM(QUANT) AS QUANT
               from KARDEX
              where DATA between '20120501' and '20120531' and B1_LOCAL = '01'
             having SUM(QUANT) <> 0) KDX ON KDX.QUANT = KDX.QUANT
  JOIN (SELECT SUM(B9_QINI) AS B9_QINI
          FROM SB9010
         WHERE D_E_L_E_T_ = ' ' AND B9_FILIAL = '01' AND B9_LOCAL = '01' 
           AND B9_DATA = '20120430') SB9 ON SB9.B9_QINI = SB9.B9_QINI
 WHERE SB2.D_E_L_E_T_ = ' ' AND SB2.B2_FILIAL = '01' AND SB2.B2_LOCAL = '01') SLD_LOCAL
  JOIN (SELECT SUM(SB8.B8_QTDORI) AS B8_QTDORI, SUM(SB8.B8_SALDO) AS B8_SALDO, 
               SUM(SB8.B8_EMPENHO) AS B8_EMPENHO,
               MIN(SBJ.BJ_QINI) AS BJ_QINI, MIN(SD5.D5_SALDO) AS D5_SALDO
          FROM SB8010 SB8
          JOIN (SELECT SUM(BJ_QINI) AS BJ_QINI
                  FROM SBJ010
                 WHERE D_E_L_E_T_ = ' ' AND BJ_FILIAL = '01' AND BJ_LOCAL = '01' 
                   AND BJ_DATA = '20120430') SBJ ON SBJ.BJ_QINI = SBJ.BJ_QINI  
          JOIN (select SUM(D5_QUANT * CASE WHEN D5_ORIGLAN < '500' THEN 1 ELSE -1 END) AS D5_SALDO
                  from SD5010) SD5 ON SD5.D5_SALDO = SD5.D5_SALDO 
          where D_E_L_E_T_ = ' ') SLD_LOTE ON SLD_LOTE.B8_QTDORI = SLD_LOTE.B8_QTDORI;
          
-- Movimento com Lote
SELECT * FROM SD1010 WHERE D_E_L_E_T_ = ' ' AND D1_LOTECTL <> ''; 
SELECT * FROM SD2010 WHERE D_E_L_E_T_ = ' ' AND D2_LOTECTL <> ''; 
SELECT * FROM SD3010 WHERE D_E_L_E_T_ = ' ' AND D3_LOTECTL <> ''; 
SELECT * FROM SD4010 WHERE D_E_L_E_T_ = ' ' AND D4_LOTECTL <> '';          