-- Geração do lote
INSERT INTO SB8010(B8_FILIAL, B8_PRODUTO, B8_LOCAL, B8_QTDORI, B8_SALDO, B8_DATA, 
                   B8_DTVALID, B8_ORIGLAN, B8_DOC, B8_SERIE, B8_CLIFOR, B8_LOJA,
                   B8_LOTECTL, D_E_L_E_T_, R_E_C_N_O_)
SELECT D1_FILIAL AS B8_FILIAL, D1_COD AS B8_PRODUTO, D1_LOCAL AS B8_LOCAL, D1_QUANT AS B8_QTDORI, 
       D1_QUANT AS B8_SALDO, D1_DTDIGIT AS B8_DATA, D1_DTDIGIT AS B8_DTVALID, 'NF' AS B8_ORIGLAN, 
       D1_DOC AS B8_DOC, D1_SERIE AS B8_SERIE, D1_FORNECE AS B8_CLIFOR, D1_LOJA AS B8_LOJA,
       'AUTO' + dbo.strzero(3867 + ROW_NUMBER() OVER(ORDER BY SD1.R_E_C_N_O_), 6) AS B8_LOTECTL, 
       ' ' AS D_E_L_E_T_, 
       (SELECT MAX(R_E_C_N_O_) FROM SB8010) + ROW_NUMBER() OVER(ORDER BY SD1.R_E_C_N_O_) AS R_E_C_N_O_
  FROM SD1010 SD1
 WHERE SD1.D_E_L_E_T_ = ' ' AND D1_LOCAL = '02' AND D1_LOTECTL = '' 
   AND D1_QUANT > 0 AND D1_DTDIGIT >= '20130501';

-- Atualização do número no documento de entrada
UPDATE SD1010
   SET D1_LOTECTL = SB8010.B8_LOTECTL
  FROM SB8010
 WHERE SD1010.D_E_L_E_T_ = ' ' AND D1_LOCAL = '02'
   AND D1_QUANT > 0 AND D1_DTDIGIT >= '20130501'
   AND D1_DOC = B8_DOC AND D1_SERIE = B8_SERIE AND D1_FORNECE = B8_CLIFOR AND D1_LOJA = B8_LOJA
   AND B8_PRODUTO = D1_COD AND B8_LOCAL = D1_LOCAL
   AND SB8010.R_E_C_N_O_ >= 5544;  

-- Geração do Kardex por Lote   
INSERT INTO SD5010(D5_FILIAL, D5_PRODUTO, D5_LOCAL, D5_DOC, D5_SERIE, D5_CLIFOR, D5_LOJA,
                   D5_DATA, D5_ORIGLAN, D5_NUMSEQ, D5_QUANT, D5_LOTECTL, D5_DTVALID, 
                   D_E_L_E_T_, R_E_C_N_O_)
            SELECT D1_FILIAL AS D5_FILIAL, D1_COD AS D5_PRODUTO, D1_LOCAL AS D5_LOCAL, 
                   D1_DOC AS D5_DOC, D1_SERIE AS D5_SERIE, D1_FORNECE AS D5_CLIFOR,
                   D1_LOJA AS D5_LOJA, D1_DTDIGIT AS D5_DATA, D1_TES AS D5_ORIGLAN, 
                   D1_NUMSEQ AS D5_NUMSEQ, D1_QUANT AS D5_QUANT, 
                   D1_LOTECTL AS D5_LOTECTL, D1_DTDIGIT AS D5_DTVALID, ' ' AS D_E_L_E_T_,
                   (SELECT MAX(R_E_C_N_O_) FROM SD5010) + ROW_NUMBER() 
                   OVER(ORDER BY SD1.R_E_C_N_O_) AS R_E_C_N_O_
              FROM SD1010 SD1
              JOIN SB8010 SB8 ON SB8.D_E_L_E_T_ = ' ' AND SB8.R_E_C_N_O_ >= 5544
               AND B8_DOC = D1_DOC AND B8_SERIE = D1_SERIE AND B8_CLIFOR = D1_FORNECE AND B8_LOJA = D1_LOJA 
               AND B8_PRODUTO = D1_COD AND B8_LOCAL = D1_LOCAL AND B8_LOTECTL = D1_LOTECTL 
             WHERE SD1.D_E_L_E_T_ = ' ' AND D1_LOCAL = '02'
               AND D1_QUANT > 0 AND D1_DTDIGIT >= '20130501';