UPDATE SD1010 SET D1_LOTECTL = '' WHERE D_E_L_E_T_ = ' ' AND D1_LOTECTL <> ''; 
UPDATE SD2010 SET D2_LOTECTL = '' WHERE D_E_L_E_T_ = ' ' AND D2_LOTECTL <> ''; 
UPDATE SD3010 SET D3_LOTECTL = '' WHERE D_E_L_E_T_ = ' ' AND D3_LOTECTL <> ''; 
UPDATE SD4010 SET D4_LOTECTL = '' WHERE D_E_L_E_T_ = ' ' AND D4_LOTECTL <> ''; 

DELETE FROM SB8010;
DELETE FROM SBJ010;
DELETE FROM SD5010;

update SB1010
   set B1_RASTRO = 'N'
 where D_E_L_E_T_ = ' ';