SELECT QP6.QP6_PRODUT PRODUT,QP6.QP6_REVI REVI,QP7.QP7_CODREC CODREC,  QP7.QP7_OPERAC OPERAC, QP7.QP7_LABOR LABOR, QP7.QP7_SEQLAB SEQLAB,  QP6.QP6_FATCO1 FATCO1, QP6.QP6_TIPCO1 TIPCO1, QP6.QP6_FATCO2 FATCO2,  QP6.QP6_TIPCO2 TIPCO2, QP6.QP6_DESCPO DESCPO, QP6.QP6_DTCAD DTCAD,  QP6.QP6_DTDES DTDES, QP6.QP6_RVDES RVDES, QP6.QP6_DTINI DTINI,  QP6.QP6_DOCOBR DOCOBR, QP6.QP6_UNMED1 UNMED1, QP6.QP6_UNMED2 UNMED2,
       QQK.QQK_CHAVE CHAVE, QQK.QQK_DESCRI DESCRI, QQK.QQK_OPERGR OPERGRP,  QP7.QP7_ENSAIO ENSAIO, QP7.QP7_ENSOBR ENSOBR, QP7.QP7_UNIMED UNIMED,  QP7.QP7_NOMINA NOMINA, QP7.QP7_LIE LIE, QP7.QP7_NIVEL NIVEL, QP7.QP7_METODO METODO,  QP6.QP6_HISTOR HISTOR, QP7.QP7_LSE LSE, QP7.QP7_PLAMO PLAMO, QP7.QP7_DESPLA DESPLA,  QP7.QP7_MINMAX MINMAX, QP7.QP7_X_FASE FASE
  FROM QPK010 QPK
  JOIN QP6010 QP6 ON QP6.D_E_L_E_T_ = ' ' AND QP6.QP6_FILIAL = '  ' AND QP6.QP6_PRODUT = '20277A-050     ' AND QP6.QP6_REVI = '02'
  LEFT JOIN QQK010 QQK ON QQK.D_E_L_E_T_ = ' ' AND QQK.QQK_FILIAL  = '00' AND QQK.QQK_PRODUT ='20277A-050     ' AND QQK.QQK_CODIGO ='01'
   AND QQK.QQK_OPERAC Between '  ' and 'ZZ' AND QQK.QQK_REVIPR = QPK.QPK_REVI
  LEFT JOIN QP7010 QP7 ON QP7.QP7_FILIAL = '  ' AND QP7.D_E_L_E_T_ = ' '
   AND QP7.QP7_REVI = QPK.QPK_REVI  AND QP7.QP7_CODREC = QQK.QQK_CODIGO  AND QP7.QP7_OPERAC = QQK.QQK_OPERAC
   AND QP7.QP7_LABOR Between '      ' and 'ZZZZZZ'
   AND QP7.QP7_PRODUT = QP6.QP6_PRODUT
 WHERE QPK.D_E_L_E_T_ = ' ' AND QPK.QPK_OP>='00888101012  ' AND QPK.QPK_LOTE>='                ' AND QPK.QPK_NUMSER>='                    '
   AND QPK.QPK_OP<='00888101012  ' AND QPK.QPK_LOTE<='                '
   AND QPK.QPK_NUMSER<='                    '
 ORDER BY QP6_PRODUT,QP6_REVI,QP7_CODREC,QP7_OPERAC,QP7_LABOR,QP7_SEQLAB

SELECT * FROM SC2010 SC2 
  LEFT JOIN (SELECT QP6_PRODUT, MAX(QP6_REVI) AS QP6_REVI
  FROM QP6010
 WHERE D_E_L_E_T_ = ' '
 GROUP BY QP6_PRODUT) QP6 ON QP6.QP6_PRODUT = SC2.C2_PRODUTO
  LEFT JOIN QQK010 QQK ON QQK.D_E_L_E_T_ = ' ' AND QQK.QQK_PRODUT = SC2.C2_PRODUTO AND QQK.QQK_REVIPR = QP6.QP6_REVI AND QQK.QQK_CODIGO = SC2.C2_ROTEIRO
WHERE SC2.D_E_L_E_T_ = ' ' AND QQK.D_E_L_E_T_ IS NULL AND SC2.C2_NUM = '008881'

-- Verificação
SELECT QQK.QQK_CODIGO, QPK.*
  FROM QPK010 QPK
  JOIN SC2010 SC2 ON SC2.D_E_L_E_T_ = ' ' AND SC2.C2_FILIAL = QPK.QPK_FILIAL AND SC2.C2_NUM = SUBSTRING(QPK.QPK_OP, 1, 6)
   AND SC2.C2_ITEM = SUBSTRING(QPK.QPK_OP, 7, 2) AND SC2.C2_SEQUEN = SUBSTRING(QPK.QPK_OP, 9, 3)
  LEFT JOIN QP6010 QP6 ON QP6.D_E_L_E_T_ = ' ' AND QP6.QP6_FILIAL = '  ' AND QP6.QP6_PRODUT = QPK.QPK_PRODUT AND QP6.QP6_REVI = QPK.QPK_REVI
  LEFT JOIN QQK010 QQK ON QQK.D_E_L_E_T_ = ' ' AND QQK.QQK_FILIAL = QPK.QPK_FILIAL AND QQK.QQK_PRODUT = QPK.QPK_PRODUT AND QQK.QQK_CODIGO = SC2.C2_ROTEIRO
   AND QQK.QQK_OPERAC Between '  ' and 'ZZ' AND QQK.QQK_REVIPR = QPK.QPK_REVI
  LEFT JOIN QP7010 QP7 ON QP7.QP7_FILIAL = '  ' AND QP7.D_E_L_E_T_ = ' '
   AND QP7.QP7_REVI = QPK.QPK_REVI  AND QP7.QP7_CODREC = QQK.QQK_CODIGO  AND QP7.QP7_OPERAC = QQK.QQK_OPERAC
   AND QP7.QP7_LABOR Between '      ' and 'ZZZZZZ'
   AND QP7.QP7_PRODUT = QP6.QP6_PRODUT
 WHERE QPK.D_E_L_E_T_ = ' ' AND QPK.QPK_OP in ('00888101012', '00892201005', '00893201002')
 ORDER BY QP6_PRODUT,QP6_REVI,QP7_CODREC,QP7_OPERAC,QP7_LABOR,QP7_SEQLAB;

-- OP sem especificação de produtos ou roteiro
SELECT SC2.C2_NUM, SC2.C2_ITEM, SC2.C2_SEQUEN, SC2.C2_ROTEIRO, QPK.QPK_TAMLOT,
       (SELECT MAX(QP6_REVI) FROM QP6010 WHERE D_E_L_E_T_ = ' ' AND QP6_PRODUT = QPK.QPK_PRODUT) AS QP6_REVI, SC2.C2_PRODUTO, SC2.C2_LOCAL,
       SC2.C2_QUANT, SC2.C2_DATPRF, QPK.QPK_REVI, SC2.C2_REVI, SC2.C2_REVISAO, SC2.C2_LOCAL, SC2.C2_QUANT
  FROM QPK010 QPK
  JOIN SC2010 SC2 ON SC2.D_E_L_E_T_ = ' ' AND SC2.C2_FILIAL = QPK.QPK_FILIAL
   AND SC2.C2_NUM = SUBSTRING(QPK.QPK_OP, 1, 6)
   AND SC2.C2_ITEM = SUBSTRING(QPK.QPK_OP, 7, 2) AND SC2.C2_SEQUEN = SUBSTRING(QPK.QPK_OP, 9, 3)
 WHERE QPK.D_E_L_E_T_ = ' ' AND QPK.QPK_REVI = ' ' OR SC2.C2_ROTEIRO = ' '
ORDER BY QPK.QPK_OP