-- Quebra por CST/Tipo de Crédito
SELECT CASE WHEN LEFT(FT_CFOP, 1) = '3' THEN '108' ELSE '101' END AS TIPO,
       FT_CSTPIS, FT_CSTCOF, FT_CODBCC, FT_ALIQPIS, FT_ALIQCOF - FT_MALQCOF AS FT_ALIQCOF,
       SUM(FT_BASEPIS) AS FT_BASEPIS, SUM(FT_VALPIS) AS FT_VALPIS,
       SUM(FT_BASECOF) AS FT_BASECOF, SUM(FT_VALCOF - FT_MVALCOF) AS FT_VALCOF
  FROM SFT010
 WHERE D_E_L_E_T_ = ' ' and FT_ENTRADA between '20130701' and '20130731'
 GROUP BY CASE WHEN LEFT(FT_CFOP, 1) = '3' THEN '108' ELSE '101' END, FT_CSTPIS, FT_CSTCOF,
          FT_CODBCC, FT_ALIQPIS, FT_ALIQCOF - FT_MALQCOF
 ORDER BY CASE WHEN LEFT(FT_CFOP, 1) = '3' THEN '108' ELSE '101' END, FT_CSTPIS, FT_CSTCOF,
          FT_CODBCC, FT_ALIQPIS, FT_ALIQCOF - FT_MALQCOF;

-- Detalhe das Notas
SELECT CASE WHEN LEFT(FT_CFOP, 1) = '3' THEN '108' ELSE '101' END AS TIPO,
       FT_CSTPIS, FT_CSTCOF, FT_CODBCC, FT_ALIQPIS, FT_ALIQCOF - FT_MALQCOF AS FT_ALIQCOF,
       FT_NFISCAL, FT_ITEM, FT_PRODUTO, FT_CFOP,
       FT_BASEPIS, FT_VALPIS, FT_BASECOF, FT_VALCOF - FT_MVALCOF AS FT_VALCOF
  FROM SFT010
 WHERE D_E_L_E_T_ = ' ' and FT_ENTRADA between '20130701' and '20130731'
   AND FT_BASEPIS + FT_BASECOF + FT_VALCOF + FT_VALPIS > 0
 ORDER BY CASE WHEN LEFT(FT_CFOP, 1) = '3' THEN '108' ELSE '101' END, FT_CSTPIS, FT_CSTCOF,
          FT_CODBCC, FT_ALIQPIS, FT_ALIQCOF - FT_MALQCOF;

-- Quebra por Tipo de Crédito
SELECT CASE WHEN LEFT(FT_CFOP, 1) = '3' THEN '108' ELSE '101' END AS TIPO,
       FT_CODBCC, FT_ALIQPIS, FT_ALIQCOF,
       SUM(FT_BASEPIS) AS FT_BASEPIS, SUM(FT_VALPIS) AS FT_VALPIS,
       SUM(FT_BASECOF) AS FT_BASECOF, SUM(FT_VALCOF) AS FT_VALCOF
  FROM SFT010
 WHERE D_E_L_E_T_ = ' ' and FT_ENTRADA between '20120101' and '20120131' and FT_ALIQPIS + FT_ALIQCOF > 0
   AND LEFT(FT_CFOP, 1) < '5'
 GROUP BY CASE WHEN LEFT(FT_CFOP, 1) = '3' THEN '108' ELSE '101' END,
          FT_CODBCC, FT_ALIQPIS, FT_ALIQCOF;

-- Quebra por CST
SELECT FT_CSTPIS, FT_CSTCOF, SUM(FT_VALCONT) AS FT_VALCONT,
       SUM(FT_BASEPIS) AS FT_BASEPIS, SUM(FT_VALPIS) AS FT_VALPIS,
       SUM(FT_BASECOF) AS FT_BASECOF, SUM(FT_VALCOF) AS FT_VALCOF
  FROM SFT010
 WHERE D_E_L_E_T_ = ' ' and FT_ENTRADA between '20120101' and '20120131'
 GROUP BY FT_CSTPIS, FT_CSTCOF;

-- Débito - Crédito
SELECT CASE WHEN LEFT(FT_CFOP, 1) < '5' THEN 'E' ELSE 'S' END AS TIPO,
       SUM(FT_VALCONT) AS FT_VALCONT,
       SUM(FT_BASEPIS) AS FT_BASEPIS, SUM(FT_VALPIS) AS FT_VALPIS,
       SUM(FT_BASECOF) AS FT_BASECOF, SUM(FT_VALCOF) AS FT_VALCOF
  FROM SFT010
 WHERE D_E_L_E_T_ = ' ' and FT_ENTRADA between '20120101' and '20120131'
 GROUP BY CASE WHEN LEFT(FT_CFOP, 1) < '5' THEN 'E' ELSE 'S' END;