-- Atualizar o tipo de frete a partir da tes nos itens da nota
SELECT SFT.R_E_C_N_O_, SFT.FT_INDNTFR, SF4.F4_INDNTFR, SFT.FT_PRODUTO, * 
  FROM SFT010 SFT 
  JOIN SD1010 SD1 ON SD1.D1_FILIAL = SFT.FT_FILIAL AND SD1.D1_DOC = SFT.FT_NFISCAL 
   AND SD1.D1_SERIE = SFT.FT_SERIE AND SD1.D1_ITEM = SFT.FT_ITEM AND SD1.D_E_L_E_T_ = ' '
  JOIN SF4010 SF4 ON SF4.F4_FILIAL = SFT.FT_FILIAL AND SF4.D_E_L_E_T_ = ' ' AND SF4.F4_CODIGO = SD1.D1_TES 
   AND SF4.F4_INDNTFR <> ''
 WHERE SFT.FT_FILIAL = '01' AND SFT.D_E_L_E_T_ = ' ' AND SFT.FT_INDNTFR = '';

-- Itens da Nota
select FT_CFOP, * from SFT010 where FT_ENTRADA BETWEEN '20120101' AND '20120131';

update SFT010 
   set FT_CODBCC = '01'
 where FT_ENTRADA BETWEEN '20120101' AND '20120131';
 
-- Código Base de Calculo Crédito PIS/COFINS
SELECT * FROM SF4010 WHERE F4_CODBCC <> ''; 

-- Relação das Tes Utilizadas - Entradas
SELECT SF4.F4_CODIGO
  FROM SFT010 SFT 
  JOIN SD1010 SD1 ON SD1.D1_FILIAL = SFT.FT_FILIAL AND SD1.D1_DOC = SFT.FT_NFISCAL 
   AND SD1.D1_SERIE = SFT.FT_SERIE AND SD1.D1_ITEM = SFT.FT_ITEM AND SD1.D_E_L_E_T_ = ' '
  JOIN SF4010 SF4 ON SF4.F4_FILIAL = SFT.FT_FILIAL AND SF4.D_E_L_E_T_ = ' ' AND SF4.F4_CODIGO = SD1.D1_TES 
 WHERE SFT.FT_FILIAL = '01' AND SFT.D_E_L_E_T_ = ' '
   AND SFT.FT_ENTRADA BETWEEN '20120101' AND '20120131'
 GROUP BY SF4.F4_CODIGO
 UNION ALL
-- Relação das Tes Utilizadas - Saídas
SELECT SF4.F4_CODIGO
  FROM SFT010 SFT 
  JOIN SD2010 SD2 ON SD2.D2_FILIAL = SFT.FT_FILIAL AND SD2.D2_DOC = SFT.FT_NFISCAL 
   AND SD2.D2_SERIE = SFT.FT_SERIE AND SD2.D2_ITEM = SFT.FT_ITEM AND SD2.D_E_L_E_T_ = ' '
  JOIN SF4010 SF4 ON SF4.F4_FILIAL = SFT.FT_FILIAL AND SF4.D_E_L_E_T_ = ' ' AND SF4.F4_CODIGO = SD2.D2_TES 
 WHERE SFT.FT_FILIAL = '01' AND SFT.D_E_L_E_T_ = ' '
   AND SFT.FT_ENTRADA BETWEEN '20120101' AND '20120131'
 GROUP BY SF4.F4_CODIGO;