select SB1.B1_TIPO, SB1.B1_CONTA, SD1.D1_TP, * 
  FROM SD1010 SD1 
  JOIN SB1010 SB1 ON SB1.R_E_C_D_E_L_ = ' ' AND SB1.B1_COD = SD1.D1_COD
 WHERE SD1.D_E_L_E_T_ = ' ' AND SD1.D1_DOC = '000008092'
 
 SELECT B1_CONTA, B1_COD, B1_DESC, CASE WHEN B1_MSBLQL = '1' THEN 'Bloqueado' Else 'Ativo' End As Ativo 
   FROM SB1010 
  WHERE D_E_L_E_T_ = ' ' AND B1_TIPO = 'ME' 
  ORDER BY B1_CONTA, B1_COD
 
 SELECT B1_CONTA, B1_COD, B1_DESC, CASE WHEN B1_MSBLQL = '1' THEN 'Bloqueado' Else 'Ativo' End As Ativo 
   FROM SB1010 
  WHERE D_E_L_E_T_ = ' ' AND B1_TIPO = 'MP'
  ORDER BY B1_CONTA, B1_COD
 