SELECT AF8.AF8_PROJET, AF8.AF8_DATA, AF8.AF8_CLIENT, AF8.AF8_LOJA, AF8.AF8_XNOMCL, AFC.AFC_XPROD 
  from AF8010 AF8 
  JOIN AFC010 AFC ON AFC.D_E_L_E_T_ = ' ' AND AFC.AFC_PROJET = AF8.AF8_PROJET AND AFC.AFC_XPRODU = 'S'
 WHERE AF8.D_E_L_E_T_ = ' ' AND AF8.AF8_PROJET LIKE '%12%A' 
 ORDER BY AF8.AF8_DATA, AF8.AF8_PROJET, AFC.AFC_XPROD
 
 SELECT * FROM YA7010 WHERE YA7_TABELA = 'SC5'
 
 SELECT * FROM AF8010 WHERE D_E_L_E_T_ = ' ' AND AF8_PROJET LIKE '%PMF%';