-- Cartões de volume sem pendencia de separação com status superior a 5-Faturado
SELECT CB2.CB2_FILIAL, CB7.CB7_DTEMIS, CB7.CB7_STATUS, COALESCE(CB9.CB9_QTESEP, 0) AS SALDOSEP, CB2.CB2_ORDSEP
  FROM CB2010 CB2
  LEFT JOIN (SELECT CB9_FILIAL, CB9_DISPID, SUM(CB9_QTESEP - CB9_QTEEMB) AS CB9_QTESEP
               FROM CB9010
              WHERE D_E_L_E_T_ = ' '
              GROUP BY CB9_FILIAL, CB9_DISPID) CB9 ON CB9.CB9_FILIAL = CB2.CB2_FILIAL AND CB9.CB9_DISPID = CB2.CB2_DISPID
  LEFT JOIN CB7010 CB7 ON CB7.D_E_L_E_T_ = ' ' AND CB7.CB7_ORDSEP = CB2.CB2_ORDSEP
 WHERE CB2.D_E_L_E_T_ = ' ' AND CB2.CB2_ORDSEP <> '' AND CB7.CB7_STATUS > '4' AND COALESCE(CB9.CB9_QTESEP, 0) = 0
 ORDER BY CB7.CB7_DTEMIS;

UPDATE CB2010
   SET CB2_ORDSEP = ''
 WHERE R_E_C_N_O_ IN
(
SELECT CB2.R_E_C_N_O_
  FROM CB2010 CB2
  LEFT JOIN (SELECT CB9_FILIAL, CB9_DISPID, SUM(CB9_QTESEP - CB9_QTEEMB) AS CB9_QTESEP
               FROM CB9010
              WHERE D_E_L_E_T_ = ' '
              GROUP BY CB9_FILIAL, CB9_DISPID) CB9 ON CB9.CB9_FILIAL = CB2.CB2_FILIAL AND CB9.CB9_DISPID = CB2.CB2_DISPID
  LEFT JOIN CB7010 CB7 ON CB7.D_E_L_E_T_ = ' ' AND CB7.CB7_ORDSEP = CB2.CB2_ORDSEP
 WHERE CB2.D_E_L_E_T_ = ' ' AND CB2.CB2_ORDSEP <> '' AND CB7.CB7_STATUS > '4' AND COALESCE(CB9.CB9_QTESEP, 0) = 0
);

-- Seleciona Cartões sem saldo de separação
SELECT CB9.SALDO, CB2.* FROM CB2010 CB2
  LEFT JOIN (SELECT CB9_FILIAL, CB9_ORDSEP, SUM(CB9_QTESEP - CB9_QTEEMB) AS SALDO
              FROM CB9010 WHERE D_E_L_E_T_ = ' ' 
             GROUP BY CB9_FILIAL, CB9_ORDSEP) CB9 ON CB9.CB9_FILIAL = CB2.CB2_FILIAL AND CB9.CB9_ORDSEP = CB2.CB2_ORDSEP 
 WHERE CB2.D_E_L_E_T_ = ' ' AND CB2.CB2_ORDSEP <> '' AND CB9.SALDO = 0
 ORDER BY CB2.CB2_FILIAL, CB2.CB2_DISPID

UPDATE CB2010
   SET CB2_ORDSEP = ''
 WHERE D_E_L_E_T_ = ' ' AND R_E_C_N_O_ IN
(
SELECT CB2.R_E_C_N_O_ FROM CB2010 CB2
  LEFT JOIN (SELECT CB9_FILIAL, CB9_ORDSEP, SUM(CB9_QTESEP - CB9_QTEEMB) AS SALDO
              FROM CB9010 WHERE D_E_L_E_T_ = ' ' 
             GROUP BY CB9_FILIAL, CB9_ORDSEP) CB9 ON CB9.CB9_FILIAL = CB2.CB2_FILIAL AND CB9.CB9_ORDSEP = CB2.CB2_ORDSEP 
 WHERE CB2.D_E_L_E_T_ = ' ' AND CB2.CB2_ORDSEP <> '' AND CB9.SALDO = 0
)