-- SELECT VALIDAÇÃO
SELECT SC5.C5_NUM, SC5.C5_CLIENTE, SC5.C5_LOJACLI, SA1.A1_NOME, SC5.C5_EMISSAO, SC5.C6_TOTAL,
       CASE WHEN SC5.C6_SALDO = 0 THEN 'Atendido Total' ELSE
	    CASE WHEN CB8.CB8_ORDSEP IS NULL THEN 'Aguardando OS' ELSE
	    CASE WHEN SC5.C6_SALDO <> SC5.C6_QTDVEN THEN 'Atendido Parcialmente' ELSE 'Na Expedição' END END END AS C5_STATUS,
       CB8.CB8_ORDSEP, CB8.CB7_DTEMIS, CB8.CB7_HREMIS, CB8.CB7_CODOPE, CB8.CB1_NOME,
       CAST(CASE WHEN CB8.CB7_STATUS = '0' Then '0-OS Gerada      ' ELSE
            CASE WHEN CB8.CB7_STATUS = '1' Then '1-Separando      ' ELSE
            CASE WHEN CB8.CB7_STATUS = '2' Then '2-Separação Final' ELSE
            CASE WHEN CB8.CB7_STATUS = '3' Then '3-Embalando      ' ELSE
            CASE WHEN CB8.CB7_STATUS = '4' Then '4-Volume Montado ' ELSE
            CASE WHEN CB8.CB7_STATUS = '5' Then '5-Nota Gerada    ' ELSE
            CASE WHEN CB8.CB7_STATUS = '6' Then '6-Nota Impressa  ' ELSE
            CASE WHEN CB8.CB7_STATUS = '7' Then '7-Volume Impresso' ELSE
            CASE WHEN CB8.CB7_STATUS = '8' Then '8-Embarcado      ' ELSE
            CASE WHEN CB8.CB7_STATUS = '9' Then '9-Finalizado     ' ELSE '' END END END END END END END END END END AS VARCHAR(20)) AS CB7_STATUS,
       CB9.CB9_DISPID, CB9.CB9_VOLUME, CB9.CBG_DATAI, CB9.CBG_HORAI, CB9.CB9_QTESEP, CB9.CB9_QTEEMB,
	    CB9.CBG_DATAF, CB9.CBG_HORAF,
	    CASE WHEN CB9.CB6_STATUS = '1' THEN 'Iniciado' ELSE
	    CASE WHEN CB9.CB6_STATUS = '2' THEN 'Pesado' ELSE
	    CASE WHEN CB9.CB6_STATUS = '3' THEN 'Encerrado' ELSE '' END END END AS CB6_STATUS,
	    CB9.CB6_XIMP, CB9.CBG_DATANF, CB9.CBG_HORANF,
	    CB9.F2_DAUTNFE, CB9.F2_HAUTNFE, CB9.CB9_NUMSER, CB9.CB9_DOC, CB9.F2_VALMERC
  FROM (SELECT SC5.C5_FILIAL, SC5.C5_NUM, MIN(SC5.C5_CLIENTE) AS C5_CLIENTE, MIN(SC5.C5_LOJACLI) AS C5_LOJACLI,
               MIN(SC5.C5_EMISSAO) AS C5_EMISSAO, SUM(ROUND(SC6.C6_VALOR, 2)) AS C6_TOTAL, SUM(SC6.C6_QTDVEN) AS C6_QTDVEN,
			      SUM(CASE WHEN SC6.C6_BLQ <> 'R' THEN SC6.C6_QTDVEN - SC6.C6_QTDENT ELSE 0 END) AS C6_SALDO
          FROM SC5990 SC5
		    JOIN SC6990 SC6 ON SC6.D_E_L_E_T_ = ' ' AND SC6.C6_FILIAL = SC5.C5_FILIAL AND SC6.C6_NUM = SC5.C5_NUM
		   WHERE SC5.D_E_L_E_T_ = ' ' AND SC5.C5_FILIAL = '01' AND SC5.C5_EMISSAO BETWEEN '19800101' AND '20141231'
		   GROUP BY SC5.C5_FILIAL, SC5.C5_NUM) SC5
  LEFT JOIN SA1990 SA1 ON SA1.D_E_L_E_T_ = ' ' AND SA1.A1_FILIAL = '  ' AND SA1.A1_COD = SC5.C5_CLIENTE AND SA1.A1_LOJA = SC5.C5_LOJACLI
  LEFT JOIN (SELECT CB8.CB8_FILIAL, CB8.CB8_ORDSEP, MAX(CB8_PEDIDO) CB8_PEDIDO, MIN(CB7.CB7_STATUS) AS CB7_STATUS,
                    MIN(CB7.CB7_DTEMIS) AS CB7_DTEMIS, MIN(CB7.CB7_HREMIS) AS CB7_HREMIS, MIN(CB7.CB7_CODOPE) AS CB7_CODOPE,
					     MIN(CB1.CB1_NOME) AS CB1_NOME
               FROM CB8990 CB8
		         JOIN CB7990 CB7 ON CB8.D_E_L_E_T_ = ' ' AND CB7.CB7_FILIAL = CB8.CB8_FILIAL AND CB7.CB7_ORDSEP = CB8.CB8_ORDSEP
               LEFT JOIN CB1990 CB1 ON CB1.D_E_L_E_T_ = ' ' AND CB1.CB1_FILIAL = '01' AND CB1.CB1_CODOPE = CB7.CB7_CODOPE
			     WHERE CB8.D_E_L_E_T_ = ' ' AND CB8.CB8_FILIAL = '01'
	          GROUP BY CB8.CB8_FILIAL, CB8.CB8_ORDSEP) CB8 ON CB8.CB8_FILIAL = SC5.C5_FILIAL AND CB8.CB8_PEDIDO = SC5.C5_NUM
  LEFT JOIN (SELECT CB9.CB9_FILIAL, CB9.CB9_ORDSEP, CB9.CB9_DISPID, CB9.CB9_VOLUME,
                    SUM(CB9.CB9_QTESEP) AS CB9_QTESEP, SUM(CB9.CB9_QTEEMB) AS CB9_QTEEMB,
					     MAX(CBG.CBG_DATAI) AS CBG_DATAI, MAX(CBG.CBG_HORAI) AS CBG_HORAI,
					     MAX(CBG.CBG_DATAF) AS CBG_DATAF, MAX(CBG.CBG_HORAF) AS CBG_HORAF,
					     MIN(CB6.CB6_STATUS) AS CB6_STATUS, MIN(CB6.CB6_XIMP) AS CB6_XIMP,
					     CB9.CB9_NUMSER, CB9.CB9_DOC,
					     MAX(CBG.CBG_DATANF) AS CBG_DATANF, MAX(CBG.CBG_HORANF) AS CBG_HORANF,
					     MIN(SF2.F2_HAUTNFE) AS F2_HAUTNFE, MIN(SF2.F2_DAUTNFE) AS F2_DAUTNFE,
					     MIN(SF2.F2_VALMERC) AS F2_VALMERC
               FROM CB9990 CB9
			 LEFT JOIN CB6990 CB6 ON CB6.D_E_L_E_T_ = ' ' AND CB6.CB6_FILIAL = CB9.CB9_FILIAL AND CB6.CB6_VOLUME = CB9.CB9_VOLUME
			 LEFT JOIN (SELECT CBG_FILIAL, CBG_ORDSEP, CAST(CBG_VOLUME AS INTEGER) AS CBG_VOLUME,
			                   MAX(CASE WHEN CBG_EVENTO = '63' THEN CBG_DATA ELSE '' END) AS CBG_DATAI,
								    MAX(CASE WHEN CBG_EVENTO = '63' THEN CBG_HORA ELSE '' END) AS CBG_HORAI,
			                   MAX(CASE WHEN CBG_EVENTO = '64' THEN CBG_DATA ELSE '' END) AS CBG_DATAF,
								    MAX(CASE WHEN CBG_EVENTO = '64' THEN CBG_HORA ELSE '' END) AS CBG_HORAF,
			                   MAX(CASE WHEN CBG_EVENTO = '54' THEN CBG_DATA ELSE '' END) AS CBG_DATANF,
								    MAX(CASE WHEN CBG_EVENTO = '54' THEN CBG_HORA ELSE '' END) AS CBG_HORANF
			              FROM CBG990
						    WHERE D_E_L_E_T_ = ' ' AND CBG_EVENTO IN ('63', '64', '54')
						    GROUP BY CBG_FILIAL, CBG_ORDSEP, CAST(CBG_VOLUME AS INTEGER)) CBG ON CBG.CBG_FILIAL = CB9.CB9_FILIAL
                AND CBG.CBG_ORDSEP = CB9.CB9_ORDSEP AND CBG.CBG_VOLUME = CB6.CB6_XVOL
			 LEFT JOIN SF2990 SF2 ON SF2.D_E_L_E_T_ = ' ' AND SF2.F2_FILIAL = CB9.CB9_FILIAL AND SF2.F2_SERIE = CB9.CB9_NUMSER
			       AND SF2.F2_DOC = CB9.CB9_DOC
              WHERE CB9.D_E_L_E_T_ = ' ' AND CB9.CB9_FILIAL = '01' AND CB9.CB9_DISPID <> '' AND CB9.CB9_QTESEP > 0
			  GROUP BY CB9.CB9_FILIAL, CB9.CB9_ORDSEP, CB9.CB9_DISPID, CB9.CB9_VOLUME,
			           CB9.CB9_NUMSER, CB9.CB9_DOC) CB9 ON CB9.CB9_FILIAL = SC5.C5_FILIAL AND CB9.CB9_ORDSEP = CB8.CB8_ORDSEP
 ORDER BY SC5.C5_NUM, CB8.CB8_ORDSEP, CB9.CB9_DISPID, CB9.CB9_VOLUME, CB9_NUMSER, CB9.CB9_DOC;

-- SELECT DICIONARIO
  FROM (SELECT SC5.C5_FILIAL, SC5.C5_NUM, MIN(SC5.C5_CLIENTE) AS C5_CLIENTE, MIN(SC5.C5_LOJACLI) AS C5_LOJACLI,
               MIN(SC5.C5_EMISSAO) AS C5_EMISSAO, SUM(ROUND(SC6.C6_VALOR, 2)) AS C6_TOTAL, SUM(SC6.C6_QTDVEN) AS C6_QTDVEN,
			   SUM(CASE WHEN SC6.C6_BLQ <> 'R' THEN SC6.C6_QTDVEN - SC6.C6_QTDENT ELSE 0 END) AS C6_SALDO
          FROM <ADVPL>RetSqlName("SC5")</ADVPL> SC5
		  JOIN <ADVPL>RetSqlName("SC6")</ADVPL> SC6 ON SC6.D_E_L_E_T_ = ' ' AND SC6.C6_FILIAL = SC5.C5_FILIAL AND SC6.C6_NUM = SC5.C5_NUM
		 WHERE SC5.D_E_L_E_T_ = ' ' AND SC5.C5_FILIAL = '<ADVPL>xFilial("SC5")</ADVPL>' 
		   AND SC5.C5_EMISSAO BETWEEN #I_C5_EMISSAO# AND #F_C5_EMISSAO#
		 GROUP BY SC5.C5_FILIAL, SC5.C5_NUM) SC5 
  LEFT JOIN <ADVPL>RetSqlName("SA1")</ADVPL> SA1 ON SA1.D_E_L_E_T_ = ' ' AND SA1.A1_FILIAL = '<ADVPL>xFilial("SA1")</ADVPL>' AND SA1.A1_COD = SC5.C5_CLIENTE AND SA1.A1_LOJA = SC5.C5_LOJACLI 
  LEFT JOIN (SELECT CB8.CB8_FILIAL, CB8.CB8_ORDSEP, MAX(CB8_PEDIDO) CB8_PEDIDO, MIN(CB7.CB7_STATUS) AS CB7_STATUS, 
                    MIN(CB7.CB7_DTEMIS) AS CB7_DTEMIS, MIN(CB7.CB7_HREMIS) AS CB7_HREMIS, MIN(CB7.CB7_CODOPE) AS CB7_CODOPE,
					MIN(CB1.CB1_NOME) AS CB1_NOME
               FROM <ADVPL>RetSqlName("CB8")</ADVPL> CB8
		       JOIN <ADVPL>RetSqlName("CB7")</ADVPL> CB7 ON CB8.D_E_L_E_T_ = ' ' AND CB7.CB7_FILIAL = CB8.CB8_FILIAL AND CB7.CB7_ORDSEP = CB8.CB8_ORDSEP
               LEFT JOIN <ADVPL>RetSqlName("CB1")</ADVPL> CB1 ON CB1.D_E_L_E_T_ = ' ' AND CB1.CB1_FILIAL = '<ADVPL>xFilial("CB1")</ADVPL>' AND CB1.CB1_CODOPE = CB7.CB7_CODOPE
			  WHERE CB8.D_E_L_E_T_ = ' ' AND CB8.CB8_FILIAL = '<ADVPL>xFilial("CB8")</ADVPL>' 
	          GROUP BY CB8.CB8_FILIAL, CB8.CB8_ORDSEP) CB8 ON CB8.CB8_FILIAL = SC5.C5_FILIAL AND CB8.CB8_PEDIDO = SC5.C5_NUM
  LEFT JOIN (SELECT CB9.CB9_FILIAL, CB9.CB9_ORDSEP, CB9.CB9_DISPID, CB9.CB9_VOLUME, 
                    SUM(CB9.CB9_QTESEP) AS CB9_QTESEP, SUM(CB9.CB9_QTEEMB) AS CB9_QTEEMB,
					MAX(CBG.CBG_DATAI) AS CBG_DATAI, MAX(CBG.CBG_HORAI) AS CBG_HORAI, 
					MAX(CBG.CBG_DATAF) AS CBG_DATAF, MAX(CBG.CBG_HORAF) AS CBG_HORAF, 
					MIN(CB6.CB6_STATUS) AS CB6_STATUS, MIN(CB6.CB6_XIMP) AS CB6_XIMP,
					CB9.CB9_NUMSER, CB9.CB9_DOC, 
					MAX(CBG.CBG_DATANF) AS CBG_DATANF, MAX(CBG.CBG_HORANF) AS CBG_HORANF, 
					MIN(SF2.F2_HAUTNFE) AS F2_HAUTNFE, MIN(SF2.F2_DAUTNFE) AS F2_DAUTNFE,
					MIN(SF2.F2_VALMERC) AS F2_VALMERC
               FROM <ADVPL>RetSqlName("CB9")</ADVPL> CB9
			   LEFT JOIN <ADVPL>RetSqlName("CB6")</ADVPL> CB6 ON CB6.D_E_L_E_T_ = ' ' AND CB6.CB6_FILIAL = CB9.CB9_FILIAL AND CB6.CB6_VOLUME = CB9.CB9_VOLUME
			   LEFT JOIN (SELECT CBG_FILIAL, CBG_ORDSEP, CAST(CBG_VOLUME AS INTEGER) AS CBG_VOLUME, 
			                     MAX(CASE WHEN CBG_EVENTO = '63' THEN CBG_DATA ELSE '' END) AS CBG_DATAI, 
								 MAX(CASE WHEN CBG_EVENTO = '63' THEN CBG_HORA ELSE '' END) AS CBG_HORAI,
			                     MAX(CASE WHEN CBG_EVENTO = '64' THEN CBG_DATA ELSE '' END) AS CBG_DATAF, 
								 MAX(CASE WHEN CBG_EVENTO = '64' THEN CBG_HORA ELSE '' END) AS CBG_HORAF,
			                     MAX(CASE WHEN CBG_EVENTO = '54' THEN CBG_DATA ELSE '' END) AS CBG_DATANF, 
								 MAX(CASE WHEN CBG_EVENTO = '54' THEN CBG_HORA ELSE '' END) AS CBG_HORANF
			                FROM <ADVPL>RetSqlName("CBG")</ADVPL>
						   WHERE D_E_L_E_T_ = ' ' AND CBG_EVENTO IN ('63', '64', '54')
						   GROUP BY CBG_FILIAL, CBG_ORDSEP, CAST(CBG_VOLUME AS INTEGER)) CBG ON CBG.CBG_FILIAL = CB9.CB9_FILIAL 
                AND CBG.CBG_ORDSEP = CB9.CB9_ORDSEP AND CBG.CBG_VOLUME = CB6.CB6_XVOL 
			   LEFT JOIN <ADVPL>RetSqlName("SF2")</ADVPL> SF2 ON SF2.D_E_L_E_T_ = ' ' AND SF2.F2_FILIAL = CB9.CB9_FILIAL AND SF2.F2_SERIE = CB9.CB9_NUMSER
			    AND SF2.F2_DOC = CB9.CB9_DOC
              WHERE CB9.D_E_L_E_T_ = ' ' AND CB9.CB9_FILIAL = '<ADVPL>xFilial("CB9")</ADVPL>' AND CB9.CB9_DISPID <> ''
			  GROUP BY CB9.CB9_FILIAL, CB9.CB9_ORDSEP, CB9.CB9_DISPID, CB9.CB9_VOLUME, 
			           CB9.CB9_NUMSER, CB9.CB9_DOC) CB9 ON CB9.CB9_FILIAL = SC5.C5_FILIAL AND CB9.CB9_ORDSEP = CB8.CB8_ORDSEP;

SELECT * FROM SC5990;
SELECT * FROM SC6990;
SELECT F2_EMISSAO, F2_HORA, F2_HAUTNFE, F2_DAUTNFE, * FROM SF2990;
SELECT * FROM CB6990;
SELECT * FROM CB9990;
SELECT * FROM CBG990 WHERE D_E_L_E_T_ = ' ' AND CBG_ORDSEP = '000102';
SELECT * FROM CBG990 WHERE D_E_L_E_T_ = ' ' AND CBG_ORDSEP = '000112' AND CBG_VOLUME = '0001';

ALTER TABLE SF2990 ADD F2_DAUTNFE VARCHAR(8);
ALTER TABLE SF2990 ADD F2_HAUTNFE VARCHAR(8);