SELECT TOP 1 B1_XCATEG, B1_XTPSRV, B1_XCTROLE, B1_XPRJSOC
  FROM SB1010;
SELECT TOP 1 F4_XTESPAE, F4_XTESVDE, F4_BONIF
  FROM SF4010;
SELECT TOP 1 D1_XDESP, D1_XVAL_C
  FROM SD1010;
SELECT TOP 1 F1_MENNOTA, F1_MENPAD, F1_XINFADX, F1_FORENT, F1_LOJAENT, F1_DAUTNFE, F1_HAUTNFE, F1_FLAGRGS, F1_IDRGS, F1_CODRGS
  FROM SF1010;

-- 1. Produtos
UPDATE SB1010
   SET B1_XCATEG = MOT.B1_XCATEG, B1_XTPSRV = MOT.B1_XTPSRV, B1_XCTROLE = MOT.B1_XCTROLE,
       B1_XPRJSOC = MOT.B1_XPRJSOC
  FROM ZT8HTG.dbo.SB1010 MOT
 WHERE SB1010.B1_COD = MOT.B1_COD;

-- 2. Natureza de Operação
UPDATE SF4010
   SET F4_XTESPAE = MOT.F4_XTESPAE, F4_XTESVDE = MOT.F4_XTESVDE, F4_BONIF = MOT.F4_BONIF
  FROM ZT8HTG.dbo.SF4010 MOT
 WHERE SF4010.F4_CODIGO = MOT.F4_CODIGO;

 -- 3. Itens das Notas de Notas de Entrada
UPDATE SD1010
   SET D1_XDESP = MOT.D1_XDESP, D1_XVAL_C = MOT.D1_XVAL_C
  FROM ZT8HTG.dbo.SD1010 MOT
 WHERE SD1010.R_E_C_N_O_ = MOT.R_E_C_N_O_;

-- 4. Notas de Notas de Entrada
UPDATE SF1010
   SET F1_MENNOTA = MOT.F1_MENNOTA, F1_MENPAD = MOT.F1_MENPAD, F1_XINFADX = MOT.F1_XINFADX, F1_FORENT = MOT.F1_FORENT, F1_LOJAENT = MOT.F1_LOJAENT,
       F1_DAUTNFE = MOT.F1_DAUTNFE, F1_HAUTNFE = MOT.F1_HAUTNFE, F1_FLAGRGS = MOT.F1_FLAGRGS, F1_IDRGS = MOT.F1_IDRGS, F1_CODRGS = MOT.F1_CODRGS
  FROM ZT8HTG.dbo.SF1010 MOT
 WHERE SF1010.R_E_C_N_O_ = MOT.R_E_C_N_O_;

 -- Refaz as visões
DROP VIEW [dbo].[SB1_N_DELET];
DROP VIEW [dbo].[SC5_N_DELET];
DROP VIEW [dbo].[SC6_N_DELET];
DROP VIEW [dbo].[SF4_N_DELET];

CREATE VIEW [dbo].[SB1_N_DELET]
AS
SELECT     *
FROM         dbo.SB1010
WHERE     (D_E_L_E_T_ <> '*');

CREATE VIEW [dbo].[SC5_N_DELET]
AS
SELECT     *
FROM         dbo.SC5010
WHERE     (D_E_L_E_T_ <> '*');

CREATE VIEW [dbo].[SC6_N_DELET]
AS
SELECT     *
FROM         dbo.SC6010
WHERE     (D_E_L_E_T_ <> '*');

CREATE VIEW [dbo].[SF4_N_DELET]
AS
SELECT     *
FROM         dbo.SF4010
WHERE     (D_E_L_E_T_ <> '*');

-- 1. SB1-Cadastro de Produtos
SELECT B1_COD, B1_CODAUX, B1_CODANTI, B1_DESC1, B1_FATYEA, B1_LISTYEA, B1_FATYEB, B1_LISTYEB, B1_POSICAO,
       B1_HIS_COD, B1_YOK, B1_XCATEG, B1_XTPSRV, B1_XCTROLE, B1_XPRJSOC
  FROM SB1010
 WHERE B1_CODAUX <> '' OR B1_CODANTI <> '' OR B1_DESC1 <> '' OR B1_FATYEA <> 0 OR B1_LISTYEA <> 0 OR
       B1_FATYEB <> 0 OR B1_LISTYEB <> 0 OR B1_POSICAO <> '' OR NOT B1_HIS_COD IS NULL OR B1_YOK <> '' OR
       B1_XCATEG <> '' OR B1_XTPSRV <> '' OR B1_XCTROLE <> '' OR B1_XPRJSOC <> '';

-- 2. Cadastro de Projetos
SELECT AF8_PROJET, AF8_XNOMCL, AF8_XVENDE, AF8_XCOMIS, AF8_XRESP1, AF8_XRESP2, AF8_XPROP, AF8_XVLACO,
       AF8_XPRJOR,AF8_XNMAPR, AF8_XDTAPR, AF8_XHRAPR, AF8_XCODSR, AF8_XREPRE, AF8_XDOORC, AF8_XDOREA,
       AF8_XDESP
  FROM AF8010
 WHERE AF8_XNOMCL <> '' OR AF8_XVENDE <> '' OR AF8_XCOMIS <> 0 OR AF8_XRESP1 <> '' OR AF8_XRESP2 <> '' OR
       AF8_XPROP <> '' OR AF8_XVLACO <> 0 OR AF8_XPRJOR <> '' OR
       AF8_XNMAPR <> '' OR AF8_XDTAPR <> '' OR AF8_XHRAPR <> '' OR AF8_XCODSR <> '' OR AF8_XREPRE <> '' OR
       AF8_XDOORC <> 0 OR AF8_XDOREA <> 0 OR AF8_XDESP <> '';

-- Recupera os dados
UPDATE AF8010
   SET AF8_XNOMCL = MOT.AF8_XNOMCL, AF8_XVENDE = MOT.AF8_XVENDE, AF8_XCOMIS = MOT.AF8_XCOMIS,
       AF8_XRESP1 = MOT.AF8_XRESP1, AF8_XRESP2 = MOT.AF8_XRESP2, AF8_XPROP = MOT.AF8_XPROP,
       AF8_XVLACO = MOT.AF8_XVLACO, AF8_XPRJOR = MOT.AF8_XPRJOR, AF8_XNMAPR = MOT.AF8_XNMAPR,
       AF8_XDTAPR = MOT.AF8_XDTAPR, AF8_XHRAPR = MOT.AF8_XHRAPR, AF8_XCODSR = MOT.AF8_XCODSR,
       AF8_XREPRE = MOT.AF8_XREPRE, AF8_XDOORC = MOT.AF8_XDOORC, AF8_XDOREA = MOT.AF8_XDOREA,
       AF8_XDESP = MOT.AF8_XDESP, AF8_XVLTRE = MOT.AF8_XVLTRE
  FROM MOT.dbo.AF8010 MOT
 WHERE AF8010.AF8_PROJET = MOT.AF8_PROJET;

-- 3. Pedido de Vendas
SELECT C5_NUM, C5_TPTES, C5_DESCTES, C5_CODPED, C5_CODSIS, C5_PEDCLI, C5_PROP, C5_PO, C5_DT_PO, C5_DT_PREV,
       C5_PARC5, C5_DATA5, C5_PARC6, C5_DATA6, C5_PARC7, C5_DATA7, C5_PARC8, C5_DATA8,
       C5_PARC9, C5_DATA9, C5_PARCA, C5_DATAA, C5_PARCB, C5_DATAB, C5_PARCC, C5_DATAC, C5_MSGIND,
       C5_PROJETO, C5_NATUREZ, C5_XDEPART, C5_XPROJET, C5_XTSKPMS, C5_XMRGPRO, C5_XVLACO, C5_XDOORC,
       C5_XDOREA, C5_XCC
  FROM SC5010
 WHERE C5_TPTES <> '' OR C5_DESCTES <> '' OR C5_CODPED <> '' OR C5_CODSIS <> '' OR C5_PEDCLI <> '' OR
       C5_PROP <> '' OR C5_PO <> '' OR C5_DT_PO <> '' OR C5_DT_PREV <> '' OR C5_PARC5 <> 0 OR
       C5_DATA5 <> '' OR C5_PARC6 <> 0 OR C5_DATA6 <> '' OR C5_PARC7 <> 0 OR C5_DATA7 <> '' OR
       C5_PARC8 <> 0 OR C5_DATA8 <> '' OR C5_PARC9 <> 0 OR C5_DATA9 <> '' OR C5_PARCA <> 0 OR
       C5_DATAA <> '' OR C5_PARCB <> 0 OR C5_DATAB <> '' OR C5_PARCC <> 0 OR C5_DATAC <> '' OR
       C5_MSGIND <> '' OR C5_PROJETO <> '' OR C5_NATUREZ <> '' OR C5_XDEPART <> '' OR C5_XPROJET <> '' OR
       C5_XTSKPMS <> '' OR C5_XMRGPRO <> 0 OR C5_XVLACO <> 0 OR C5_XDOORC <> 0 OR C5_XDOREA <> 0 OR
       C5_XCC <> '';

-- Recupera os dados
UPDATE SC6010
   SET C6_XCC = MOT.C6_XCC, C6_XVALTRE = MOT.C6_XVALTRE
  FROM MOT.dbo.SC6010 MOT
 WHERE SC6010.C6_NUM = MOT.C6_NUM AND SC6010.C6_ITEM = MOT.C6_ITEM AND SC6010.C6_PRODUTO = MOT.C6_PRODUTO;

-- 4. Itens de Nota de Saída
SELECT D2_XCC, D2_XPROJET, D2_XEDTPMS, * FROM SD2010
 WHERE D2_XCC <> '' OR D2_XPROJET <> '' OR D2_XEDTPMS <> '';

-- Recupera os dados
UPDATE SD2010
   SET D2_XCC = MOT.D2_XCC
  FROM MOT.dbo.SD2010 MOT
 WHERE SD2010.D2_DOC = MOT.D2_DOC AND SD2010.D2_SERIE = MOT.D2_SERIE AND SD2010.D2_ITEM = MOT.D2_ITEM;

-- 6. Clientes
UPDATE SA1010
   SET A1_X_CON_P = MOT.A1_X_CON_P, A1_X_MAILP = MOT.A1_X_MAILP, A1_TPASS = MOT.A1_TPASS, A1_TPUTI = MOT.A1_TPUTI,
       A1_GRPTEN = MOT.A1_GRPTEN, A1_NTELCON = MOT.A1_NTELCON
  FROM MOT.dbo.SF4010 MOT
 WHERE SA1010.A1_COD = MOT.A1_COD AND SA1010.A1_LOJA = MOT.A1_LOJA;

 -- 8. Centro de Custos
UPDATE CTT010
   SET CTT_XOBPRJ = MOT.CTT_XOBPRJ, CTT_XVDISP = MOT.CTT_XVDISP
  FROM MOT.dbo.CTT010 MOT
 WHERE CTT010.R_E_C_N_O_ = MOT.R_E_C_N_O_;

