-- Eventos com hora extra
SELECT SP9.P9_CODIGO
  FROM SP9010 SP9
  JOIN SRV010 SRV ON SRV.D_E_L_E_T_ = ' ' AND SRV.RV_FILIAL = ' ' AND SRV.RV_COD = SP9.P9_CODFOL
   AND SRV.RV_TIPOCOD = '1' AND SRV.RV_PERC > 0
 WHERE SP9.D_E_L_E_T_ = ' ' AND SP9.P9_CODFOL <> ''
 ORDER BY SP9.P9_CODIGO;

-- Eventos de pagamento de banco de horas
SELECT * FROM SP9010 WHERE D_E_L_E_T_ = ' ' AND P9_TIPOCOD = '1' AND P9_BHORAS = 'S'

-- Consulta que retorna apontamentos com banco e extras
create view EXTRAS_BANCO as
select SPC.PC_MAT, SPC.PC_DATA, SUM(case when SPC.PC_PD = '107' then SPC.PC_QUANTC else null end) as EXTRAS,
       SUM(case when SPC.PC_PD = '052' then SPC.PC_QUANTC else null end) as BANCO,
       MIN(case when SPC.PC_PD = '107' then SPC.R_E_C_N_O_ else null end) as RECNO_107,
       MIN(case when SPC.PC_PD = '052' then SPC.R_E_C_N_O_ else null end) as RECNO_052
  from SPC010 SPC
  join (SELECT SP9.P9_CODIGO
          FROM SP9010 SP9
          JOIN SRV010 SRV ON SRV.D_E_L_E_T_ = ' ' AND SRV.RV_FILIAL = ' ' AND SRV.RV_COD = SP9.P9_CODFOL
           AND SRV.RV_TIPOCOD = '1' AND SRV.RV_PERC > 0
         WHERE SP9.D_E_L_E_T_ = ' ' AND SP9.P9_CODFOL <> ''
         UNION
         SELECT '052' AS P9_CODIGO) SP9 ON SP9.P9_CODIGO = SPC.PC_PD
 where SPC.D_E_L_E_T_ = ' '
 group by SPC.PC_MAT, SPC.PC_DATA
having count(*) > 1;

-- Limpa horas informadas
update SPC010
   set PC_PDI = '', PC_QUANTI = 0, 
       PC_DATAALT = '',
       PC_HORAALT = '',
       PC_USUARIO = ''
 where PC_MAT = '2035' and PC_DATA = '20121129' and PC_PD in ('052', '107');
 
-- Troca 052 (Banco) para 107 (Extras)
update SPC010
   set PC_PDI = '107', PC_QUANTI = PC_QUANTC, 
       PC_DATAALT = cast(DATEPART(year, CURRENT_TIMESTAMP) as varchar(4)) +
                    dbo.strzero(DATEPART(month, CURRENT_TIMESTAMP), 2) +
                    dbo.strzero(DATEPART(day, CURRENT_TIMESTAMP), 2),
       PC_HORAALT = cast(DATEPART(hour, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(minute, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(second, CURRENT_TIMESTAMP) as varchar(2)),
       PC_USUARIO = '000158'
  from EXTRAS_BANCO
 where SPC010.D_E_L_E_T_ = ' '
   and SPC010.PC_MAT = '2035' and SPC010.PC_DATA = '20121129' and SPC010.PC_PD in ('052', '107')
   and SPC010.R_E_C_N_O_ = EXTRAS_BANCO.RECNO_107
       
-- Troca 107 (Extras) para 052 (Banco)
update SPC010
   set PC_PDI = '052', PC_QUANTI = PC_QUANTC, 
       PC_DATAALT = cast(DATEPART(year, CURRENT_TIMESTAMP) as varchar(4)) +
                    dbo.strzero(DATEPART(month, CURRENT_TIMESTAMP), 2) +
                    dbo.strzero(DATEPART(day, CURRENT_TIMESTAMP), 2),
       PC_HORAALT = cast(DATEPART(hour, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(minute, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(second, CURRENT_TIMESTAMP) as varchar(2)),
       PC_USUARIO = '000158'
  from EXTRAS_BANCO
 where SPC010.D_E_L_E_T_ = ' '
   and SPC010.PC_MAT = '2035' and SPC010.PC_DATA = '20121129' and SPC010.PC_PD in ('052', '107')
   and SPC010.R_E_C_N_O_ = EXTRAS_BANCO.RECNO_052;

-- ID: RICARDO - 000158
-- ID: LETICIA - 000190

select * from SPC010
 where D_E_L_E_T_ = ' ' and R_E_C_N_O_ in (3223, 6926);

SELECT * from EXTRAS_BANCO
 ORDER BY PC_DATA, PC_MAT;

SELECT * from EXTRAS_BANCO
 WHERE PC_MAT = '3101';;

CREATE TABLE HORAS_AUTORIZADAS(RA_MAT VARCHAR(6), DATA_INICIAL VARCHAR(8), DATA_FINAL VARCHAR(8));

INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3101', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3124', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3072', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3113', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('2035', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3132', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3122', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3102', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3086', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3106', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3115', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3084', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3077', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3105', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3118', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3026', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3051', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3099', '20121215', '20130116');

--// Incluido em 24/01/2013
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3083', '20121215', '20130116');
INSERT INTO HORAS_AUTORIZADAS(RA_MAT, DATA_INICIAL, DATA_FINAL) VALUES('3087', '20121215', '20130116');

SELECT * FROM HORAS_AUTORIZADAS;

SELECT EXT.* from EXTRAS_BANCO EXT
  JOIN HORAS_AUTORIZADAS AUT ON AUT.RA_MAT = EXT.PC_MAT
 WHERE EXT.PC_MAT = '3101' AND EXT.PC_DATA BETWEEN AUT.DATA_INICIAL AND AUT.DATA_FINAL;

-- Troca 052 (Banco) para 107 (Extras)
update SPC010
   set PC_PDI = '107', PC_QUANTI = PC_QUANTC,
       PC_DATAALT = cast(DATEPART(year, CURRENT_TIMESTAMP) as varchar(4)) +
                    dbo.strzero(DATEPART(month, CURRENT_TIMESTAMP), 2) +
                    dbo.strzero(DATEPART(day, CURRENT_TIMESTAMP), 2),
       PC_HORAALT = cast(DATEPART(hour, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(minute, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(second, CURRENT_TIMESTAMP) as varchar(2)),
       PC_USUARIO = '000190'
  from EXTRAS_BANCO
  JOIN HORAS_AUTORIZADAS AUT ON AUT.RA_MAT = EXTRAS_BANCO.PC_MAT
   AND EXTRAS_BANCO.PC_DATA BETWEEN AUT.DATA_INICIAL AND AUT.DATA_FINAL
 where SPC010.D_E_L_E_T_ = ' '
   and SPC010.PC_MAT = EXTRAS_BANCO.PC_MAT and SPC010.PC_DATA = EXTRAS_BANCO.PC_DATA
   and SPC010.PC_PD = '052' and SPC010.R_E_C_N_O_ = EXTRAS_BANCO.RECNO_052;

select SPC010.*
  from SPC010, EXTRAS_BANCO
  JOIN HORAS_AUTORIZADAS AUT ON AUT.RA_MAT = EXTRAS_BANCO.PC_MAT
   AND EXTRAS_BANCO.PC_DATA BETWEEN AUT.DATA_INICIAL AND AUT.DATA_FINAL
 where SPC010.D_E_L_E_T_ = ' '
   and SPC010.PC_MAT = EXTRAS_BANCO.PC_MAT and SPC010.PC_DATA = EXTRAS_BANCO.PC_DATA
   and SPC010.PC_PD = '052' and SPC010.R_E_C_N_O_ = EXTRAS_BANCO.RECNO_052
 order by SPC010.PC_MAT, SPC010.PC_DATA;

select * into SPC010_EXTRAS from SPC010;

-- 2 Matriculas incluidas
update SPC010
   set PC_PDI = '107', PC_QUANTI = PC_QUANTC,
       PC_DATAALT = cast(DATEPART(year, CURRENT_TIMESTAMP) as varchar(4)) +
                    dbo.strzero(DATEPART(month, CURRENT_TIMESTAMP), 2) +
                    dbo.strzero(DATEPART(day, CURRENT_TIMESTAMP), 2),
       PC_HORAALT = cast(DATEPART(hour, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(minute, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(second, CURRENT_TIMESTAMP) as varchar(2)),
       PC_USUARIO = '000190'
  from EXTRAS_BANCO
  JOIN HORAS_AUTORIZADAS AUT ON AUT.RA_MAT = EXTRAS_BANCO.PC_MAT
   AND EXTRAS_BANCO.PC_DATA BETWEEN AUT.DATA_INICIAL AND AUT.DATA_FINAL
 where SPC010.D_E_L_E_T_ = ' '
   and SPC010.PC_MAT = EXTRAS_BANCO.PC_MAT and SPC010.PC_DATA = EXTRAS_BANCO.PC_DATA
   and SPC010.PC_PD = '052' and SPC010.R_E_C_N_O_ = EXTRAS_BANCO.RECNO_052
   and SPC010.PC_MAT in ('3083', '3087') ;

-- Troca 107 (Extras) para 052 (Banco)
update SPC010
   set PC_PDI = '052', PC_QUANTI = PC_QUANTC,
       PC_DATAALT = cast(DATEPART(year, CURRENT_TIMESTAMP) as varchar(4)) +
                    dbo.strzero(DATEPART(month, CURRENT_TIMESTAMP), 2) +
                    dbo.strzero(DATEPART(day, CURRENT_TIMESTAMP), 2),
       PC_HORAALT = cast(DATEPART(hour, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(minute, CURRENT_TIMESTAMP) as varchar(2)) +
                    cast(DATEPART(second, CURRENT_TIMESTAMP) as varchar(2)),
       PC_USUARIO = '000190'
  from EXTRAS_BANCO
  JOIN HORAS_AUTORIZADAS AUT ON AUT.RA_MAT = EXTRAS_BANCO.PC_MAT
   AND EXTRAS_BANCO.PC_DATA BETWEEN AUT.DATA_INICIAL AND AUT.DATA_FINAL
 where SPC010.D_E_L_E_T_ = ' '
   and SPC010.PC_MAT = EXTRAS_BANCO.PC_MAT and SPC010.PC_DATA = EXTRAS_BANCO.PC_DATA
   and SPC010.PC_PD = '107' and SPC010.R_E_C_N_O_ = EXTRAS_BANCO.RECNO_107;
