-- Contagem
SELECT A1_EST, A1_MUN, COUNT(*) AS CLIENTES
  FROM SA1000
 WHERE A1_FILIAL = ' ' AND A1_EST = 'SP' 
 GROUP BY A1_EST, A1_MUN
 ORDER BY A1_EST, A1_MUN

SELECT * FROM SA1000 
 WHERE A1_FILIAL = ' ' AND A1_EST = 'SP' 
 ORDER BY A1_MCOMPRA DESC

-- Clientes - Contratos
SELECT A1_NOME AS NOME, A1_NREDUZ AS FANTASIA, A1_CGC AS CNPJ, 
       AOV_CODSEG, AOV_DESSEG, A1_CNAE AS CNAE, CC3_DESC AS NOMECNAE, A1_END AS ENDERECO, 
	   A1_XNEND AS NUMERO, A1_BAIRRO AS BAIRRO, 
	   A1_MUN AS CIDADE, A1_CONTATO AS CONTATO, A1_TEL, A1_XEMAILF,
       A1_ULTCOM AS ULTPGTO, A1_MCOMPRA, A1_NROCOM, CNB.*
  FROM SA1000 SA1
  LEFT JOIN CC3000 CC3 ON CC3_COD = A1_CNAE AND CC3.D_E_L_E_T_ = ' '
  LEFT JOIN AOV000 AOV ON AOV_CODSEG = CC3_CODSEG AND AOV.D_E_L_E_T_ = ' '
  JOIN (
SELECT MAX(CNC_CLIENT) AS A1_COD, B1_COD, MIN(B1_DESC) AS B1_DESC, MAX(CNB_QUANT) AS CNB_QUANT, MAX(CNB_VLUNIT) AS CNB_VLUNIT
  FROM CNC000 CNC
  JOIN SA1000 SA1 ON A1_FILIAL = CNC_FILIAL AND A1_COD = CNC_CLIENT AND A1_EST = 'SP' 
   AND A1_MUN IN ('SANTO ANDRE', 'MAUA', 'RIBEIRAO PIRES', 'SAO BERNARDO DO CAMPO', 'SAO PAULO', 'SUZANO',
                  'SAO CAETANO DO SUL')
   AND A1_ULTCOM <> ' ' AND A1_MCOMPRA > 10000 AND A1_MSBLQL <> '1' AND A1_XSITCLI <> '2' AND SA1.D_E_L_E_T_ = ' ' 
   AND A1_ULTCOM >= '20180101' AND SA1.D_E_L_E_T_ = ' '
  JOIN CNB000 CNB ON CNB_FILIAL = CNC_FILIAL AND CNB_CONTRA = CNC_NUMERO AND CNB_REVISA = CNC_REVISA AND CNB_SITUAC = 'A'
   AND CNB.D_E_L_E_T_ = ' '
  JOIN SB1000 SB1 ON B1_FILIAL = CNC_FILIAL AND B1_COD = CNB_PRODUT AND SB1.D_E_L_E_T_ = ' '
 WHERE CNC_FILIAL = ' ' AND SUBSTR(CNC_NUMERO, 1, 3) = 'CON' AND CNC_TIPCLI = '01' AND CNC.D_E_L_E_T_ = ' '
 GROUP BY CNC_NUMERO, B1_COD, CNB_QUANT, CNB_VLUNIT) CNB ON CNB.A1_COD = SA1.A1_COD 
 ORDER BY A1_MUN, A1_MCOMPRA DESC

-- Clientes - Contratos - SC
SELECT A1_NOME AS NOME, A1_NREDUZ AS FANTASIA, A1_CGC AS CNPJ, 
       AOV_CODSEG, AOV_DESSEG, A1_CNAE AS CNAE, CC3_DESC AS NOMECNAE, A1_END AS ENDERECO, 
       A1_XNEND AS NUMERO, A1_BAIRRO AS BAIRRO, 
       A1_MUN AS CIDADE, A1_CONTATO AS CONTATO, A1_TEL, A1_XEMAILF,
       A1_ULTCOM AS ULTPGTO, A1_MCOMPRA, A1_NROCOM, CNB.*
  FROM SA1000 SA1
  LEFT JOIN CC3000 CC3 ON CC3_COD = A1_CNAE AND CC3.D_E_L_E_T_ = ' '
  LEFT JOIN AOV000 AOV ON AOV_CODSEG = CC3_CODSEG AND AOV.D_E_L_E_T_ = ' '
  JOIN (
SELECT MAX(CNC_CLIENT) AS A1_COD, B1_COD, MIN(B1_DESC) AS B1_DESC, MAX(CNB_QUANT) AS CNB_QUANT, MAX(CNB_VLUNIT) AS CNB_VLUNIT
  FROM CNC000 CNC
  JOIN CN9000 CN9 ON CN9.CN9_FILIAL = CNC_FILIAL AND CN9_NUMERO = CNC_NUMERO AND CN9.CN9_SITUAC = '05' AND CN9.CN9_REVATU = ' ' AND CN9.D_E_L_E_T_ = ' '
  JOIN SA1000 SA1 ON A1_FILIAL = CNC_FILIAL AND A1_COD = CNC_CLIENT AND A1_EST = 'SC' 
   AND A1_ULTCOM <> ' ' AND A1_MSBLQL <> '1' AND SA1.D_E_L_E_T_ = ' ' 
   AND A1_ULTCOM >= '20190101' AND SA1.D_E_L_E_T_ = ' '
  JOIN CNB000 CNB ON CNB_FILIAL = CNC_FILIAL AND CNB_CONTRA = CNC_NUMERO AND CNB_REVISA = CNC_REVISA AND CNB_SITUAC = 'A'
   AND CNB.D_E_L_E_T_ = ' '
  JOIN SB1000 SB1 ON B1_FILIAL = CNC_FILIAL AND B1_COD = CNB_PRODUT AND SB1.D_E_L_E_T_ = ' '
 WHERE CNC_FILIAL = ' ' AND CNC_NUMERO BETWEEN ' ' AND 'ZZZZZZZZZZZZZZZ' AND CNC_REVISA BETWEEN ' ' AND 'ZZZZZZ' AND CNC.D_E_L_E_T_ = ' '
 GROUP BY CNC_NUMERO, B1_COD, CNB_QUANT, CNB_VLUNIT) CNB ON CNB.A1_COD = SA1.A1_COD 
 ORDER BY A1_MUN, A1_MCOMPRA DESC 
 
 -- Select
 SELECT SA1.*
  FROM (SELECT A1_NOME, A1_NREDUZ, A1_CGC, A1_END, A1_XNEND, A1_BAIRRO, A1_MUN, A1_CONTATO, A1_TEL, A1_XEMAILF,
               A1_ULTCOM, A1_MCOMPRA, A1_NROCOM, CNB_PRODUT, CNB_ITEM, MIN(CNB_QUANT) AS CNB_QUANT, MIN(CNB_VLUNIT) AS CNB_VLUNIT
	      FROM CNB000 CNB  
          JOIN CN9000 CN9 ON CN9.CN9_FILIAL = ' ' AND CN9.CN9_NUMERO = CNB.CNB_CONTRA AND CN9.CN9_REVISA = CNB.CNB_REVISA AND CN9.CN9_SITUAC = '05' 
           AND CN9.CN9_ESPCTR = '2' AND CN9.D_E_L_E_T_ = ' '
          JOIN SA1000 SA1 ON SA1.A1_FILIAL = ' ' AND SA1.A1_COD = SUBSTR( CNB_CONTRA, 4, 6 ) AND SA1.A1_LOJA = '00'  
           AND A1_COD BETWEEN ' ' AND 'ZZZZZ' AND A1_EST = 'SC' AND SA1.A1_MSBLQL IN (' ', '2') AND SA1.D_E_L_E_T_ = ' ' 
         WHERE CNB.CNB_FILIAL  = ' '  AND CNB_CONTRA BETWEEN ' ' AND 'ZZZZZ' AND CNB_REVISA BETWEEN ' ' AND 'ZZZZZ'
           AND CNB_NUMERO BETWEEN ' ' AND 'ZZZZZ' AND CNB_ITEM BETWEEN ' ' AND 'ZZZZZ' AND CNB.CNB_SITUAC = 'A' 
           AND CNB.CNB_TIPREC = '1' AND CNB.D_E_L_E_T_ = ' ' 
	GROUP BY A1_NOME, A1_NREDUZ, A1_CGC, A1_END, A1_XNEND, A1_BAIRRO, A1_MUN, A1_CONTATO, A1_TEL, A1_XEMAILF,
               A1_ULTCOM, A1_MCOMPRA, A1_NROCOM, CNB_PRODUT, CNB_ITEM) SA1	

          AOV_CODSEG, MIN(AOV_DESSEG) AS AOV_DESSEG, A1_CNAE, MIN(CC3_DESC) AS NOMECNAE, 
			   
		  LEFT JOIN CC3000 CC3 ON CC3_COD = A1_CNAE AND CC3.D_E_L_E_T_ = ' '
          LEFT JOIN AOV000 AOV ON AOV_CODSEG = CC3_CODSEG AND AOV.D_E_L_E_T_ = ' '
			   
-- Clientes
SELECT A1_NOME AS NOME, A1_NREDUZ AS FANTASIA, A1_CGC AS CNPJ, 
       AOV_CODSEG, AOV_DESSEG, A1_CNAE AS CNAE, CC3_DESC AS NOMECNAE, A1_END AS ENDERECO, 
	   A1_XNEND AS NUMERO, A1_BAIRRO AS BAIRRO, 
	   A1_MUN AS CIDADE, A1_CONTATO AS CONTATO, A1_TEL, A1_XEMAILF,
       A1_ULTCOM AS ULTPGTO, A1_MCOMPRA, A1_NROCOM, CNB.*
  FROM SA1000 SA1
  LEFT JOIN CC3000 CC3 ON CC3_COD = A1_CNAE AND CC3.D_E_L_E_T_ = ' '
  LEFT JOIN AOV000 AOV ON AOV_CODSEG = CC3_CODSEG AND AOV.D_E_L_E_T_ = ' '
JOIN (
SELECT MAX(CNC_CLIENT) AS A1_COD
  FROM CNC000 CNC
  JOIN SA1000 SA1 ON A1_FILIAL = CNC_FILIAL AND A1_COD = CNC_CLIENT AND A1_EST = 'SP' 
   AND A1_MUN IN ('SANTO ANDRE', 'MAUA', 'RIBEIRAO PIRES', 'SAO BERNARDO DO CAMPO', 'SAO PAULO', 'SUZANO',
                  'SAO CAETANO DO SUL')
  JOIN CNB000 CNB ON CNB_FILIAL = CNC_FILIAL AND CNB_CONTRA = CNC_NUMERO AND CNB_REVISA = CNC_REVISA AND CNB_SITUAC = 'A'
   AND CNB.D_E_L_E_T_ = ' '
   AND A1_ULTCOM <> ' ' AND A1_MCOMPRA > 10000 AND A1_MSBLQL <> '1' AND A1_XSITCLI <> '2' AND SA1.D_E_L_E_T_ = ' ' AND A1_ULTCOM >= '20180101'
 WHERE CNC_FILIAL = ' ' AND SUBSTR(CNC_NUMERO, 1, 3) = 'CON' AND CNC_TIPCLI = '01' AND CNC.D_E_L_E_T_ = ' '
 GROUP BY CNC_NUMERO) CNB ON CNB.A1_COD = SA1.A1_COD   
 WHERE A1_EST = 'SP' 
   AND A1_MUN IN ('SANTO ANDRE', 'MAUA', 'RIBEIRAO PIRES', 'SAO BERNARDO DO CAMPO', 'SAO PAULO', 'SUZANO',
                  'SAO CAETANO DO SUL')
   AND A1_ULTCOM <> ' ' AND A1_MCOMPRA > 10000 AND A1_MSBLQL <> '1' AND A1_XSITCLI <> '2' AND SA1.D_E_L_E_T_ = ' ' 
   AND A1_ULTCOM >= '20180101' AND SA1.D_E_L_E_T_ = ' '
 ORDER BY A1_MUN, A1_MCOMPRA DESC
 
SELECT COUNT(*)
  FROM (SELECT A1_FILIAL, A1_COD, A1_LOJA, A1_NOME, A1_CGC, A1_XEMAILF, A1_DDD, A1_TEL, A1_END, A1_COMPLEM, A1_BAIRRO, A1_CEP, A1_MUN, A1_EST
	  FROM CNB000 CNB  
          JOIN CN9000 CN9 ON CN9.CN9_FILIAL = ' ' AND CN9.CN9_NUMERO = CNB.CNB_CONTRA AND CN9.CN9_REVISA = CNB.CNB_REVISA AND CN9.CN9_SITUAC = '05' 
           AND CN9.CN9_ESPCTR = '2' AND CN9.D_E_L_E_T_ = ' '
          JOIN SA1000 SA1 ON SA1.A1_FILIAL = ' ' AND SA1.A1_COD = SUBSTR( CNB_CONTRA, 4, 6 ) AND SA1.A1_LOJA = '00'  
           AND A1_COD BETWEEN ' ' AND 'ZZZZZ' AND SA1.A1_MSBLQL IN (' ', '2') AND SA1.D_E_L_E_T_ = ' ' 
         WHERE CNB.CNB_FILIAL  = ' '  AND CNB_CONTRA BETWEEN ' ' AND 'ZZZZZ' AND CNB_REVISA BETWEEN ' ' AND 'ZZZZZ'
           AND CNB_NUMERO BETWEEN ' ' AND 'ZZZZZ' AND CNB_ITEM BETWEEN ' ' AND 'ZZZZZ' AND CNB.CNB_SITUAC = 'A' AND CNB.D_E_L_E_T_ = ' ' 
	GROUP BY A1_FILIAL, A1_COD, A1_LOJA, A1_NOME, A1_CGC, A1_XEMAILF, A1_DDD, A1_TEL, A1_END, A1_COMPLEM, A1_BAIRRO, A1_CEP, A1_MUN, A1_EST) SA1	
