-- Ligação SWN x SD1
SELECT WN_LINHA, * FROM SWN010 SWN
 WHERE SWN.D_E_L_E_T_= ' ' AND WN_DOC = '000002923'
   AND EXISTS(SELECT 1 FROM SD1010 WHERE D1_DOC = SWN.WN_DOC AND D1_SERIE = SWN.WN_SERIE
                 AND D1_FORNECE = SWN.WN_FORNECE AND D1_LOJA = SWN.WN_LOJA AND D1_COD = SWN.WN_PRODUTO
                 AND D1_PEDIDO = SWN.WN_PO_NUM  AND D1_ITEM = CAST(SWN.WN_LINHA AS INTEGER)
                 AND D_E_L_E_T_= ' ')
 ORDER BY WN_DOC, WN_PO_NUM;

SELECT WN_LINHA,* FROM SWN010 WHERE WN_DOC = '000002923' AND WN_PRODUTO = '153198-1' ORDER BY WN_LINHA;
SELECT * FROM SD1010 WHERE D1_DOC = '000002923' AND D1_COD = '153198-1' ORDER BY D1_ITEM;

SELECT D1_PEDIDO,D1_ITEM,* FROM SD1010 WHERE D1_DOC = '000003835';
SELECT WN_LINHA,* FROM SWN010 WHERE WN_DOC = '000003835' ORDER BY WN_LINHA;

select D1_ITEM, D1_PEDIDO, * from SD1010 WHERE D1_CUSTO = 37.63 AND D1_COD = '153198-1' AND D_E_L_E_T_ = ' ';
select D1_DOC, D1_ITEM, D1_PEDIDO, * from SD1010 WHERE D1_CUSTO = 61.52 AND D1_COD = 'MANUAL' AND D_E_L_E_T_ = ' ';

SELECT * FROM SWN010 WHERE WN_PO_NUM = '006585' AND WN_PRODUTO = '153198-1' AND D_E_L_E_T_ = ' ';
SELECT * FROM SWN010 WHERE WN_PO_NUM IN ('007063','007065') AND WN_PRODUTO = 'MANUAL' AND D_E_L_E_T_ = ' ';

        SELECT SUM(D1_CUSTO)
          FROM (
SELECT D1_CUSTO, D1_SERIE, D1_COD, D1_DOC
FROM SD1010 D1, SF4010 F4
WHERE D1_FILIAL  = '01'
AND F4_FILIAL    = '01'
AND D1_TES       = F4_CODIGO
AND F4_ESTOQUE   = 'S' AND F4_PODER3 = 'N'
AND D1_TIPO <> 'D' AND D1_ORIGLAN <> 'LF'
AND D1_DTDIGIT >= '20110101'        
AND D1_DTDIGIT <= '20110110'
AND D1.D_E_L_E_T_=''
AND F4.D_E_L_E_T_=''
-- ORDER BY D1_DTDIGIT, D1_SERIE, D1_DOC
			  ) AS SD1

-- Relatório de Compras
        SELECT SUM(D1_CUSTO)
          FROM (
		SELECT 	'SD1' ARQ, SB1.B1_COD PRODUTO, SB1.B1_TIPO, SB1.B1_UM, SB1.B1_GRUPO, SB1.B1_DESC, D1_DTDIGIT DATA,	
				 D1_TES TES, D1_CF CF, D1_NUMSEQ SEQUENCIA,	D1_DOC DOCUMENTO, D1_SERIE SERIE, D1_QUANT QUANTIDADE,
				 D1_QTSEGUM QUANT2UM, D1_LOCAL ARMAZEM,	' ' OP,	D1_FORNECE FORNECEDOR, D1_LOJA LOJA, D1_TIPO TIPONF,
				 SD1.R_E_C_N_O_ NRECNO, CASE WHEN SF4.F4_PODER3 = 'N' AND SD1.D1_TIPO <> 'D' THEN SD1.D1_CUSTO ELSE 0 END AS D1_CUSTO
	
		FROM SB1010 SB1, SD1010 SD1, SF4010 SF4
	
		WHERE SB1.B1_COD     =  SD1.D1_COD		AND  	SD1.D1_FILIAL  =  '01'		        AND
			  SF4.F4_FILIAL  =  '01'           	AND 	SD1.D1_TES     =  SF4.F4_CODIGO		AND
			  SF4.F4_ESTOQUE =  'S'				AND 	SD1.D1_DTDIGIT >= '20110101'        AND
			  SD1.D1_DTDIGIT <= '20110110'   	AND		SD1.D1_ORIGLAN <> 'LF'				AND
			  SD1.D1_LOCAL   >= '  '          	AND		SD1.D1_LOCAL   <= 'ZZ'          	AND
			  SD1.D_E_L_E_T_ = ' '            	AND 	SF4.D_E_L_E_T_ = ' '                AND
	          SB1.B1_COD     >= ' '           	AND		SB1.B1_COD     <= 'ZZZZZZZZZZZZZZZ'	AND
			  SB1.B1_FILIAL  =  '01'            AND		SB1.B1_TIPO    >= '  '          	AND
			  SB1.B1_TIPO    <= 'ZZ'          	AND		SB1.D_E_L_E_T_ = ' '
			  ) AS SD1

-- Ligação entre SD1 e SWN
select SWN.WN_DOC, SWN.WN_SERIE, SWN.WN_FORNECE, SWN.WN_LOJA, SWN.WN_PRODUTO, SWN.WN_PO_NUM, SWN.WN_LINHA, * 
  from SWN010 SWN where WN_DOC LIKE '002438';
select D1.D1_DOC, D1.D1_SERIE, D1.D1_FORNECE, D1.D1_LOJA, D1.D1_COD, D1.D1_PEDIDO, D1.D1_ITEM, * 
  from SD1010 D1 where D1.D1_DOC LIKE '002438';

-- Query totalizando custo
SELECT D1.D1_DTDIGIT, SUM(D1.D1_CUSTO) AS D1_CUSTO, SUM(D1.D1_TOTAL) AS D1_TOTAL,
       SUM((
       case when not SWN.WN_DOC is null 
            then (D1.D1_TOTAL + D1.D1_VALIPI + SWN.WN_DESPICM + SWN.WN_OUT_DES + SWN.WN_VL_ICM + SWN.WN_VLRPIS + SWN.WN_VLRCOF)
            else D1.D1_CUSTO - case when SF1.F1_EST = 'EX' then ((D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6)) else 0 end end +
       CASE WHEN SWN.WN_FILIAL IS NULL THEN D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6 ELSE 0 END) * 
                 case when D1.D1_TIPO = 'D' then -1 else 1 end) as CUSTO,
       SUM(
       CASE WHEN NOT SWN.WN_FILIAL IS NULL 
            THEN SWN.WN_OUT_DES+SWN.WN_VL_ICM+SWN.WN_VLRPIS+SWN.WN_VLRCOF+SWN.WN_VALIPI
             ELSE D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6 END) AS OUTROS,
       SUM((
       case when not SWN.WN_DOC is null 
            then (D1.D1_TOTAL + D1.D1_VALIPI + SWN.WN_DESPICM + SWN.WN_OUT_DES + SWN.WN_VL_ICM + SWN.WN_VLRPIS + SWN.WN_VLRCOF)
            else D1.D1_CUSTO - case when SF1.F1_EST = 'EX' then ((D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6)) else 0 end end +
       CASE WHEN SWN.WN_FILIAL IS NULL THEN D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6 ELSE 0 END) * 
                 case when D1.D1_TIPO = 'D' then -1 else 1 end) -
       SUM(
       CASE WHEN NOT SWN.WN_FILIAL IS NULL 
            THEN SWN.WN_OUT_DES+SWN.WN_VL_ICM+SWN.WN_VLRPIS+SWN.WN_VLRCOF+SWN.WN_VALIPI
             ELSE D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6 END) AS LIQUIDO          
  FROM SD1010 D1
--JOIN SF4010 F4 ON F4.F4_CODIGO = D1.D1_TES AND (F4.F4_DUPLIC ='S' OR F4.F4_ESTOQUE= 'S' OR D1.D1_TIPO_NF <>'') AND F4.D_E_L_E_T_=' '
  JOIN SF4010 F4 ON F4.F4_CODIGO = D1.D1_TES AND F4.F4_ESTOQUE= 'S' AND F4.D_E_L_E_T_=' '
  LEFT JOIN SWN010 SWN ON SWN.WN_FILIAL = '  ' AND SWN.WN_DOC = D1.D1_DOC AND SWN.WN_SERIE = D1.D1_SERIE 
   AND SWN.WN_FORNECE = D1.D1_FORNECE AND SWN.WN_LOJA = D1.D1_LOJA AND SWN.WN_PRODUTO = D1.D1_COD
   AND SWN.WN_PO_NUM = D1.D1_PEDIDO AND cast(SWN.WN_LINHA as integer) = cast(D1.D1_ITEM as integer)   
   AND SWN.D_E_L_E_T_= ' '
  LEFT JOIN SF1010 SF1 ON SF1.F1_FILIAL = D1.D1_FILIAL AND SF1.F1_DOC = D1.D1_DOC AND SF1.F1_SERIE = D1.D1_SERIE 
   AND SF1.F1_FORNECE = D1.D1_FORNECE AND SF1.F1_LOJA = D1.D1_LOJA AND SF1.D_E_L_E_T_ = ' '
 WHERE D1_FILIAL = '01' AND F4.F4_FILIAL = '01' AND D1.D1_TIPO <> 'D'
   AND D1.D1_DTDIGIT  >='20110106' AND D1.D1_DTDIGIT  <='20110106'
   AND D1.D_E_L_E_T_ = ' '   
 GROUP BY D1.D1_DTDIGIT
 ORDER BY D1.D1_DTDIGIT;

-- AND D1.D1_DTDIGIT  >='20110101' AND D1.D1_DTDIGIT  <='20110831' 

-- Query totalizando custo
SELECT (
       case when not SWN.WN_DOC is null 
            then (D1.D1_TOTAL + D1.D1_VALIPI + SWN.WN_DESPICM + SWN.WN_OUT_DES + SWN.WN_VL_ICM + SWN.WN_VLRPIS + SWN.WN_VLRCOF)
            else D1.D1_CUSTO - case when SF1.F1_EST = 'EX' then ((D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6)) else 0 end end +
       CASE WHEN SWN.WN_FILIAL IS NULL THEN D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6 ELSE 0 END) * 
                 case when D1.D1_TIPO = 'D' then -1 else 1 end as CUSTO,
       CASE WHEN NOT SWN.WN_FILIAL IS NULL 
            THEN SWN.WN_OUT_DES+SWN.WN_VL_ICM+SWN.WN_VLRPIS+SWN.WN_VLRCOF+SWN.WN_VALIPI
             ELSE D1.D1_VALIPI+D1.D1_VALICM+D1.D1_VALIMP5+D1.D1_VALIMP6 END AS OUTROS,
       D1.*
  FROM SD1010 D1
  JOIN SF4010 F4 ON F4.F4_CODIGO = D1.D1_TES AND (F4.F4_DUPLIC ='S' OR F4.F4_ESTOQUE= 'S' OR D1.D1_TIPO_NF <>'') AND F4.D_E_L_E_T_=' '
  LEFT JOIN SWN010 SWN ON SWN.WN_FILIAL = '  ' AND SWN.WN_DOC = D1.D1_DOC AND SWN.WN_SERIE = D1.D1_SERIE 
   AND SWN.WN_FORNECE = D1.D1_FORNECE AND SWN.WN_LOJA = D1.D1_LOJA AND SWN.WN_PRODUTO = D1.D1_COD
   AND SWN.WN_PO_NUM = D1.D1_PEDIDO AND cast(SWN.WN_LINHA as integer) = cast(D1.D1_ITEM as integer)   
   AND SWN.D_E_L_E_T_= ' '
  LEFT JOIN SF1010 SF1 ON SF1.F1_FILIAL = D1.D1_FILIAL AND SF1.F1_DOC = D1.D1_DOC AND SF1.F1_SERIE = D1.D1_SERIE 
   AND SF1.F1_FORNECE = D1.D1_FORNECE AND SF1.F1_LOJA = D1.D1_LOJA AND SF1.D_E_L_E_T_ = ' '
 WHERE D1_FILIAL = '01' AND F4.F4_FILIAL = '01' AND D1.D1_TIPO <> 'D'
   AND D1.D1_DTDIGIT = '20110104' AND D1.D1_DTDIGIT = '20110104' 
   AND D1.D_E_L_E_T_ = ' ';
 
// Custo Total
dBselectarea("SW9")
dBsetOrder(3)
dBseek(xFilial("SW9")+TMP->D1_CONHEC)

dBselectarea("SWN")
dBsetOrder(4)
IF dBseek(xFilial("SWN") + TMP->(D1_DOC + D1_SERIE + D1_FORNECE + D1_LOJA + D1_COD + D1_PEDIDO), .T.)
	WHILE !Eof() .AND. SWN->(WN_FILIAL + WN_DOC + WN_SERIE + WN_FORNECE + WN_LOJA + WN_PRODUTO + WN_PO_NUM) == ;
			xFilial("SWN") + TMP->(D1_DOC + D1_SERIE + D1_FORNECE + D1_LOJA + D1_COD + D1_PEDIDO) .AND. SWN->WN_LINHA # Val(TMP->D1_ITEM)

		DbSkip()
	ENDDO
	IF SWN->WN_LINHA == Val(TMP->D1_ITEM)
		_nRet	:= TMP->(D1_TOTAL + D1_VALIPI) + SWN->(WN_DESPICM + WN_OUT_DES + WN_VL_ICM + WN_VLRPIS + WN_VLRCOF) * IIF(TMP->D1_TIPO = "D", -1, 1)
	ENDIF
Else
	_nRet	:= Val(U_VALORFB2()) + Val(U_ValOt2())
Endif

// Fob
User Function ValorFb2() // Pegar o Valor FOB
Local aArea	:= GetArea()
Local _cRet	:= "                0.00"

dBselectarea("SF1")
dBsetorder(1)
dBseek(TMP->(D1_FILIAL+D1_DOC+D1_SERIE+D1_FORNECE+D1_LOJA),.T.)

IF  SF1->F1_EST="EX"
	dBselectarea("SW9")
	dBsetOrder(3)
	dBseek(xFilial("SW9")+TMP->D1_CONHEC)

	dBselectarea("SWN")
	dBsetOrder(4)
//	IF dBseek(xFilial("SWN")+TMP->(D1_DOC+D1_SERIE+D1_FORNECE+D1_LOJA+D1_COD+D1_PEDIDO),.T.)
	IF DbSeek(xFilial("SWN") + TMP->(D1_DOC + D1_SERIE + D1_FORNECE + D1_LOJA + D1_COD + D1_PEDIDO), .T.)
		WHILE !Eof() .AND. SWN->(WN_FILIAL + WN_DOC + WN_SERIE + WN_FORNECE + WN_LOJA + WN_PRODUTO + WN_PO_NUM) == ;
				xFilial("SWN") + TMP->(D1_DOC + D1_SERIE + D1_FORNECE + D1_LOJA + D1_COD + D1_PEDIDO) .AND. SWN->WN_LINHA # Val(TMP->D1_ITEM)

			DbSkip()
		ENDDO
		IF SWN->WN_LINHA == Val(TMP->D1_ITEM)
			_cRet	:= (STR(((SWN->WN_FOB_R+SWN->WN_DESPICM+SWN->WN_DESPADU)*IIF(TMP->D1_TIPO="D",-1,1)),20,2))
		ENDIF
	Else
		// Para produtos nacionais
		_cRet	:= STR((TMP->D1_CUSTO-(TMP->D1_VALIPI+TMP->D1_VALICM+TMP->D1_VALIMP5+TMP->D1_VALIMP6))*IIF(TMP->D1_TIPO="D",-1,1),20,2)
	Endif
Else
	_cRet:=STR((TMP->D1_CUSTO)*IIF(TMP->D1_TIPO="D",-1,1),20,2)
Endif

_cRet:=transform (_cRet,"99999999999999999.99",20,2)

RestArea(aArea)
Return _cRet

// Outros
dBselectarea("SW9")
dBsetOrder(3)
dBseek(xFilial("SW9")+TMP->D1_CONHEC)

dBselectarea("SWN")
dBsetOrder(4)
IF dBseek(xFilial("SWN")+TMP->(D1_DOC+D1_SERIE+D1_FORNECE+D1_LOJA+D1_COD+D1_PEDIDO),.T.)
	WHILE !Eof() .AND. SWN->(WN_FILIAL + WN_DOC + WN_SERIE + WN_FORNECE + WN_LOJA + WN_PRODUTO + WN_PO_NUM) == ;
			xFilial("SWN") + TMP->(D1_DOC + D1_SERIE + D1_FORNECE + D1_LOJA + D1_COD + D1_PEDIDO) .AND. SWN->WN_LINHA # Val(TMP->D1_ITEM)

		DbSkip()
	ENDDO
	IF SWN->WN_LINHA == Val(TMP->D1_ITEM)
		_cRet:=(STR(((SWN->WN_OUT_DES+SWN->WN_VL_ICM+SWN->WN_VLRPIS+SWN->WN_VLRCOF+SWN->WN_VALIPI)*IIF(TMP->D1_TIPO="D",-1,1)),20,2)) //Retirado o campo WN_DESPICM, conforme solicitacao da Srta Luciana
	ENDIF
Else
	// Produto nacional
	_cRet:=STR((TMP->D1_VALIPI+TMP->D1_VALICM+TMP->D1_VALIMP5+TMP->D1_VALIMP6)*IIF(TMP->D1_TIPO="D",-1,1),20,2)
Endif

-- Compras
SELECT * FROM SD2010 D2 , SF4010 F4 WHERE D2_FILIAL = '01' AND F4_FILIAL = '01' AND D2_TES = F4_CODIGO AND F4_XTESPAE = '1' 
   AND D2_EMISSAO >='20110101' AND D2_EMISSAO <='20110831' AND D2_CUSTO1 > 0 AND D2_TIPO <> 'D' AND D2.D_E_L_E_T_=' ' 
   AND F4.D_E_L_E_T_=' ' 