-- Copia dos apontamentos a serem encerrados
SELECT (SELECT MIN(AFU.AFU_HORAI) FROM AFU010 AFU 
         WHERE AFU.D_E_L_E_T_ = ' ' AND AFU_RECURS = AFU010.AFU_RECURS AND AFU_DATA = AFU010.AFU_DATA
           AND AFU_HORAI > AFU010.AFU_HORAI) AS PROXIMO, * 
  INTO AFU010_ENC           
  FROM AFU010
 WHERE D_E_L_E_T_ = ' ' AND AFU_HORAF = ''
ORDER BY AFU_RECURS, AFU_DATA, AFU_HORAI;

UPDATE AFU010
   SET AFU_HORAF = AFU010_ENC.AFU_HORAF, AFU_HQUANT = AFU010_ENC.AFU_HQUANT
  FROM AFU010_ENC
 WHERE AFU010_ENC.R_E_C_N_O_ = AFU010.R_E_C_N_O_;

-- Encerramento anterior as 12:00
SELECT (SELECT MIN(AFU.AFU_HORAI) FROM AFU010 AFU 
         WHERE AFU.D_E_L_E_T_ = ' ' AND AFU_RECURS = AFU010.AFU_RECURS AND AFU_DATA = AFU010.AFU_DATA
           AND AFU_HORAI > AFU010.AFU_HORAI AND AFU_HORAI < '13:00') AS PROXIMO,
        * 
  FROM AFU010
 WHERE D_E_L_E_T_ = ' ' AND AFU_HORAF = '' AND AFU_HORAI < '13:00'
ORDER BY AFU_RECURS, AFU_DATA, AFU_HORAI;

-- Encerramento
UPDATE AFU010   
   SET AFU_HORAF = COALESCE((SELECT MIN(AFU.AFU_HORAI) FROM AFU010 AFU 
                              WHERE AFU.D_E_L_E_T_ = ' ' AND AFU_RECURS = AFU010.AFU_RECURS 
                                AND AFU_DATA = AFU010.AFU_DATA
                                AND AFU_HORAI > AFU010.AFU_HORAI AND AFU_HORAI < '13:00'), '12:00'), 
       AFU_HQUANT = dbo.dt_difhora(AFU_HORAI, COALESCE((SELECT MIN(AFU.AFU_HORAI) FROM AFU010 AFU 
                                                         WHERE AFU.D_E_L_E_T_ = ' ' AND AFU_RECURS = AFU010.AFU_RECURS 
                                                         AND AFU_DATA = AFU010.AFU_DATA
                                                         AND AFU_HORAI > AFU010.AFU_HORAI AND AFU_HORAI < '13:00'), '12:00')), 
       AFU_XTIPO = 'S'
 WHERE D_E_L_E_T_ = ' ' AND AFU_HORAF = '' AND AFU_HORAI < '13:00';

-- Encerramento superior as 13:00
SELECT (SELECT MIN(AFU.AFU_HORAI) FROM AFU010 AFU 
         WHERE AFU.D_E_L_E_T_ = ' ' AND AFU_RECURS = AFU010.AFU_RECURS AND AFU_DATA = AFU010.AFU_DATA
           AND AFU_HORAI > AFU010.AFU_HORAI) AS PROXIMO, dbo.dt_difhora(AFU_HORAI, '18:00') AS AFU_HQUANT, * 
  FROM AFU010
 WHERE D_E_L_E_T_ = ' ' AND AFU_HORAF = '' AND AFU_DATA < '20120413' AND AFU_HORAI >= '13:00' 
ORDER BY AFU_RECURS, AFU_DATA, AFU_HORAI;

-- Encerramento
UPDATE AFU010   
   SET AFU_HORAF = '18:00', AFU_HQUANT = dbo.dt_difhora(AFU_HORAI, '18:00'), AFU_XTIPO = 'S'
 WHERE D_E_L_E_T_ = ' ' AND AFU_HORAF = '' AND AFU_DATA < '20120413' AND AFU_HORAI >= '13:00';