-- Projetos por SC
select * from AFG010 order by AFG_PROJET, AFG_NUMSC;

-- Despesas por Projetos
select * from AFR010 order by AFR_PROJET, AFR_NUM;

-- Geração do pedido
select C5_NUM, C5_CODPED, C5_CLIENTE
  from ;

-- Visão despesas por projeto
select AFG.AFG_PROJET AS C5_XPROJET, AF9.AF9_EDTPAI AS C5_XTSKPMS, 
       AF8.AF8_CLIENT AS C5_CLIENTE, AF8.AF8_LOJA AS C5_LOJA, SA1.A1_NOME,
       SD1.D1_EMISSAO AS EMISSAO, SD1.D1_DOC AS DOCTO, SC7.C7_OBS AS DETALHE,
       'S/N' as C5_CODPED, 'N' as C5_TIPO, '2' AS C5_XDEPART, 
       SC7.C7_PRODUTO AS C6_PRODUTO, '001' AS C6_TES, SUM(SD1.D1_QUANT) AS C6_QTDVEN, 
       ROUND(SUM(SD1.D1_TOTAL / SD1.D1_QUANT), 2) AS C6_PRCVEN, SUM(SD1.D1_TOTAL) AS C6_TOTAL
  from AFG010 AFG
  JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFG.AFG_FILIAL AND AF8.D_E_L_E_T_ = ' ' 
   AND AF8.AF8_PROJET = AFG.AFG_PROJET AND AF8.AF8_XDESP = '2'
  JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT
   AND SA1.A1_LOJA = AF8.AF8_LOJA
  JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFG.AFG_FILIAL AND AF9.D_E_L_E_T_ = ' ' 
   AND AF9.AF9_PROJET = AFG.AFG_PROJET AND AF9.AF9_REVISA = AFG.AFG_REVISA 
   AND AF9.AF9_TAREFA = AFG.AFG_TAREFA
  JOIN SC7010 SC7 ON SC7.C7_FILIAL = AFG.AFG_FILIAL AND SC7.D_E_L_E_T_ = ' ' 
   AND SC7.C7_NUMSC = AFG.AFG_NUMSC AND SC7.C7_ITEMSC = AFG.AFG_ITEMSC 
  JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFG.AFG_FILIAL AND SD1.D_E_L_E_T_ = ' ' 
   AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_ITEMPC = SC7.C7_ITEM
 WHERE AFG.AFG_FILIAL = '01' AND AFG.D_E_L_E_T_ = ' '
 GROUP BY AFG.AFG_PROJET, AF9.AF9_EDTPAI, AF8.AF8_CLIENT, AF8.AF8_LOJA, SA1.A1_NOME, 
          SD1.D1_EMISSAO, SD1.D1_DOC, SC7.C7_OBS, SC7.C7_PRODUTO
 UNION ALL
select AFR.AFR_PROJET AS C5_XPROJET, AF9.AF9_EDTPAI AS C5_XTSKPMS, 
       AF8.AF8_CLIENT AS C5_CLIENTE, AF8.AF8_LOJA AS C5_LOJA, SA1.A1_NOME,
       SE2.E2_EMISSAO AS EMISSAO, AFR.AFR_NUM AS DOCTO, LTRIM(RTRIM(SZ8.Z8_DESCRI)) + ' [' + LTRIM(RTRIM(SA2.A2_NOME)) + ']' AS DETALHE,
       'S/N' as C5_CODPED, 'N' as C5_TIPO, 
       '2' AS C5_XDEPART, SZ8.Z8_PRODUTO AS C6_PRODUTO, '001' AS C6_TES, 1 AS C6_QTDVEN, 
       SUM(CASE WHEN AFR.AFR_XVAL_C = 0 THEN AFR.AFR_VALOR1 ELSE AFR.AFR_XVAL_C END) AS C6_PRCVEN, 
       SUM(CASE WHEN AFR.AFR_XVAL_C = 0 THEN AFR.AFR_VALOR1 ELSE AFR.AFR_XVAL_C END) AS C6_TOTAL
  from AFR010 AFR
  JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFR.AFR_FILIAL AND AF8.D_E_L_E_T_ = ' ' 
   AND AF8.AF8_PROJET = AFR.AFR_PROJET AND AF8.AF8_XDESP = '2'
  JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT
   AND SA1.A1_LOJA = AF8.AF8_LOJA
  JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFR.AFR_FILIAL AND AF9.D_E_L_E_T_ = ' ' 
   AND AF9.AF9_PROJET = AFR.AFR_PROJET AND AF9.AF9_REVISA = AFR.AFR_REVISA 
   AND AF9.AF9_TAREFA = AFR.AFR_TAREFA
  JOIN SZ8010 SZ8 ON SZ8.Z8_FILIAL = '  ' AND SZ8.D_E_L_E_T_ = ' ' AND SZ8.Z8_DESPESA = AFR.AFR_TIPOD
  JOIN SE2010 SE2 ON SE2.E2_FILIAL = AFR.AFR_FILIAL AND SE2.D_E_L_E_T_ = ' ' 
   AND SE2.E2_PREFIXO = AFR.AFR_PREFIX AND SE2.E2_NUM = AFR.AFR_NUM AND SE2.E2_NUM = AFR.AFR_NUM
   AND SE2.E2_EMISSAO BETWEEN '20120101' AND '20123104'
  JOIN SA2010 SA2 ON SA2.A2_FILIAL = '  ' AND SA2.D_E_L_E_T_ = ' ' AND SA2.A2_COD = SE2.E2_FORNECE 
   AND SA2.A2_LOJA = SE2.E2_LOJA
 WHERE AFR.AFR_FILIAL = '01' AND AFR.D_E_L_E_T_ = ' '
 GROUP BY AFR.AFR_PROJET, AF9.AF9_EDTPAI, AF8.AF8_CLIENT, AF8.AF8_LOJA, SA1.A1_NOME, 
          SE2.E2_EMISSAO, AFR.AFR_NUM, SA2.A2_NOME, SZ8.Z8_PRODUTO, SZ8.Z8_DESCRI;

-- AND AFG.AFG_PROJET = 'PMS006311A' 
-- Projeto
SELECT TOP 1 AF8_CLIENT, AF8_LOJA, * FROM AF8010;
-- EDT
SELECT TOP 1 * FROM AFC010;
-- Tarefa
SELECT TOP 1 AF9_EDTPAI, * FROM AF9010;
-- SC por Projeto
SELECT TOP 1 * FROM AFG010 ORDER BY R_E_C_N_O_ DESC;
-- Despesas por Projeto
SELECT TOP 1 * FROM AFR010;

-- Pedido de Compras
SELECT C7_NUMSC, C7_ITEMSC, C7_EMISSAO, C7_NUM, * FROM SC7010 
 WHERE D_E_L_E_T_ = ' ' AND C7_NUMSC = '010759'
 
-- Notas de Compras
SELECT D1_PEDIDO, D1_ITEMPC, D1_DTDIGIT, * FROM SD1010 
 WHERE D_E_L_E_T_ = ' ' AND D1_PEDIDO = '009760'
 
-- Solicitações
SELECT TOP 1 * FROM SC1010;

SELECT * FROM AF8010;

-- Geração do lote para reembolso
select Z9_PROJETO, Z9_REVISA, Z9_CLIENTE, 
       SUM(CASE WHEN TIPO = 1 THEN C6_TOTAL ELSE 0 END) AS D1_TOTAL, 
       SUM(CASE WHEN TIPO = 2 THEN C6_TOTAL ELSE 0 END) AS AFR_XVAL_C 
  from (select 1 as TIPO, AFG.AFG_PROJET AS Z9_PROJETO, AFG.AFG_REVISA AS Z9_REVISA, 
               AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, 
               SUM(CASE WHEN AFG.AFG_XCOB = '2' 
                        THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END) AS C6_TOTAL   
          from AFG010 AFG   
          JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFG.AFG_FILIAL AND AF8.D_E_L_E_T_ = ' '    
           AND AF8.AF8_PROJET = AFG.AFG_PROJET AND AF8.AF8_XDESP = '2'   
          JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFG.AFG_FILIAL AND AF9.D_E_L_E_T_ = ' '    
           AND AF9.AF9_PROJET = AFG.AFG_PROJET AND AF9.AF9_REVISA = AFG.AFG_REVISA    
           AND AF9.AF9_TAREFA = AFG.AFG_TAREFA   
          JOIN SC7010 SC7 ON SC7.C7_FILIAL = AFG.AFG_FILIAL AND SC7.D_E_L_E_T_ = ' '    
           AND SC7.C7_NUMSC = AFG.AFG_NUMSC AND SC7.C7_ITEMSC = AFG.AFG_ITEMSC   
          JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFG.AFG_FILIAL AND SD1.D_E_L_E_T_ = ' '    
           AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_ITEMPC = SC7.C7_ITEM 
           AND SD1.D1_EMISSAO BETWEEN '20120401' AND '20120417'  
         WHERE AFG.AFG_FILIAL = '01' AND AFG.D_E_L_E_T_ = ' ' 
         --AND CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END > 0 
         --AND AFG.AFG_XDESP = ''  
         GROUP BY AFG.AFG_PROJET, AFG.AFG_REVISA, AF8.AF8_CLIENT, AF8.AF8_LOJA  
         UNION ALL 
        select 2 as TIPO, AFR.AFR_PROJET AS Z9_PROJETO, AFR.AFR_REVISA AS Z9_REVISA, 
               AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, 
               SUM(AFR.AFR_XVAL_C) AS C6_TOTAL   
          from AFR010 AFR   
          JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFR.AFR_FILIAL AND AF8.D_E_L_E_T_ = ' '    
           AND AF8.AF8_PROJET = AFR.AFR_PROJET AND AF8.AF8_XDESP = '2'   
          JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT 
           AND SA1.A1_LOJA = AF8.AF8_LOJA   JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFR.AFR_FILIAL 
           AND AF9.D_E_L_E_T_ = ' '    AND AF9.AF9_PROJET = AFR.AFR_PROJET AND AF9.AF9_REVISA = AFR.AFR_REVISA 
           AND AF9.AF9_TAREFA = AFR.AFR_TAREFA   
          JOIN SE2010 SE2 ON SE2.E2_FILIAL = AFR.AFR_FILIAL AND SE2.D_E_L_E_T_ = ' '    
           AND SE2.E2_PREFIXO = AFR.AFR_PREFIX AND SE2.E2_NUM = AFR.AFR_NUM AND SE2.E2_TIPO = AFR.AFR_TIPO 
           AND SE2.E2_PARCELA = AFR.AFR_PARCEL AND SE2.E2_EMISSAO BETWEEN '20120401' AND '20120417'  
         WHERE AFR.AFR_FILIAL = '01' AND AFR.D_E_L_E_T_ = ' ' AND AFR.AFR_XVAL_C > 0 AND AFR.AFR_XDESP = '' 
         GROUP BY AFR.AFR_PROJET, AFR.AFR_REVISA, AF8.AF8_CLIENT, AF8.AF8_LOJA ) SZ9 
 GROUP BY Z9_CLIENTE, Z9_LOJA, Z9_PROJETO, Z9_REVISA 
 ORDER BY Z9_CLIENTE, Z9_LOJA, Z9_PROJETO, Z9_REVISA;

SELECT * FROM SZ9010;
DELETE FROM SZ9010;

-- SC
SELECT * FROM SD1010 WHERE AFG_XDESP <> '';

SELECT * FROM AFR010 WHERE AFR_XDESP <> '';

select Z9_PROJETO, Z9_REVISA, Z9_CLIENTE, SUM(CASE WHEN TIPO = 1 THEN C6_TOTAL ELSE 0 END) AS D1_TOTAL, SUM(CASE WHEN TIPO = 2 THEN C6_TOTAL ELSE 0 END) AS AFR_XVAL_C from (select 1 as TIPO, AFG.AFG_PROJET AS Z9_PROJETO, AFG.AFG_REVISA AS Z9_REVISA, AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, SUM(CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END) AS C6_TOTAL from AFG010 AFG JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFG.AFG_FILIAL AND AF8.D_E_L_E_T_ = ' ' AND AF8.AF8_PROJET = AFG.AFG_PROJET AND AF8.AF8_XDESP = '2' AND AF8.AF8_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND AF8.AF8_CLIENT BETWEEN '      ' AND 'ZZZZZZ' AND AF8.AF8_LOJA BETWEEN '  ' AND 'ZZ' JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFG.AFG_FILIAL AND AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_PROJET = AFG.AFG_PROJET AND AF9.AF9_REVISA = AFG.AFG_REVISA AND AF9.AF9_TAREFA = AFG.AFG_TAREFA JOIN SC7010 SC7 ON SC7.C7_FILIAL = AFG.AFG_FILIAL AND SC7.D_E_L_E_T_ = ' ' AND SC7.C7_NUMSC = AFG.AFG_NUMSC AND SC7.C7_ITEMSC = AFG.AFG_ITEMSC JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFG.AFG_FILIAL AND SD1.D_E_L_E_T_ = ' ' AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_ITEMPC = SC7.C7_ITEM AND SD1.D1_EMISSAO BETWEEN '20120101' AND '20120418' WHERE AFG.AFG_FILIAL = '01' AND AFG.D_E_L_E_T_ = ' ' AND AFG.AFG_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END > 0 AND AFG.AFG_XDESP = '' GROUP BY AFG.AFG_PROJET, AFG.AFG_REVISA, AF8.AF8_CLIENT, AF8.AF8_LOJA UNION ALL select 2 as TIPO, AFR.AFR_PROJET AS Z9_PROJETO, AFR.AFR_REVISA AS Z9_REVISA, AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, SUM(AFR.AFR_XVAL_C) AS C6_TOTAL from AFR010 AFR JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFR.AFR_FILIAL AND AF8.D_E_L_E_T_ = ' ' AND AF8.AF8_PROJET = AFR.AFR_PROJET AND AF8.AF8_XDESP = '2' AND AF8.AF8_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND AF8.AF8_CLIENT BETWEEN '      ' AND 'ZZZZZZ' AND AF8.AF8_LOJA BETWEEN '  ' AND 'ZZ' JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT AND SA1.A1_LOJA = AF8.AF8_LOJA JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFR.AFR_FILIAL AND AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_PROJET = AFR.AFR_PROJET AND AF9.AF9_REVISA = AFR.AFR_REVISA AND AF9.AF9_TAREFA = AFR.AFR_TAREFA JOIN SE2010 SE2 ON SE2.E2_FILIAL = AFR.AFR_FILIAL AND SE2.D_E_L_E_T_ = ' ' AND SE2.E2_PREFIXO = AFR.AFR_PREFIX AND SE2.E2_NUM = AFR.AFR_NUM AND SE2.E2_TIPO = AFR.AFR_TIPO AND SE2.E2_PARCELA = AFR.AFR_PARCEL AND SE2.E2_EMISSAO BETWEEN '20120101' AND '20120418' WHERE AFR.AFR_FILIAL = '01' AND AFR.D_E_L_E_T_ = ' ' AND AFR.AFR_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND AFR.AFR_XVAL_C > 0 AND AFR.AFR_XDESP = '' GROUP BY AFR.AFR_PROJET, AFR.AFR_REVISA, AF8.AF8_CLIENT, AF8.AF8_LOJA ) SZ9 GROUP BY Z9_CLIENTE, Z9_LOJA, Z9_PROJETO, Z9_REVISA ORDER BY Z9_CLIENTE, Z9_LOJA, Z9_PROJETO, Z9_REVISA;

SELECT * FROM AFR010;

UPDATE AFR010 
   SET AFR_XDESP = '000008' 
  FROM AF8010 AF8 
  JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFR010.AFR_FILIAL AND AF9.D_E_L_E_T_ = ' ' 
   AND AF9.AF9_PROJET = AFR010.AFR_PROJET AND AF9.AF9_REVISA = AFR010.AFR_REVISA 
   AND AF9.AF9_TAREFA = AFR010.AFR_TAREFA JOIN SE2010 SE2 ON SE2.E2_FILIAL = AFR010.AFR_FILIAL 
   AND SE2.D_E_L_E_T_ = ' ' AND SE2.E2_PREFIXO = AFR010.AFR_PREFIX AND SE2.E2_NUM = AFR010.AFR_NUM 
   AND SE2.E2_TIPO = AFR010.AFR_TIPO AND SE2.E2_PARCELA = AFR010.AFR_PARCEL 
   AND SE2.E2_EMISSAO BETWEEN '20120101' AND '20120418' 
 WHERE AFR010.AFR_FILIAL = '01' AND AFR010.D_E_L_E_T_ = ' ' AND AFR010.AFR_XVAL_C > 0 
   AND AFR010.AFR_XDESP = '' AND AF8.AF8_FILIAL = AFR010.AFR_FILIAL AND AF8.D_E_L_E_T_ = ' ' 
   AND AF8.AF8_PROJET = AFR010.AFR_PROJET AND AF8.AF8_XDESP = '2';
   
select Z9_PROJETO, Z9_REVISA, Z9_CLIENTE, 
       SUM(CASE WHEN TIPO = 1 THEN C6_TOTAL ELSE 0 END) AS D1_TOTAL, 
       SUM(CASE WHEN TIPO = 2 THEN C6_TOTAL ELSE 0 END) AS AFR_XVAL_C 
  from (select 1 as TIPO, AFG.AFG_PROJET AS Z9_PROJETO, AFG.AFG_REVISA AS Z9_REVISA, 
               AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, 
               CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END AS C6_TOTAL, 
               AFG.R_E_C_N_O_ AS RECNO 
          from AFG010 AFG 
          JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFG.AFG_FILIAL AND AF8.D_E_L_E_T_ = ' ' 
           AND AF8.AF8_PROJET = AFG.AFG_PROJET AND AF8.AF8_XDESP = '2' 
           AND AF8.AF8_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' 
           AND AF8.AF8_CLIENT BETWEEN '      ' AND 'ZZZZZZ' AND AF8.AF8_LOJA BETWEEN '  ' AND 'ZZ' 
          JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFG.AFG_FILIAL AND AF9.D_E_L_E_T_ = ' ' 
           AND AF9.AF9_PROJET = AFG.AFG_PROJET AND AF9.AF9_REVISA = AFG.AFG_REVISA AND AF9.AF9_TAREFA = AFG.AFG_TAREFA 
          JOIN SC7010 SC7 ON SC7.C7_FILIAL = AFG.AFG_FILIAL AND SC7.D_E_L_E_T_ = ' ' AND SC7.C7_NUMSC = AFG.AFG_NUMSC 
           AND SC7.C7_ITEMSC = AFG.AFG_ITEMSC JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFG.AFG_FILIAL 
           AND SD1.D_E_L_E_T_ = ' ' AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_ITEMPC = SC7.C7_ITEM 
           AND SD1.D1_EMISSAO BETWEEN '20120101' AND '20120418' 
         WHERE AFG.AFG_FILIAL = '01' AND AFG.D_E_L_E_T_ = ' ' 
           AND AFG.AFG_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' 
           AND CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END > 0 
           AND AFG.AFG_XDESP = '' AND AF8.AF8_CLIENT <> '' AND AF8.AF8_LOJA <> '' 
         UNION ALL 
        select 2 as TIPO, AFR.AFR_PROJET AS Z9_PROJETO, AFR.AFR_REVISA AS Z9_REVISA, 
               AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, AFR.AFR_XVAL_C AS C6_TOTAL, 
               AFR.R_E_C_N_O_ AS RECNO 
          from AFR010 AFR 
          JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFR.AFR_FILIAL AND AF8.D_E_L_E_T_ = ' ' 
           AND AF8.AF8_PROJET = AFR.AFR_PROJET AND AF8.AF8_XDESP = '2' 
           AND AF8.AF8_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' 
           AND AF8.AF8_CLIENT BETWEEN '      ' AND 'ZZZZZZ' AND AF8.AF8_LOJA BETWEEN '  ' AND 'ZZ' 
          JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT 
           AND SA1.A1_LOJA = AF8.AF8_LOJA JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFR.AFR_FILIAL 
           AND AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_PROJET = AFR.AFR_PROJET AND AF9.AF9_REVISA = AFR.AFR_REVISA 
           AND AF9.AF9_TAREFA = AFR.AFR_TAREFA JOIN SE2010 SE2 ON SE2.E2_FILIAL = AFR.AFR_FILIAL 
           AND SE2.D_E_L_E_T_ = ' ' AND SE2.E2_PREFIXO = AFR.AFR_PREFIX AND SE2.E2_NUM = AFR.AFR_NUM 
           AND SE2.E2_TIPO = AFR.AFR_TIPO AND SE2.E2_PARCELA = AFR.AFR_PARCEL 
           AND SE2.E2_EMISSAO BETWEEN '20120101' AND '20120418' 
         WHERE AFR.AFR_FILIAL = '01' AND AFR.D_E_L_E_T_ = ' ' 
           AND AFR.AFR_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND AFR.AFR_XVAL_C > 0 
           AND AFR.AFR_XDESP = '' AND AF8.AF8_CLIENT <> '' AND AF8.AF8_LOJA <> '') SZ9 
 GROUP BY Z9_CLIENTE, Z9_LOJA, Z9_PROJETO, Z9_REVISA 
 ORDER BY Z9_CLIENTE, Z9_LOJA, Z9_PROJETO, Z9_REVISA
           
-- Limpa a geração
SELECT * FROM SD1010 WHERE D_E_L_E_T_ = ' ' AND D1_XDESP <> '';
UPDATE SD1010 SET D1_XDESP = ''  WHERE D1_XDESP <> '';

SELECT * FROM AFR010 WHERE D_E_L_E_T_ = ' ' AND AFR_XDESP <> '';
UPDATE AFR010 SET AFR_XDESP = '' WHERE AFR_XDESP <> '';

DELETE FROM SZ9010;

UPDATE AFG010 SET AFG_XDESP = '000035' 
  FROM (select 1 as TIPO, AFG.AFG_PROJET AS Z9_PROJETO, AFG.AFG_REVISA AS Z9_REVISA, AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END AS C6_TOTAL, AFG.R_E_C_N_O_ AS RECNO from AFG010 AFG JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFG.AFG_FILIAL AND AF8.D_E_L_E_T_ = ' ' AND AF8.AF8_PROJET = AFG.AFG_PROJET AND AF8.AF8_XDESP = '2' AND AF8.AF8_PROJET BETWEEN 'PMS003211A' AND 'PMS003211A' AND AF8.AF8_CLIENT BETWEEN '005391' AND '005391' AND AF8.AF8_LOJA BETWEEN '01' AND '01' JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFG.AFG_FILIAL AND AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_PROJET = AFG.AFG_PROJET AND AF9.AF9_REVISA = AFG.AFG_REVISA AND AF9.AF9_TAREFA = AFG.AFG_TAREFA JOIN SC7010 SC7 ON SC7.C7_FILIAL = AFG.AFG_FILIAL AND SC7.D_E_L_E_T_ = ' ' AND SC7.C7_NUMSC = AFG.AFG_NUMSC AND SC7.C7_ITEMSC = AFG.AFG_ITEMSC JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFG.AFG_FILIAL AND SD1.D_E_L_E_T_ = ' ' AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_ITEMPC = SC7.C7_ITEM AND SD1.D1_EMISSAO BETWEEN '20120101' AND '20120418' WHERE AFG.AFG_FILIAL = '01' AND AFG.D_E_L_E_T_ = ' ' AND AFG.AFG_PROJET BETWEEN 'PMS003211A' AND 'PMS003211A' AND CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END > 0 AND AFG.AFG_XDESP = '' AND AF8.AF8_CLIENT <> '' AND AF8.AF8_LOJA <> '' UNION ALL ) SZ9 
 WHERE AFG010.R_E_C_N_O_ = SZ9.RECNO;
 
select SD1.D1_XDESP, 1 as TIPO, AFG.AFG_PROJET AS Z9_PROJETO, AFG.AFG_REVISA AS Z9_REVISA, AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END AS C6_TOTAL, SD1.R_E_C_N_O_ AS RECNO 
  from AFG010 AFG JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFG.AFG_FILIAL AND AF8.D_E_L_E_T_ = ' ' AND AF8.AF8_PROJET = AFG.AFG_PROJET AND AF8.AF8_XDESP = '2' AND AF8.AF8_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND AF8.AF8_CLIENT + AF8.AF8_LOJA BETWEEN '        ' AND 'ZZZZZZZZ' JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFG.AFG_FILIAL AND AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_PROJET = AFG.AFG_PROJET AND AF9.AF9_REVISA = AFG.AFG_REVISA AND AF9.AF9_TAREFA = AFG.AFG_TAREFA JOIN SC7010 SC7 ON SC7.C7_FILIAL = AFG.AFG_FILIAL AND SC7.D_E_L_E_T_ = ' ' AND SC7.C7_NUMSC = AFG.AFG_NUMSC AND SC7.C7_ITEMSC = AFG.AFG_ITEMSC JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFG.AFG_FILIAL AND SD1.D_E_L_E_T_ = ' ' AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_ITEMPC = SC7.C7_ITEM AND SD1.D1_EMISSAO BETWEEN '20120101' AND '20120419' WHERE AFG.AFG_FILIAL = '01' AND AFG.D_E_L_E_T_ = ' ' AND AFG.AFG_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END > 0 AND SD1.D1_XDESP = '' AND AF8.AF8_CLIENT <> '' AND AF8.AF8_LOJA <> '' 
 UNION ALL 
select 2 as TIPO, AFR.AFR_PROJET AS Z9_PROJETO, AFR.AFR_REVISA AS Z9_REVISA, AF8.AF8_CLIENT AS Z9_CLIENTE, AF8.AF8_LOJA AS Z9_LOJA, AFR.AFR_XVAL_C AS C6_TOTAL, AFR.R_E_C_N_O_ AS RECNO from AFR010 AFR JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFR.AFR_FILIAL AND AF8.D_E_L_E_T_ = ' ' AND AF8.AF8_PROJET = AFR.AFR_PROJET AND AF8.AF8_XDESP = '2' AND AF8.AF8_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND AF8.AF8_CLIENT + AF8.AF8_LOJA BETWEEN '        ' AND 'ZZZZZZZZ' JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT AND SA1.A1_LOJA = AF8.AF8_LOJA JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFR.AFR_FILIAL AND AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_PROJET = AFR.AFR_PROJET AND AF9.AF9_REVISA = AFR.AFR_REVISA AND AF9.AF9_TAREFA = AFR.AFR_TAREFA JOIN SE2010 SE2 ON SE2.E2_FILIAL = AFR.AFR_FILIAL AND SE2.D_E_L_E_T_ = ' ' AND SE2.E2_PREFIXO = AFR.AFR_PREFIX AND SE2.E2_NUM = AFR.AFR_NUM AND SE2.E2_TIPO = AFR.AFR_TIPO AND SE2.E2_PARCELA = AFR.AFR_PARCEL AND SE2.E2_EMISSAO BETWEEN '20120101' AND '20120419' WHERE AFR.AFR_FILIAL = '01' AND AFR.D_E_L_E_T_ = ' ' AND AFR.AFR_PROJET BETWEEN '          ' AND 'ZZZZZZZZZZ' AND AFR.AFR_XVAL_C > 0 AND AFR.AFR_XDESP = '' AND AF8.AF8_CLIENT <> '' AND AF8.AF8_LOJA <> ''

--
select 1 as TIPO, AFG.AFG_PROJET AS C5_XPROJET, AF8.AF8_CLIENT AS C5_CLIENTE, AF8.AF8_LOJA AS C5_LOJA, 
       SA1.A1_NOME, SD1.D1_EMISSAO AS EMISSAO, SD1.D1_DOC AS DOCTO, SC7.C7_OBS AS DETALHE, 
       SUM(SD1.D1_QUANT) AS C6_QUANTOS, 
       SUM(CASE WHEN SD1.D1_QUANT = 0 THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) / SD1.D1_QUANT END) AS C6_UNITARIO, 
       SUM(SD1.D1_TOTAL) AS C6_TOTAL, 
       SUM(CASE WHEN AFG.AFG_XCOB = '2' THEN 0 ELSE SD1.D1_TOTAL + (SD1.D1_TOTAL * 20 / 100) END) AS C6_COBCLI   
  from AFG010 AFG   
  JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFG.AFG_FILIAL AND AF8.D_E_L_E_T_ = ' '    
   AND AF8.AF8_PROJET = AFG.AFG_PROJET AND AF8.AF8_XDESP = '2' AND AF8.AF8_PROJET BETWEEN '' AND '' AND AF8.AF8_CLIENT + AF8.AF8_LOJA BETWEEN '' AND 'ZZZZZZZZ'   JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT    AND SA1.A1_LOJA = AF8.AF8_LOJA   JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFG.AFG_FILIAL AND AF9.D_E_L_E_T_ = ' '    AND AF9.AF9_PROJET = AFG.AFG_PROJET AND AF9.AF9_REVISA = AFG.AFG_REVISA    AND AF9.AF9_TAREFA = AFG.AFG_TAREFA   JOIN SC7010 SC7 ON SC7.C7_FILIAL = AFG.AFG_FILIAL AND SC7.D_E_L_E_T_ = ' '    AND SC7.C7_NUMSC = AFG.AFG_NUMSC AND SC7.C7_ITEMSC = AFG.AFG_ITEMSC   JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFG.AFG_FILIAL AND SD1.D_E_L_E_T_ = ' '    AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_ITEMPC = SC7.C7_ITEM    AND SD1.D1_EMISSAO BETWEEN '19800101' AND '30001231' AND SD1.D1_XDESP >= '000041'AND SD1.D1_XDESP <= '000041' WHERE AFG.AFG_FILIAL = '01' AND AFG.D_E_L_E_T_ = ' '  GROUP BY AFG.AFG_PROJET, AF8.AF8_CLIENT, AF8.AF8_LOJA, SA1.A1_NOME, SD1.D1_EMISSAO, SD1.D1_DOC, SC7.C7_OBS  UNION ALL select 2 as TIPO, AFR.AFR_PROJET AS C5_XPROJET, AF8.AF8_CLIENT AS C5_CLIENTE, AF8.AF8_LOJA AS C5_LOJA, SA1.A1_NOME, SE2.E2_EMISSAO AS EMISSAO, AFR.AFR_NUM AS DOCTO, COALESCE(LTRIM(RTRIM(SZ8.Z8_DESCRI)) + ' [' + LTRIM(RTRIM(SA2.A2_NOME)) + ']', LTRIM(RTRIM(SA2.A2_NOME))) AS DETALHE, SUM(AFR.AFR_XQTDE) AS C6_QUANTOS, SUM(CASE WHEN AFR.AFR_XQTDE = 0 THEN 0 ELSE AFR.AFR_XVAL_C / AFR.AFR_XQTDE END) AS C6_UNITARIO, SUM(AFR.AFR_VALOR1) AS C6_TOTAL, SUM(AFR.AFR_XVAL_C) AS C6_COBCLI   from AFR010 AFR   LEFT JOIN SZ8010 SZ8 ON SZ8.Z8_FILIAL = '  ' AND SZ8.D_E_L_E_T_ = ' ' AND SZ8.Z8_DESPESA = AFR.AFR_TIPOD   JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFR.AFR_FILIAL AND AF8.D_E_L_E_T_ = ' '    AND AF8.AF8_PROJET = AFR.AFR_PROJET AND AF8.AF8_XDESP = '2' AND AF8.AF8_PROJET BETWEEN '' AND '' AND AF8.AF8_CLIENT + AF8.AF8_LOJA BETWEEN '' AND 'ZZZZZZZZ'   JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT    AND SA1.A1_LOJA = AF8.AF8_LOJA   JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFR.AFR_FILIAL AND AF9.D_E_L_E_T_ = ' '    AND AF9.AF9_PROJET = AFR.AFR_PROJET AND AF9.AF9_REVISA = AFR.AFR_REVISA    AND AF9.AF9_TAREFA = AFR.AFR_TAREFA   JOIN SE2010 SE2 ON SE2.E2_FILIAL = AFR.AFR_FILIAL AND SE2.D_E_L_E_T_ = ' '    AND SE2.E2_PREFIXO = AFR.AFR_PREFIX AND SE2.E2_NUM = AFR.AFR_NUM AND SE2.E2_TIPO = AFR.AFR_TIPO AND SE2.E2_PARCELA = AFR.AFR_PARCEL    AND SE2.E2_EMISSAO BETWEEN '19800101' AND '30001231'   JOIN SA2010 SA2 ON SA2.A2_FILIAL = '  ' AND SA2.D_E_L_E_T_ = ' ' AND SA2.A2_COD = SE2.E2_FORNECE    AND SA2.A2_LOJA = SE2.E2_LOJA  WHERE AFR.AFR_FILIAL = '01' AND AFR.D_E_L_E_T_ = ' ' AND AFR.AFR_XDESP >= '000041'AND AFR.AFR_XDESP <= '000041' GROUP BY AFR.AFR_PROJET, AF8.AF8_CLIENT, AF8.AF8_LOJA, SA1.A1_NOME, SE2.E2_EMISSAO, AFR.AFR_NUM, SA2.A2_NOME, SZ8.Z8_DESCRI  ORDER BY C5_CLIENTE, C5_LOJA, TIPO, C5_XPROJET, DOCTO

-- Despesas   
SELECT * FROM SD1010 WHERE D_E_L_E_T_ = ' ' AND D1_XDESP = '000047';

SELECT * FROM AFR010 WHERE D_E_L_E_T_ = ' ' AND AFR_XDESP = '000047';

SELECT * FROM SZ9010 WHERE Z9_DESPESA = '000047';

-- D_E_L_E_T_ = ' ' AND 
UPDATE AFR010 SET AFR_XDESP = '' WHERE D_E_L_E_T_ = ' ' AND AFR_XDESP = '000047';   

SELECT TOP 1 * FROM SZ8010;
SELECT TOP 1 * FROM AFR010;
SELECT TOP 1 AF9_EDTPAI, * FROM AF9010;

SELECT * FROM SE4010;

-- Geração 
select SZ9.Z9_DESPESA, SZ9.C5_CLIENTE, SZ9.C5_LOJACLI, SZ9.A1_TIPO, SZ9.Z9_CONDPAG, SZ9.C5_XPROJET, 
       SZ9.C5_XTSKPMS, SZ9.C6_PRODUTO, SUM(SZ9.C6_QTDVEN) AS C6_QTDVEN, SUM(SZ9.C6_PRCVEN) AS C6_PRCVEN 
  from (select SZ9.Z9_DESPESA, AF8.AF8_CLIENT AS C5_CLIENTE, AF8.AF8_LOJA AS C5_LOJACLI, 
               AF8.AF8_PROJET AS C5_XPROJET, AF9.AF9_EDTPAI AS C5_XTSKPMS, MIN(SA1.A1_TIPO) AS A1_TIPO, 
               '002' AS Z9_CONDPAG,SD1.D1_COD AS C6_PRODUTO, SUM(SD1.D1_QUANT) AS C6_QTDVEN, 
               SUM(SD1.D1_XVAL_C) AS C6_PRCVEN 
          from AFG010 AFG 
          JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFG.AFG_FILIAL AND AF8.D_E_L_E_T_ = ' ' 
           AND AF8.AF8_PROJET = AFG.AFG_PROJET AND AF8.AF8_XDESP = '2' 
          JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT
           AND SA1.A1_LOJA = AF8.AF8_LOJA
          JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFG.AFG_FILIAL AND AF9.D_E_L_E_T_ = ' ' 
           AND AF9.AF9_PROJET = AFG.AFG_PROJET AND AF9.AF9_REVISA = AFG.AFG_REVISA 
           AND AF9.AF9_TAREFA = AFG.AFG_TAREFA 
          JOIN SC7010 SC7 ON SC7.C7_FILIAL = AFG.AFG_FILIAL AND SC7.D_E_L_E_T_ = ' ' 
           AND SC7.C7_NUMSC = AFG.AFG_NUMSC AND SC7.C7_ITEMSC = AFG.AFG_ITEMSC 
          JOIN SD1010 SD1 ON SD1.D1_FILIAL = AFG.AFG_FILIAL AND SD1.D_E_L_E_T_ = ' ' 
           AND SD1.D1_PEDIDO = SC7.C7_NUM AND SD1.D1_ITEMPC = SC7.C7_ITEM 
           AND SD1.D1_XDESP between '000060' AND '000060' 
          JOIN SZ9010 SZ9 ON SZ9.Z9_FILIAL = AFG.AFG_FILIAL AND SZ9.D_E_L_E_T_ = ' ' AND SZ9.Z9_DESPESA = SD1.D1_XDESP 
         where AFG.D_E_L_E_T_ = ' ' AND AFG.AFG_FILIAL = '01' 
         group by SZ9.Z9_DESPESA, AF8.AF8_CLIENT, AF8.AF8_LOJA, AF8.AF8_PROJET, AF9.AF9_EDTPAI, SD1.D1_COD 
         union all 
        select SZ9.Z9_DESPESA, AF8.AF8_CLIENT AS C5_CLIENTE, AF8.AF8_LOJA AS C5_LOJACLI, 
               AF8.AF8_PROJET AS C5_XPROJET, AF9.AF9_EDTPAI AS C5_XTSKPMS, MIN(SA1.A1_TIPO) AS A1_TIPO, 
               '002' AS Z9_CONDPAG, SZ8.Z8_PRODUTO AS C6_PRODUTO, SUM(AFR.AFR_XQTDE) AS C6_QTDVEN, 
               SUM(AFR.AFR_XVAL_C) AS C6_PRCVEN 
          from AFR010 AFR 
          JOIN SZ8010 SZ8 ON SZ8.Z8_FILIAL = '  ' AND SZ8.D_E_L_E_T_ = ' ' AND SZ8.Z8_DESPESA = AFR.AFR_TIPOD 
          JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFR.AFR_FILIAL AND AF8.D_E_L_E_T_ = ' ' AND AF8.AF8_PROJET = AFR.AFR_PROJET 
           AND AF8.AF8_XDESP = '2' 
          JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT 
           AND SA1.A1_LOJA = AF8.AF8_LOJA 
          JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFR.AFR_FILIAL AND AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_PROJET = AFR.AFR_PROJET 
           AND AF9.AF9_REVISA = AFR.AFR_REVISA AND AF9.AF9_TAREFA = AFR.AFR_TAREFA 
          JOIN SE2010 SE2 ON SE2.E2_FILIAL = AFR.AFR_FILIAL AND SE2.D_E_L_E_T_ = ' ' AND SE2.E2_PREFIXO = AFR.AFR_PREFIX 
           AND SE2.E2_NUM = AFR.AFR_NUM AND SE2.E2_TIPO = AFR.AFR_TIPO AND SE2.E2_PARCELA = AFR.AFR_PARCEL 
          JOIN SZ9010 SZ9 ON SZ9.Z9_FILIAL = AFR.AFR_FILIAL AND SZ9.D_E_L_E_T_ = ' ' AND SZ9.Z9_DESPESA = AFR.AFR_XDESP 
         WHERE AFR.AFR_FILIAL = '01' AND AFR.D_E_L_E_T_ = ' ' 
         group by SZ9.Z9_DESPESA, AF8.AF8_CLIENT, AF8.AF8_LOJA, AF8.AF8_PROJET, AF9.AF9_EDTPAI, SZ8.Z8_PRODUTO) SZ9 
 group by SZ9.Z9_DESPESA, SZ9.C5_CLIENTE, SZ9.C5_LOJACLI, SZ9.A1_TIPO, SZ9.Z9_CONDPAG, SZ9.C5_XPROJET, SZ9.C5_XTSKPMS, SZ9.C6_PRODUTO 
 order by SZ9.Z9_DESPESA, SZ9.C5_CLIENTE, SZ9.C5_LOJACLI, SZ9.A1_TIPO, SZ9.Z9_CONDPAG, SZ9.C5_XPROJET, SZ9.C5_XTSKPMS, SZ9.C6_PRODUTO
 
SELECT * FROM SZ8010 WHERE D_E_L_E_T_ = ' '; 

UPDATE SZ8010 SET Z8_PRODUTO = 'SRV-PROGRAMACAO' WHERE D_E_L_E_T_ = ' ';

SELECT * FROM SB1010 WHERE D_E_L_E_T_ = ' ' AND B1_COD LIKE '%SRV%';

SELECT TOP 1 AF9_EDTPAI, * FROM AF9010;
SELECT TOP 1 AFC_XPROD, * FROM AFC010;