DROP VIEW REALIZADO;

-- Apontamentos
CREATE VIEW REALIZADO AS   
SELECT AFU.AFU_PROJET, SZ5.Z5_DESCRI, 
       CASE WHEN SZ6.Z6_GRUPO1 = '2' THEN 'SRV-INSTALACAO' 
            ELSE CASE WHEN SZ6.Z6_GRUPO1 = '3' THEN 'SRV-INTEGRACAO' 
            ELSE 'SRV-PROGRAMACAO' END END AS AFU_PRODUT,
       SUM(AFU.AFU_HQUANT) AS AFU_HQUANT
  FROM AFU010 AFU
  JOIN SZ6010 SZ6 ON SZ6.Z6_FILIAL = ' ' AND SZ6.D_E_L_E_T_ = ' ' AND SZ6.Z6_TAREFA = AFU.AFU_XSBTSK
   AND SZ6.Z6_GRUPO1 <> ''
  JOIN SZ5010 SZ5 ON SZ5.Z5_FILIAL = ' ' AND SZ5.D_E_L_E_T_ = ' ' AND SZ5.Z5_GRUPO = SZ6.Z6_GRUPO1
 WHERE AFU.AFU_FILIAL = '01' AND AFU.D_E_L_E_T_ = ' ' AND AFU.AFU_HQUANT > 0
   AND AFU.AFU_DATA >= '20120411'
 GROUP BY AFU.AFU_PROJET, SZ5.Z5_DESCRI,
          CASE WHEN SZ6.Z6_GRUPO1 = '2' THEN 'SRV-INSTALACAO' 
            ELSE CASE WHEN SZ6.Z6_GRUPO1 = '3' THEN 'SRV-INTEGRACAO' 
            ELSE 'SRV-PROGRAMACAO' END END;

-- Conferencia dos totais
SELECT SUM(AFU_HQUANT) AS AFU_HQUANT
 FROM (

SELECT AFU.AFU_XSBTSK, MIN(SZ6.Z6_GRUPO1) AS Z6_GRUPO1, SUM(AFU.AFU_HQUANT) AS AFU_HQUANT
  FROM AFU010 AFU
  LEFT JOIN SZ6010 SZ6 ON SZ6.Z6_FILIAL = ' ' AND SZ6.D_E_L_E_T_ = ' ' AND SZ6.Z6_TAREFA = AFU.AFU_XSBTSK
 WHERE AFU.D_E_L_E_T_ = ' ' AND AFU.AFU_PROJET = 'PMS001512A'
 GROUP BY AFU.AFU_XSBTSK
-- ORDER BY AFU.AFU_XSBTSK
) AS TAB 
WHERE Z6_GRUPO1 <> '';

SELECT TOP 1 * FROM AFU010;

select * from SZ6010 
 WHERE D_E_L_E_T_ = ' ' AND Z6_GRUPO1 <> ''
 ORDER BY Z6_TAREFA;

SELECT * from SZ5010 where D_E_L_E_T_ = ' ' AND Z5_TIPO = '1';

-- Previsto
DROP VIEW PREVISTO;

CREATE VIEW PREVISTO AS 
SELECT AFA_PROJET, AFA_PRODUT, SUM(AFA_QUANT) AS AFA_QUANT	-- // AFA_TAREFA, 
  FROM AFA010 AFA
 WHERE AFA.AFA_PROJET <> '' AND AFA.D_E_L_E_T_ = ' ' AND LEFT(AFA.AFA_PROJET, 3) = 'PMS' 
   AND AFA.AFA_PRODUT IN ('SRV-INSTALACAO', 'SRV-INSTALACAO2', 'SRV-INTEGRACAO', 'SRV-PROGRAMACAO')
   AND RIGHT(RTRIM(AFA.AFA_TAREFA), 3) = '.04'
 GROUP BY AFA_PROJET, AFA_PRODUT;
   
SELECT * FROM PREVISTO;
SELECT * FROM REALIZADO;

DROP VIEW REALIZADO_PREVISTO;
CREATE VIEW REALIZADO_PREVISTO AS 
SELECT AFU.AFU_PROJET, AFU.Z5_DESCRI, AFA.AFA_PRODUT, AFU.AFU_HQUANT, AFA.AFA_QUANT
  FROM REALIZADO AFU
  JOIN PREVISTO AFA ON AFA.AFA_PROJET = AFU.AFU_PROJET AND AFA.AFA_PRODUT = AFU.AFU_PRODUT;
  
SELECT * FROM PREVISTO  WHERE AFA_PROJET = 'PMS001512A'; 
SELECT * FROM REALIZADO WHERE AFU_PROJET = 'PMS001512A'; 

SELECT * FROM REALIZADO_PREVISTO WHERE AFU_PROJET = 'PMS001512A'; 

-- Comparação com a ociosidade
SELECT * FROM OCIOSIDADE WHERE AFU_PROJET = 'PMS001512A';

SELECT SUM(AFU_HQUANT) AS AFU_HQUANT 
  FROM OCIOSIDADE 
 WHERE AFU_PROJET = 'PMS001512A' AND Z6_GRUPO1 <> '';

-- AFU
SELECT R_E_C_N_O_, *
  FROM AFU010
 WHERE D_E_L_E_T_ = ' ' AND AFU_PROJET = 'PMS001512A'
   AND NOT EXISTS(SELECT 1 FROM AFU010_TMP WHERE R_E_C_N_O_ = AFU010.R_E_C_N_O_)
 ORDER BY R_E_C_N_O_

-- TMP
SELECT R_E_C_N_O_, *
  FROM AFU010_TMP
 WHERE AFU_PROJET = 'PMS001512A'
 ORDER BY R_E_C_N_O_
 
SELECT * from SZ5010 where D_E_L_E_T_ = ' ' AND Z5_TIPO = '1';

SELECT * FROM AE8010 WHERE AE8_RECURS = '9002';

   SELECT AFU.R_E_C_N_O_, AFU.AFU_PROJET, AF8.AF8_CLIENT, AF8.AF8_LOJA, SA1.A1_NOME, AFU.AFU_TAREFA, 
          AFU.AFU_RECURS, AFU.AFU_DATA, AFU.AFU_HORAI, AFU.AFU_HORAF, AFU.AFU_HQUANT, AFU.AFU_XSBTSK
     FROM AFU010 AFU
     JOIN AF8010 AF8 ON AF8.AF8_FILIAL = AFU.AFU_FILIAL AND AF8.D_E_L_E_T_ = ' '  AND AF8.AF8_PROJET = AFU.AFU_PROJET
     JOIN SA1010 SA1 ON SA1.A1_FILIAL = '  ' AND SA1.D_E_L_E_T_ = ' ' AND SA1.A1_COD = AF8.AF8_CLIENT
      AND SA1.A1_LOJA = AF8.AF8_LOJA
    WHERE AFU.AFU_FILIAL = '01' AND AFU.D_E_L_E_T_ = ' ' 
      AND AFU.AFU_DATA BETWEEN '19800101' and '30000101'
      AND AFU.AFU_PROJET = 'PMS001512A'
    ORDER BY AFU.AFU_RECURS, AFU.AFU_DATA, AFU.AFU_HORAI;
 
 
 ORDER BY AFU.AFU_RECURS, AFU.AFU_DATA, AFU.AFU_HORAI;
 
SELECT * FROM AFU010 WHERE R_E_C_N_O_ = 1589; 
    
-- 23/04/2012
SELECT * FROM AFA010 
 WHERE D_E_L_E_T_ = ' ' AND AFA_FILIAL = '01' AND AFA_PROJET = 'PMS001512A'
 ORDER BY AFA_TAREFA;

-- Com Grupo - 145,74
SELECT SUM(AFU_HQUANT)
 FROM
(
SELECT AFU.AFU_TAREFA, SZ6.Z6_GRUPO1, AFU.R_E_C_N_O_, AFU.AFU_XSBTSK, AFU.AFU_PROJET, SZ5.Z5_DESCRI, 
       CASE WHEN SZ6.Z6_GRUPO1 = '2' THEN 'SRV-INSTALACAO' 
            ELSE CASE WHEN SZ6.Z6_GRUPO1 = '3' THEN 'SRV-INTEGRACAO' 
            ELSE 'SRV-PROGRAMACAO' END END AS AFU_PRODUT,
       AFU.AFU_HQUANT
  FROM AFU010 AFU
  JOIN SZ6010 SZ6 ON SZ6.Z6_FILIAL = ' ' AND SZ6.D_E_L_E_T_ = ' ' AND SZ6.Z6_TAREFA = AFU.AFU_XSBTSK
   AND SZ6.Z6_GRUPO1 <> ''
  JOIN SZ5010 SZ5 ON SZ5.Z5_FILIAL = ' ' AND SZ5.D_E_L_E_T_ = ' ' AND SZ5.Z5_GRUPO = SZ6.Z6_GRUPO1
 WHERE AFU.AFU_FILIAL = '01' AND AFU.D_E_L_E_T_ = ' ' AND AFU.AFU_HQUANT > 0
   AND AFU.AFU_PROJET = 'PMS001512A'
--ORDER BY AFU.R_E_C_N_O_
) TAB;  

-- Sem Agrupamento: 154,24
SELECT SUM(AFU.AFU_HQUANT) AFU_HQUANT
  FROM AFU010 AFU
 WHERE AFU.AFU_FILIAL = '01' AND AFU.D_E_L_E_T_ = ' ' AND AFU.AFU_HQUANT > 0
   AND AFU.AFU_PROJET = 'PMS001512A'

SELECT * FROM AFU010 WHERE AFU_HQUANT = -1;

SELECT R_E_C_N_O_, AFU_RECURS, AFU_DATA, AFU_HORAI, AFU_HORAF FROM AFU010 AFU
 WHERE AFU.AFU_PROJET = 'PMS001512A' AND AFU.D_E_L_E_T_ = ' ' AND AFU.AFU_RECURS = '3084'
 ORDER BY AFU_RECURS, AFU_DATA, AFU_HORAI 
    
SELECT SEQUENCIAL, R_E_C_N_O_, AFU_RECURS, AFU_DATA, AFU_HORAI, AFU_HORAF 
  FROM AFU010_TMP AFU
 WHERE SEQUENCIAL > 0 AND AFU.AFU_RECURS = '3084'
 ORDER BY SEQUENCIAL

exec dt_pmsocioso '20120411', '20120423';

SELECT AFU.AFU_RECURS, COUNT(*) AS QUANTOS FROM AFU010 AFU
 WHERE AFU.AFU_PROJET = 'PMS001512A'
 GROUP BY AFU.AFU_RECURS;
 
SELECT AFU.AFU_RECURS, COUNT(*) AS QUANTOS FROM AFU010_TMP AFU
 WHERE AFU.AFU_PROJET = 'PMS001512A'
 GROUP BY AFU.AFU_RECURS; 
 
SELECT * FROM AFU010 WHERE AFU_DATA < '20120411' AND AFU_XSBTSK <> ''; 

