-- Produto A
select * from SB2010 where B2_COD = 'CELROB005511A';

select * from SC6010 where C6_PRODUTO = 'CELROB005511A';

select * from SC2010 where C2_PRODUTO = 'CELROB005511A' AND D_E_L_E_T_ = ' ';

select * from SD1010 where D1_COD = 'CELROB005511A';
select * from SD2010 where D2_COD = 'CELROB005511A';
select * from SD3010 where D3_COD = 'CELROB005511A';

-- Produto B
select * from SB2010 where B2_COD = 'CELROB005511B';

select * from SC6010 where C6_PRODUTO = 'CELROB005511B';

select * from SC2010 where C2_PRODUTO = 'CELROB005511B' AND D_E_L_E_T_ = ' ';

-- Quantidade AFA x ZZX
SELECT AFA.AFA_PRODUT, AFA.AFA_XQENTE, ZZX.ZZX_QTDE
  FROM AFA010 AFA
  LEFT JOIN (SELECT ZZX_COD, SUM(ZZX_QTDE) AS ZZX_QTDE
               FROM ZZX010 ZZX
              WHERE ZZX_PROJET = 'PMS005511A' AND ZZX_PRODUT = 'CELROB005511A' 
                AND D_E_L_E_T_ = ' '
           GROUP BY ZZX_COD) ZZX ON ZZX_COD = AFA.AFA_PRODUT
 WHERE AFA.AFA_PROJET = 'PMS005511A' AND AFA.AFA_TAREFA = '01.03' AND AFA.D_E_L_E_T_ = ' ';

-- Corrige quantidade entregue
UPDATE AFA010
   SET AFA_XQENTE = 0
 WHERE AFA_PROJET = 'PMS005511A' AND AFA_TAREFA = '01.03' AND D_E_L_E_T_ = ' ';

-- AFA
SELECT AFA_XQENTE, * FROM AFA010
 WHERE AFA_PROJET = 'PMS005511A' AND AFA_TAREFA = '01.03' AND D_E_L_E_T_ = ' '
   AND AFA_XQENTE > 0;

SELECT * FROM AFC010
 WHERE AFC_PROJET = 'PMS005511A' AND D_E_L_E_T_ = ' ';

-- ZZX
SELECT * FROM ZZX010
 WHERE ZZX_PROJET = 'PMS005511A' AND ZZX_PRODUT = 'CELROB005511A' AND D_E_L_E_T_ = ' ';
 
SELECT * FROM ZZX010
 WHERE ZZX_PROJET = 'PMS005511A' AND ZZX_PRODUT = 'CELROB005511B' AND D_E_L_E_T_ = ' '; 

-- Relacionamento 
SELECT ZZX_FILIAL,ZZX_PRODUT,ZZX_COD,SUM(ZZX_QTDE) ZZX_QTDE 
  FROM ZZX010 ZZX
 WHERE D_E_L_E_T_=' ' AND ZZX_FILIAL = '  ' AND ZZX_PROJET = 'PMS005511A'
 GROUP BY ZZX_FILIAL,ZZX_PRODUT,ZZX_COD
 ORDER BY ZZX_FILIAL,ZZX_PRODUT,ZZX_COD;
 
 SELECT AFA_PRODUT, AFA_TAREFA, SUM(AFA_QUANT) AS AFA_QUANT FROM AFA010
  WHERE AFA_PROJET = 'PMS005511A' AND AFA_TAREFA IN ('01.03', '02.03')
  GROUP BY AFA_PRODUT, AFA_TAREFA
  ORDER BY AFA_PRODUT, AFA_TAREFA;

-- EDT
SELECT * FROM AFC010
 WHERE AFC_PROJET = 'PMS005511A' AND D_E_L_E_T_ = ' ';

-- Tarefas
SELECT AF9_EDTPAI, * FROM AF9010
 WHERE AF9_PROJET = 'PMS005511A' AND AF9_TAREFA IN ('01.03', '02.03') AND D_E_L_E_T_ = ' ';

-- Produtos
SELECT AFA_XQENTE, * FROM AFA010
 WHERE AFA_PROJET = 'PMS005511A' AND AFA_TAREFA IN ('01.03', '02.03') AND D_E_L_E_T_ = ' '
 ORDER BY AFA_TAREFA, AFA_ITEM;
 
-- Vinculo EDF, Tarefa e Produtos
SELECT AFA.AFA_TAREFA, AFC.AFC_XPROD, AFA.AFA_PRODUT, AFA.AFA_QUANT, ZZX.ZZX_QTDE 
  FROM AFA010 AFA
  JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFA.AFA_FILIAL AND AF9.D_E_L_E_T_ = ' ' 
   AND AF9.AF9_PROJET = AFA.AFA_PROJET AND AF9.AF9_REVISA = AFA.AFA_REVISA 
   AND AF9.AF9_TAREFA = AFA.AFA_TAREFA
  JOIN AFC010 AFC ON AFC.AFC_FILIAL = AFA.AFA_FILIAL AND AFC.D_E_L_E_T_ = ' ' 
   AND AFC.AFC_PROJET = AFA.AFA_PROJET AND AFC.AFC_EDT = AF9.AF9_EDTPAI
  LEFT JOIN (SELECT ZZX_PRODUT,ZZX_COD,SUM(ZZX_QTDE) ZZX_QTDE 
               FROM ZZX010 ZZX
              WHERE D_E_L_E_T_=' ' AND ZZX_FILIAL = '  ' AND ZZX_PROJET = 'PMS005511A'
              GROUP BY ZZX_FILIAL,ZZX_PRODUT,ZZX_COD) ZZX ON ZZX.ZZX_PRODUT = AFC.AFC_XPROD
   AND ZZX.ZZX_COD = AFA.AFA_PRODUT
 WHERE AFA.AFA_FILIAL = '01' AND AFA.D_E_L_E_T_ = ' ' AND AFA.AFA_PROJET = 'PMS005511A'
   AND AFA.AFA_TAREFA IN ('01.03', '02.03')
   AND AFA.AFA_QUANT <> COALESCE(ZZX.ZZX_QTDE, 0) AND AFA.AFA_XESTRU = 'S'
 ORDER BY AFA.AFA_TAREFA, AFA.AFA_PRODUT;
 
-- Atualização da quantidade entregue
 UPDATE AFA010
    SET AFA_XQENTE = COALESCE(AFA.ZZX_QTDE, 0)
   FROM (SELECT AFA.R_E_C_N_O_, ZZX.ZZX_QTDE 
           FROM AFA010 AFA
           JOIN AF9010 AF9 ON AF9.AF9_FILIAL = AFA.AFA_FILIAL AND AF9.D_E_L_E_T_ = ' ' 
            AND AF9.AF9_PROJET = AFA.AFA_PROJET AND AF9.AF9_REVISA = AFA.AFA_REVISA 
            AND AF9.AF9_TAREFA = AFA.AFA_TAREFA
           JOIN AFC010 AFC ON AFC.AFC_FILIAL = AFA.AFA_FILIAL AND AFC.D_E_L_E_T_ = ' ' 
            AND AFC.AFC_PROJET = AFA.AFA_PROJET AND AFC.AFC_EDT = AF9.AF9_EDTPAI
      LEFT JOIN (SELECT ZZX_PRODUT,ZZX_COD,SUM(ZZX_QTDE) ZZX_QTDE 
                   FROM ZZX010 ZZX
                  WHERE D_E_L_E_T_=' ' AND ZZX_FILIAL = '  ' AND ZZX_PROJET = 'PMS005511A'
                  GROUP BY ZZX_FILIAL,ZZX_PRODUT,ZZX_COD) ZZX ON ZZX.ZZX_PRODUT = AFC.AFC_XPROD
            AND ZZX.ZZX_COD = AFA.AFA_PRODUT
          WHERE AFA.AFA_FILIAL = '01' AND AFA.D_E_L_E_T_ = ' ' AND AFA.AFA_PROJET = 'PMS005511A'
            AND AFA.AFA_TAREFA IN ('01.03', '02.03')) AFA 
 WHERE AFA010.R_E_C_N_O_ = AFA.R_E_C_N_O_;