SELECT SBF.BF_PRODUTO, SBF.BF_LOCAL, 
       SUM(CASE WHEN SBE.BE_XTPEND < '2' THEN SBF.BF_QUANT - SBF.BF_EMPENHO ELSE 0 END) AS BF_DISPONIVEL,
	   SUM(CASE WHEN SBE.BE_XTPEND > '1' THEN SBF.BF_QUANT - SBF.BF_EMPENHO ELSE 0 END) AS BF_PULMAO
  FROM SBF990 SBF
  JOIN SBE990 SBE ON SBE.D_E_L_E_T_ = ' ' AND SBE.BE_FILIAL = SBF.BF_FILIAL AND SBE.BE_LOCALIZ = SBF.BF_LOCALIZ 
 WHERE SBF.D_E_L_E_T_ = ' ' 
 GROUP BY SBF.BF_PRODUTO, SBF.BF_LOCAL
 ORDER BY SBF.BF_PRODUTO, SBF.BF_LOCAL;

SELECT SUM(CASE WHEN SBE.BE_XTPEND < '2' THEN SBF.BF_QUANT - SBF.BF_EMPENHO ELSE 0 END) AS BF_DISPONIVEL,
       SUM(CASE WHEN SBE.BE_XTPEND > '1' THEN SBF.BF_QUANT - SBF.BF_EMPENHO ELSE 0 END) AS BF_PULMAO 
  FROM SBF990 SBF 
  JOIN SBE990 SBE ON SBE.D_E_L_E_T_ = ' ' AND SBE.BE_FILIAL = SBF.BF_FILIAL AND SBE.BE_LOCALIZ = SBF.BF_LOCALIZ  
 WHERE SBF.D_E_L_E_T_ = ' ' AND SBF.BF_FILIAL = '01' AND SBF.BF_PRODUTO = '006            ' AND SBF.BF_LOCAL = '01'

SELECT C9_BLEST, * FROM SC9990 WHERE D_E_L_E_T_ = ' ' AND C9_PEDIDO = '000100';
SELECT * FROM SDC990 WHERE D_E_L_E_T_ = ' ' AND DC_PEDIDO = '000100';