SELECT RT_FILIAL, RT_MAT, RT_CC, RT_DATACAL, RT_TIPPROV, RT_VERBA 
  FROM SRT010
 WHERE RT_MAT = '3053' AND D_E_L_E_T_ = ' '
 GROUP BY RT_FILIAL, RT_MAT, RT_CC, RT_DATACAL, RT_TIPPROV, RT_VERBA   
HAVING COUNT(*) > 1
 ORDER BY RT_FILIAL, RT_MAT, RT_CC, RT_DATACAL, RT_TIPPROV, RT_VERBA;