SELECT SRA.RA_CATFUNC, SRC.RC_DATA, SUM(SRC.RC_VALOR) AS RC_VALOR
  FROM SRC010 SRC
  JOIN SRA010 SRA ON SRA.D_E_L_E_T_ = ' ' AND SRA.RA_FILIAL = '01' AND SRA.RA_MAT = SRC.RC_MAT
WHERE SRC.D_E_L_E_T_ = ' ' AND SRC.RC_DATA = '20120930' AND SRC.RC_PD = '713'
GROUP BY SRC.RC_DATA, SRA.RA_CATFUNC
ORDER BY SRC.RC_DATA, SRA.RA_CATFUNC;

SELECT * FROM SRA010 WHERE D_E_L_E_T_ = ' ' AND RA_CATFUNC = 'P';