-- Medica e Odontologica - Titular
SELECT RA_MAT, RA_NOME, RA_ASMEDIC, RA_TIPAMED, RA_DPASSME, RA_TPASODO, RA_ASODONT
  FROM SRA010
 WHERE D_E_L_E_T_ = ' ' AND RA_MAT = '3108'
 ORDER BY RA_MAT;

-- Medica e Odontologica - Dependente
SELECT RB_MAT, RB_COD, RB_NOME, RB_TPDEPAM, RB_TIPAMED, RB_CODAMED, RB_VBDESAM, RB_DTINIAM, RB_DTFIMAM, 
       RB_TPDPODO, RB_TPASODO, RB_ASODONT, RB_VBDESAO, RB_DTINIAO, RB_DTFIMAO
  FROM SRB010
 WHERE D_E_L_E_T_ = ' ' AND RB_MAT = '3108'
 ORDER BY RB_MAT;
 
SELECT * FROM SRB010 
 WHERE D_E_L_E_T_ = ' ' AND RB_ASODONT <> '' AND RB_TPASODO = ''
 
SELECT * FROM RHK010 WHERE D_E_L_E_T_ = ' ' AND RHK_MAT = '3108';
SELECT * FROM RHL010 WHERE D_E_L_E_T_ = ' ' AND RHL_MAT = '3108';

UPDATE SRB010 
   SET RB_TPASODO = '1'
 WHERE D_E_L_E_T_ = ' ' AND RB_ASODONT <> '' AND RB_TPASODO = ''

-- Preenche as verbas nos dependentes - Assistencia Médica
UPDATE RHL010
   SET RHL_PD = SRB010.RB_VBDESAM 
  FROM SRB010 
 WHERE RHL010.RHL_TPFORN = '1' AND RHL010.RHL_MAT = SRB010.RB_MAT AND RHL010.RHL_CODIGO = SRB010.RB_COD;

-- Preenche as verbas nos dependentes - Assistencia Odontologica
UPDATE RHL010
   SET RHL_PD = SRB010.RB_VBDESAO
  FROM SRB010 
 WHERE RHL010.RHL_TPFORN = '2' AND RHL010.RHL_MAT = SRB010.RB_MAT AND RHL010.RHL_CODIGO = SRB010.RB_COD;
