//-- Comparação do saldo empenhado no SB2 x SD4
SELECT SD4.D4_QUANT, SB2.B2_QEMP, SB2.* 
  FROM SB2010 SB2 
  LEFT JOIN (SELECT D4_COD, D4_LOCAL, SUM(D4_QUANT) AS D4_QUANT
               FROM SD4010
              WHERE D_E_L_E_T_ = ' '
              GROUP BY D4_COD, D4_LOCAL) SD4 ON SD4.D4_COD = SB2.B2_COD AND SD4.D4_LOCAL = SB2.B2_LOCAL
 WHERE SB2.D_E_L_E_T_ = ' ' AND SB2.B2_QEMP > 0 AND SB2.B2_QEMP <> COALESCE(SD4.D4_QUANT, 0)
 ORDER BY SB2.B2_COD, SB2.B2_LOCAL

//-- Lista de empenhos em aberto
SELECT * FROM SD4010 WHERE D_E_L_E_T_ = ' ' AND D4_QUANT > 0 ORDER BY D4_DATA