SELECT SLD_LOCAL.*, SLD_LOTE.*
  FROM
(
SELECT SUM(SB2.B2_QATU) AS SALDO_ATUAL, MIN(KDX.QUANT) AS SALDO_MOVIMENTO,
       SUM(SB2.B2_QATU) - MIN(KDX.QUANT) AS CONFERE_FECHAMENTO,
       MIN(SB9.B9_QINI) AS SALDO_FECHAMENTO, SUM(SB2.B2_QEMP) AS EMPENHO
  FROM SB2010 SB2
  JOIN (select SUM(QUANT) AS QUANT
          from KARDEX
         where DATA between '20120901' and '20120931' and B1_LOCAL = '01'
           and TIPO = 1
        having SUM(QUANT) <> 0) KDX ON KDX.QUANT = KDX.QUANT
  JOIN (SELECT SUM(B9_QINI) AS B9_QINI
          FROM SB9010
         WHERE D_E_L_E_T_ = ' ' AND B9_FILIAL = '01' AND B9_LOCAL = '01'
           AND B9_DATA = '20120831') SB9 ON SB9.B9_QINI = SB9.B9_QINI
 WHERE SB2.D_E_L_E_T_ = ' ' AND SB2.B2_FILIAL = '01' AND SB2.B2_LOCAL = '01') SLD_LOCAL
  JOIN (SELECT SUM(SB8.B8_QTDORI) AS B8_QTDORI, SUM(SB8.B8_SALDO) AS B8_SALDO,
               SUM(SB8.B8_EMPENHO) AS B8_EMPENHO,
               MIN(SBJ.BJ_QINI) AS BJ_QINI, MIN(SD5.D5_SALDO) AS D5_SALDO
          FROM SB8010 SB8
          JOIN (SELECT SUM(BJ_QINI) AS BJ_QINI
                  FROM SBJ010
                 WHERE D_E_L_E_T_ = ' ' AND BJ_FILIAL = '01' AND BJ_LOCAL = '01'
                   AND BJ_DATA = '20120831') SBJ ON SBJ.BJ_QINI = SBJ.BJ_QINI
          JOIN (select SUM(D5_QUANT * CASE WHEN D5_ORIGLAN < '500' THEN 1 ELSE -1 END) AS D5_SALDO
                  from SD5010
                 where D_E_L_E_T_ = ' ' AND D5_DATA <= '20120831') SD5 ON SD5.D5_SALDO = SD5.D5_SALDO
          where D_E_L_E_T_ = ' ') SLD_LOTE ON SLD_LOTE.B8_QTDORI = SLD_LOTE.B8_QTDORI;

-- Confere saldo de local x lote
SELECT SB9.B9_COD, SUM(SB9.B9_QINI) AS B9_QINI, MIN(SBJ.BJ_QINI) AS BJ_QINI
  FROM SB9010 SB9
  JOIN SB1010 SB1 ON SB1.D_E_L_E_T_ = ' ' AND SB1.B1_FILIAL = SB9.B9_FILIAL AND SB1.B1_COD = SB9.B9_COD 
   AND SB1.B1_RASTRO = 'L'
  LEFT JOIN (SELECT BJ_COD, SUM(BJ_QINI) AS BJ_QINI FROM SBJ010 
              WHERE D_E_L_E_T_ = ' ' AND BJ_DATA = '20120630'
              GROUP BY BJ_COD
             HAVING SUM(BJ_QINI) > 0) SBJ ON SBJ.BJ_COD = SB9.B9_COD 
 WHERE SB9.D_E_L_E_T_ = ' ' AND SB9.B9_FILIAL = '01' AND SB9.B9_DATA = '20120630'
 GROUP BY SB9.B9_COD
HAVING SUM(SB9.B9_QINI) = COALESCE(MIN(SBJ.BJ_QINI), 0)
 ORDER BY SB9.B9_COD DESC