SELECT *
  FROM SBJ450
 WHERE BJ_DATA = '20160229'
   AND D_E_L_E_T_ = ' '

-- Saldo por lote
SELECT D5_PRODUTO, D5_LOTECTL, D5_NUMLOTE, MIN(BJ_QINI) AS BJ_QINI, 
       SUM(CASE WHEN D5_ORIGLAN < '500' THEN D5_QUANT ELSE 0 END) AS ENTRADA, 
	   SUM(CASE WHEN D5_ORIGLAN >= '500' THEN D5_QUANT ELSE 0 END) AS SAIDA,
	   COALESCE(MIN(BJ_QINI), 0) +
	   COALESCE(SUM(CASE WHEN D5_ORIGLAN < '500' THEN D5_QUANT ELSE 0 END), 0) -
	   COALESCE(SUM(CASE WHEN D5_ORIGLAN >= '500' THEN D5_QUANT ELSE 0 END), 0) AS SALDO	   
  FROM SD5450 SD5
  LEFT JOIN SBJ450 SBJ ON SBJ.BJ_FILIAL = D5_FILIAL AND SBJ.BJ_COD = D5_PRODUTO AND SBJ.BJ_LOCAL = D5_LOCAL
   AND SBJ.BJ_LOTECTL = D5_LOTECTL AND BJ_NUMLOTE = D5_NUMLOTE AND BJ_DATA = '20160229' 
   AND SBJ.D_E_L_E_T_ = ' '
 WHERE SD5.D5_FILIAL = '01' AND D5_DATA BETWEEN '20160301' AND '20160331' AND SD5.D_E_L_E_T_ = ' '
 GROUP BY D5_PRODUTO, D5_LOTECTL, D5_NUMLOTE
 ORDER BY D5_PRODUTO, D5_LOTECTL, D5_NUMLOTE

-- Detalhado
SELECT *
  FROM SB9450
 WHERE B9_FILIAL = ' ' AND B9_COD = 'EA1572-9601G' AND D_E_L_E_T_ = ' '
 ORDER BY B9_DATA

SELECT * FROM SB8450 WHERE B8_FILIAL = ' ' AND B8_PRODUTO = 'EA1572-9601G' AND D_E_L_E_T_ = ' '

-- Totais por armazen
SELECT B9_FILIAL, B9_DATA, SUM(B9_QINI) AS B9_QINI, SUM(B9_CM1) AS B9_CM1
  FROM SB9450
 WHERE SUBSTRING(B9_DATA, 1, 4) = '2016' AND D_E_L_E_T_ = ' '
 GROUP BY B9_FILIAL, B9_DATA
 ORDER BY B9_FILIAL, B9_DATA

-- Totais por Lote
SELECT BJ_FILIAL, BJ_DATA, SUM(BJ_QINI) AS BJ_QINI
  FROM SBJ450
 WHERE SUBSTRING(BJ_DATA, 1, 4) = '2016' AND D_E_L_E_T_ = ' '
 GROUP BY BJ_FILIAL, BJ_DATA
 ORDER BY BJ_FILIAL, BJ_DATA

UPDATE SBJ450 SET BJ_FILIAL = '01' WHERE BJ_FILIAL = '02' AND BJ_DATA = '20160131'