-- Cabeçalho Requisição do Empenho
select * from ZZV010 WHERE ZZV_PROJET = 'PMS009711A';

-- Cabeçalho Requisição do Empenho
select * from ZZX010 where D_E_L_E_T_ = ' ' AND ZZX_COD = 'TESTE';

select AFC_XPROD, AFC_XPRODU, * from AFC010 where D_E_L_E_T_ = ' ' AND AFC_PROJET = 'PMS009711A';

-- Saldo em estoque
SELECT * FROM SB2010 WHERE B2_COD = 'TESTE';

-- Produtos do Projeto 
SELECT * FROM AFA010 WHERE AFA_PRODUT = 'TESTE';

-- Requisição de empenho pendentes - Sintética
SELECT ZZX.ZZX_COD, SUM(ZZX.ZZX_QTDE) AS ZZX_QTDE
  FROM ZZX010 ZZX
  JOIN AFC010 AFC ON AFC.D_E_L_E_T_ = ' ' AND AFC.AFC_FILIAL = '01' AND AFC.AFC_PROJET = ZZX.ZZX_PROJET 
   AND AFC.AFC_NIVEL > '001' AND AFC.AFC_XPROD = ZZX.ZZX_PRODUT
  JOIN AF9010 AF9 ON AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_FILIAL = AFC.AFC_FILIAL AND AF9.AF9_PROJET = ZZX.ZZX_PROJET 
   AND AF9.AF9_EDTPAI = AFC.AFC_EDT
  JOIN AFA010 AFA ON AFA.D_E_L_E_T_ = ' ' AND AFA.AFA_FILIAL = AFC.AFC_FILIAL AND AFA.AFA_PROJET = ZZX.ZZX_PROJET 
   AND AFA.AFA_TAREFA = AF9.AF9_TAREFA AND AFA.AFA_PRODUT = ZZX.ZZX_COD AND AFA.AFA_XESTRU = 'S'
  LEFT JOIN SD3010 SD3 ON SD3.D_E_L_E_T_ = ' ' AND SD3.D3_FILIAL = '01' AND SD3.D3_OP = AFC.AFC_XOP 
   AND SD3.D3_COD = ZZX.ZZX_COD
 WHERE ZZX.D_E_L_E_T_ = ' ' AND ZZX.ZZX_FILIAL = '  ' AND ZZX.ZZX_COD <> '' AND SD3.R_E_C_N_O_ IS NULL
 GROUP BY ZZX.ZZX_COD
 ORDER BY ZZX.ZZX_COD;
 
-- Requisição de empenho - detalhada
DROP VIEW EMPENHO_PENDENTE;
CREATE VIEW EMPENHO_PENDENTE AS
SELECT ZZX.ZZX_PROJET, ZZX.ZZX_NUM, ZZX_PRODUT, ZZX_COD, ZZX_QTDE, ZZX_TIPO, AFC.AFC_XOP, AFA.AFA_TAREFA, AFA.AFA_XQENTE,
       ZZX.D_E_L_E_T_
  FROM ZZX010 ZZX
  JOIN AFC010 AFC ON AFC.D_E_L_E_T_ = ' ' AND AFC.AFC_FILIAL = '01' AND AFC.AFC_PROJET = ZZX.ZZX_PROJET 
   AND AFC.AFC_NIVEL > '001' AND AFC.AFC_XPROD = ZZX.ZZX_PRODUT
  JOIN AF9010 AF9 ON AF9.D_E_L_E_T_ = ' ' AND AF9.AF9_FILIAL = AFC.AFC_FILIAL AND AF9.AF9_PROJET = ZZX.ZZX_PROJET 
   AND AF9.AF9_EDTPAI = AFC.AFC_EDT
  JOIN AFA010 AFA ON AFA.D_E_L_E_T_ = ' ' AND AFA.AFA_FILIAL = AFC.AFC_FILIAL AND AFA.AFA_PROJET = ZZX.ZZX_PROJET 
   AND AFA.AFA_TAREFA = AF9.AF9_TAREFA AND AFA.AFA_PRODUT = ZZX.ZZX_COD AND AFA.AFA_XESTRU = 'S'
  LEFT JOIN SD3010 SD3 ON SD3.D_E_L_E_T_ = ' ' AND SD3.D3_FILIAL = '01' AND SD3.D3_OP = AFC.AFC_XOP 
   AND SD3.D3_COD = ZZX.ZZX_COD
 WHERE ZZX.D_E_L_E_T_ = ' ' AND ZZX.ZZX_FILIAL = '  ' AND SD3.R_E_C_N_O_ IS NULL
-- ORDER BY AFC.AFC_XOP, ZZX.ZZX_PROJET, ZZX.ZZX_DATA, ZZX.R_E_C_N_O_;

DROP VIEW EMPENHO_PENDENTE_RESUMO;
CREATE VIEW EMPENHO_PENDENTE_RESUMO AS
SELECT ZZX_COD, SUM(ZZX_QTDE) AS ZZX_QTDE
  FROM EMPENHO_PENDENTE
 GROUP BY ZZX_COD;
 
SELECT * FROM EMPENHO_PENDENTE_RESUMO 
 ORDER BY ZZX_COD
 

SELECT AFC_XOP, * FROM AFC010 WHERE D_E_L_E_T_ = ' ' AND AFC_PROJET = 'PMS005511A';

SELECT AFA_XESTRU, AFA_QUANT, * FROM AFA010
 WHERE D_E_L_E_T_ = ' ' AND AFA_PRODUT = '150039-2' AND AFA_TAREFA = '01.02'
 AND AFA_PROJET = 'PMS005011A'; 

SELECT * FROM EMPENHO_PENDENTE WHERE ZZX_COD =  '150039-2'

SELECT * FROM ZZX010 WHERE D_E_L_E_T_ = ' ' AND ZZX_COD = '150039-2' 
AND ZZX_PROJET = 'PMS005011A'
ORDER BY ZZX_PRODUT;

SELECT * FROM SD3010 WHERE D3_COD LIKE '%5511A%'

SELECT * FROM AFC010 WHERE AFC_XOP = 'MSDHUK01001';

SELECT * FROM ZZX010 WHERE ZZX_PRODUT LIKE '%5511A%'

SELECT * FROM ZZX010 WHERE D_E_L_E_T_ = ' ' AND ZZX_PRODUT LIKE '%5011A%' AND ZZX_PROJET LIKE '%5511A%'

SELECT * FROM AFA010
 WHERE AFA_PROJET = 'PMS005511A' AND AFA_PRODUT = '150039-2';

SELECT * FROM SD3010 WHERE D_E_L_E_T_ = ' ' AND D3_FILIAL = '01' AND D3_COD = '150039-2' AND D3_OP IN ('MSDHUK01001', 'MSDHU801001');

