-- Nota de Entrada
SELECT SD1.D1_DTDIGIT, SD1.* FROM SD1010 SD1
  LEFT JOIN SC2010 SC2 ON SC2.D_E_L_E_T_ = ' ' AND SC2.C2_NUM || SC2.C2_ITEM || SC2.C2_SEQUEN = SD1.D1_OP
 WHERE SD1.D_E_L_E_T_ = ' ' AND SD1.D1_OP <> ' ' AND SC2.C2_NUM IS NULL;

-- Retira o vinculo
UPDATE SD1010
   SET D1_OP = ' '
 WHERE D_E_L_E_T_ = ' ' AND D1_OP <> ' ' AND R_E_C_N_O_ IN
(
SELECT SD1.R_E_C_N_O_ FROM SD1010 SD1
  LEFT JOIN SC2010 SC2 ON SC2.D_E_L_E_T_ = ' ' AND SC2.C2_NUM || SC2.C2_ITEM || SC2.C2_SEQUEN = SD1.D1_OP
 WHERE SD1.D_E_L_E_T_ = ' ' AND SD1.D1_OP <> ' ' AND SC2.C2_NUM IS NULL
);

-- Movimento de Estoque
SELECT SD3.* FROM SD3010 SD3
  LEFT JOIN SC2010 SC2 ON SC2.D_E_L_E_T_ = ' ' AND SC2.C2_NUM || SC2.C2_ITEM || SC2.C2_SEQUEN = SD3.D3_OP
 WHERE SD3.D_E_L_E_T_ = ' ' AND SD3.D3_OP <> ' ' AND SC2.C2_NUM IS NULL;

-- Retira o vinculo
UPDATE SD3010
   SET D3_OP = ' ', D3_XOBS = D3_OP
 WHERE D_E_L_E_T_ = ' ' AND D3_OP <> ' ' AND R_E_C_N_O_ IN
(
SELECT SD3.R_E_C_N_O_ FROM SD3010 SD3
  LEFT JOIN SC2010 SC2 ON SC2.D_E_L_E_T_ = ' ' AND SC2.C2_NUM || SC2.C2_ITEM || SC2.C2_SEQUEN = SD3.D3_OP
 WHERE SD3.D_E_L_E_T_ = ' ' AND SD3.D3_OP <> ' ' AND SC2.C2_NUM IS NULL
);
